/**
 * 行业指南页脚链接所需的最小数据（slug + 双语短标签）。
 * 与 guides.ts 分离：guides.ts 全文内容只进懒加载的 guide/tld chunk，不进首屏主 bundle。
 */
export const GUIDE_LABELS: { slug: string; zh: string; en: string }[] = [
  { slug: "saas", zh: "SaaS 工具", en: "SaaS tools" },
  { slug: "ecommerce", zh: "电商品牌", en: "E-commerce" },
  { slug: "ai", zh: "AI 产品", en: "AI products" },
  { slug: "fintech", zh: "金融科技", en: "Fintech" },
  { slug: "pets", zh: "宠物品牌", en: "Pet brands" },
  { slug: "blog", zh: "个人博客", en: "Blogs" },
  { slug: "game", zh: "游戏", en: "Games" },
  { slug: "edu", zh: "教育产品", en: "Education" },
  { slug: "travel", zh: "旅行", en: "Travel" },
  { slug: "food", zh: "餐饮美食", en: "Food & dining" },
  { slug: "fitness", zh: "健身健康", en: "Fitness" },
  { slug: "devtools", zh: "开发者工具", en: "Dev tools" },
  { slug: "web3", zh: "Web3 加密", en: "Web3" },
  { slug: "agency", zh: "咨询工作室", en: "Agencies" },
  { slug: "photography", zh: "摄影工作室", en: "Photography" },
  { slug: "podcast", zh: "播客节目", en: "Podcasts" },
  { slug: "realestate", zh: "房产家居", en: "Real estate" },
  { slug: "health", zh: "医疗健康", en: "Health" },
  { slug: "legal", zh: "法律服务", en: "Legal" },
  { slug: "newsletter", zh: "Newsletter", en: "Newsletters" },
  { slug: "music", zh: "音乐人", en: "Music & labels" },
  { slug: "beauty", zh: "美妆个护", en: "Beauty" },
  { slug: "nonprofit", zh: "公益组织", en: "Nonprofits" },
  { slug: "parenting", zh: "母婴亲子", en: "Parenting" },
  { slug: "hardware", zh: "智能硬件", en: "Hardware" },
  { slug: "security", zh: "网络安全", en: "Cybersecurity" },
  { slug: "creator", zh: "视频创作者", en: "Creators" },
  { slug: "freelance", zh: "自由职业", en: "Freelancers" },
  { slug: "fashion", zh: "服饰潮牌", en: "Fashion labels" },
  { slug: "coffee", zh: "咖啡茶饮", en: "Coffee & tea" },
  { slug: "automotive", zh: "汽车出行", en: "Automotive" },
  { slug: "community", zh: "社区俱乐部", en: "Communities" },
  { slug: "wedding", zh: "婚庆策划", en: "Wedding planners" },
  { slug: "bnb", zh: "民宿短租", en: "BnBs & stays" },
  { slug: "courses", zh: "在线课程", en: "Online courses" },
  { slug: "boardgame", zh: "桌游工作室", en: "Board games" },
  { slug: "outdoor", zh: "户外露营", en: "Outdoor & camping" },
  { slug: "cleaning", zh: "家政清洁", en: "Cleaning services" },
];
