/**
 * 行业指南页脚链接所需的最小数据（slug + 双语短标签）。
 * 与 guides.ts 分离：guides.ts 全文内容只进懒加载的 guide/tld chunk，不进首屏主 bundle。
 */
export const GUIDE_LABELS: { slug: string; zh: string; en: string }[] = [
  { slug: "saas", zh: "SaaS 工具", en: "SaaS tools" },
  { slug: "ecommerce", zh: "电商品牌", en: "E-commerce" },
  { slug: "ai", zh: "AI 产品", en: "AI products" },
  { slug: "fintech", zh: "金融科技", en: "Fintech" },
  { slug: "pets", zh: "宠物品牌", en: "Pet brands" },
  { slug: "blog", zh: "个人博客", en: "Blogs" },
  { slug: "game", zh: "游戏", en: "Games" },
  { slug: "edu", zh: "教育产品", en: "Education" },
  { slug: "travel", zh: "旅行", en: "Travel" },
  { slug: "food", zh: "餐饮美食", en: "Food & dining" },
  { slug: "fitness", zh: "健身健康", en: "Fitness" },
  { slug: "devtools", zh: "开发者工具", en: "Dev tools" },
  { slug: "web3", zh: "Web3 加密", en: "Web3" },
  { slug: "agency", zh: "咨询工作室", en: "Agencies" },
  { slug: "photography", zh: "摄影工作室", en: "Photography" },
  { slug: "podcast", zh: "播客节目", en: "Podcasts" },
  { slug: "realestate", zh: "房产家居", en: "Real estate" },
  { slug: "health", zh: "医疗健康", en: "Health" },
  { slug: "legal", zh: "法律服务", en: "Legal" },
  { slug: "newsletter", zh: "Newsletter", en: "Newsletters" },
  { slug: "music", zh: "音乐人", en: "Music & labels" },
  { slug: "beauty", zh: "美妆个护", en: "Beauty" },
  { slug: "nonprofit", zh: "公益组织", en: "Nonprofits" },
  { slug: "parenting", zh: "母婴亲子", en: "Parenting" },
  { slug: "hardware", zh: "智能硬件", en: "Hardware" },
  { slug: "security", zh: "网络安全", en: "Cybersecurity" },
  { slug: "creator", zh: "视频创作者", en: "Creators" },
  { slug: "freelance", zh: "自由职业", en: "Freelancers" },
  { slug: "fashion", zh: "服饰潮牌", en: "Fashion labels" },
  { slug: "coffee", zh: "咖啡茶饮", en: "Coffee & tea" },
  { slug: "automotive", zh: "汽车出行", en: "Automotive" },
  { slug: "community", zh: "社区俱乐部", en: "Communities" },
  { slug: "wedding", zh: "婚庆策划", en: "Wedding planners" },
  { slug: "bnb", zh: "民宿短租", en: "BnBs & stays" },
  { slug: "courses", zh: "在线课程", en: "Online courses" },
  { slug: "boardgame", zh: "桌游工作室", en: "Board games" },
  { slug: "outdoor", zh: "户外露营", en: "Outdoor & camping" },
  { slug: "cleaning", zh: "家政清洁", en: "Cleaning services" },
  { slug: "marketing", zh: "数字营销", en: "Digital marketing" },
  { slug: "therapy", zh: "心理咨询", en: "Therapy & mental health" },
  { slug: "resale", zh: "二手循环", en: "Resale & recommerce" },
  { slug: "recruiting", zh: "招聘人力", en: "Recruiting & HR" },
  { slug: "eldercare", zh: "养老服务", en: "Senior care" },
  { slug: "logistics", zh: "物流货运", en: "Logistics & freight" },
  { slug: "agent", zh: "AI 智能体", en: "AI agents" },
  { slug: "crossborder", zh: "跨境电商", en: "Cross-border e-commerce" },
  { slug: "escaperoom", zh: "剧本杀密室", en: "Escape rooms" },
  { slug: "bakery", zh: "烘焙甜品", en: "Bakeries & desserts" },
  { slug: "bookstore", zh: "书店出版", en: "Bookstores & publishing" },
  { slug: "florist", zh: "花店花艺", en: "Florists" },
  { slug: "interior", zh: "装修设计", en: "Interior & renovation" },
  { slug: "studyabroad", zh: "留学教育", en: "Study abroad" },
  { slug: "usedcar", zh: "二手车", en: "Used cars" },
  { slug: "insurance", zh: "保险经纪", en: "Insurance" },
  { slug: "farm", zh: "农场生鲜", en: "Farms & fresh food" },
  { slug: "barber", zh: "美发理容", en: "Barbershops & salons" },
  { slug: "yoga", zh: "瑜伽普拉提", en: "Yoga & Pilates" },
  { slug: "vet", zh: "宠物医院", en: "Vet clinics" },
  { slug: "esports", zh: "电竞战队", en: "Esports teams" },
  { slug: "drone", zh: "无人机航拍", en: "Drone & aerial" },
  { slug: "hanfu", zh: "汉服国潮", en: "Hanfu & guochao" },
  { slug: "dental", zh: "口腔诊所", en: "Dental clinics" },
  { slug: "accounting", zh: "会计财税", en: "Accounting & tax" },
  { slug: "livestream", zh: "直播电商", en: "Livestream commerce" },
  { slug: "translation", zh: "翻译本地化", en: "Translation & localization" },
  { slug: "gardening", zh: "园艺绿植", en: "Gardening & plants" },
  { slug: "coworking", zh: "联合办公", en: "Coworking spaces" },
  { slug: "solar", zh: "光伏新能源", en: "Solar & clean energy" },
  { slug: "coach", zh: "健身私教", en: "Personal training" },
  { slug: "codingschool", zh: "编程培训", en: "Coding bootcamps" },
  { slug: "jewelry", zh: "珠宝首饰", en: "Jewelry" },
  { slug: "toys", zh: "玩具品牌", en: "Toy brands" },
  { slug: "brewery", zh: "精酿酒饮", en: "Craft beer & drinks" },
  { slug: "furniture", zh: "家具品牌", en: "Furniture" },
  { slug: "crossfit", zh: "CrossFit 综合体能", en: "CrossFit & functional fitness" },
  { slug: "language", zh: "语言学习", en: "Language learning" },
  { slug: "resume", zh: "简历求职", en: "Resume & job search" },
  { slug: "events", zh: "活动策划", en: "Event planning" },
  { slug: "moving", zh: "搬家服务", en: "Moving services" },
  { slug: "aquarium", zh: "水族爬宠", en: "Aquariums & reptiles" },
  { slug: "indiehacker", zh: "独立开发者", en: "Indie hackers" },
  { slug: "petsupplies", zh: "宠物用品电商", en: "Pet supplies e-commerce" },
  { slug: "preschool", zh: "儿童早教", en: "Early childhood education" },
  { slug: "travelshoot", zh: "旅拍摄影", en: "Travel photography" },
  { slug: "forwarder", zh: "跨境物流", en: "Cross-border logistics" },
  { slug: "mcn", zh: "短视频 MCN", en: "Short-video MCN" },
  { slug: "opensource", zh: "开源项目", en: "Open source" },
  { slug: "indiegame", zh: "独立游戏", en: "Indie games" },
  { slug: "gearrental", zh: "影棚器材租赁", en: "Gear & studio rentals" },
  { slug: "sourcing", zh: "电商选品", en: "Product sourcing" },
  { slug: "fleamarket", zh: "线下市集", en: "Markets & pop-ups" },
  { slug: "ski", zh: "滑雪户外", en: "Ski & snow" },
  { slug: "aiart", zh: "AI 绘画", en: "AI art tools" },
  { slug: "campsite", zh: "露营地", en: "Campgrounds" },
  { slug: "tcm", zh: "中医养生", en: "TCM & wellness" },
  { slug: "deskcraft", zh: "桌面文创", en: "Desk & stationery" },
  { slug: "petmemorial", zh: "宠物殡葬", en: "Pet memorial" },
  { slug: "postpartum", zh: "月子中心", en: "Postpartum care" },
];
