/**
 * 行业指南页脚链接所需的最小数据（slug + 双语短标签）。
 * 与 guides.ts 分离：guides.ts 全文内容只进懒加载的 guide/tld chunk，不进首屏主 bundle。
 */
export const GUIDE_LABELS: { slug: string; zh: string; en: string }[] = [
  { slug: "saas", zh: "SaaS 工具", en: "SaaS tools" },
  { slug: "ecommerce", zh: "电商品牌", en: "E-commerce" },
  { slug: "ai", zh: "AI 产品", en: "AI products" },
  { slug: "fintech", zh: "金融科技", en: "Fintech" },
  { slug: "pets", zh: "宠物品牌", en: "Pet brands" },
  { slug: "blog", zh: "个人博客", en: "Blogs" },
  { slug: "game", zh: "游戏", en: "Games" },
  { slug: "edu", zh: "教育产品", en: "Education" },
  { slug: "travel", zh: "旅行", en: "Travel" },
  { slug: "food", zh: "餐饮美食", en: "Food & dining" },
  { slug: "fitness", zh: "健身健康", en: "Fitness" },
  { slug: "devtools", zh: "开发者工具", en: "Dev tools" },
  { slug: "web3", zh: "Web3 加密", en: "Web3" },
  { slug: "agency", zh: "咨询工作室", en: "Agencies" },
  { slug: "photography", zh: "摄影工作室", en: "Photography" },
  { slug: "podcast", zh: "播客节目", en: "Podcasts" },
  { slug: "realestate", zh: "房产家居", en: "Real estate" },
  { slug: "health", zh: "医疗健康", en: "Health" },
  { slug: "legal", zh: "法律服务", en: "Legal" },
  { slug: "newsletter", zh: "Newsletter", en: "Newsletters" },
  { slug: "music", zh: "音乐人", en: "Music & labels" },
  { slug: "beauty", zh: "美妆个护", en: "Beauty" },
  { slug: "nonprofit", zh: "公益组织", en: "Nonprofits" },
  { slug: "parenting", zh: "母婴亲子", en: "Parenting" },
  { slug: "hardware", zh: "智能硬件", en: "Hardware" },
  { slug: "security", zh: "网络安全", en: "Cybersecurity" },
  { slug: "creator", zh: "视频创作者", en: "Creators" },
  { slug: "freelance", zh: "自由职业", en: "Freelancers" },
  { slug: "fashion", zh: "服饰潮牌", en: "Fashion labels" },
  { slug: "coffee", zh: "咖啡茶饮", en: "Coffee & tea" },
  { slug: "automotive", zh: "汽车出行", en: "Automotive" },
  { slug: "community", zh: "社区俱乐部", en: "Communities" },
  { slug: "wedding", zh: "婚庆策划", en: "Wedding planners" },
  { slug: "bnb", zh: "民宿短租", en: "BnBs & stays" },
  { slug: "courses", zh: "在线课程", en: "Online courses" },
  { slug: "boardgame", zh: "桌游工作室", en: "Board games" },
  { slug: "outdoor", zh: "户外露营", en: "Outdoor & camping" },
  { slug: "cleaning", zh: "家政清洁", en: "Cleaning services" },
  { slug: "marketing", zh: "数字营销", en: "Digital marketing" },
  { slug: "therapy", zh: "心理咨询", en: "Therapy & mental health" },
  { slug: "resale", zh: "二手循环", en: "Resale & recommerce" },
  { slug: "recruiting", zh: "招聘人力", en: "Recruiting & HR" },
  { slug: "eldercare", zh: "养老服务", en: "Senior care" },
  { slug: "logistics", zh: "物流货运", en: "Logistics & freight" },
  { slug: "agent", zh: "AI 智能体", en: "AI agents" },
  { slug: "crossborder", zh: "跨境电商", en: "Cross-border e-commerce" },
  { slug: "escaperoom", zh: "剧本杀密室", en: "Escape rooms" },
  { slug: "bakery", zh: "烘焙甜品", en: "Bakeries & desserts" },
  { slug: "bookstore", zh: "书店出版", en: "Bookstores & publishing" },
  { slug: "florist", zh: "花店花艺", en: "Florists" },
  { slug: "interior", zh: "装修设计", en: "Interior & renovation" },
  { slug: "studyabroad", zh: "留学教育", en: "Study abroad" },
  { slug: "usedcar", zh: "二手车", en: "Used cars" },
  { slug: "insurance", zh: "保险经纪", en: "Insurance" },
  { slug: "farm", zh: "农场生鲜", en: "Farms & fresh food" },
  { slug: "barber", zh: "美发理容", en: "Barbershops & salons" },
  { slug: "yoga", zh: "瑜伽普拉提", en: "Yoga & Pilates" },
  { slug: "vet", zh: "宠物医院", en: "Vet clinics" },
  { slug: "esports", zh: "电竞战队", en: "Esports teams" },
  { slug: "drone", zh: "无人机航拍", en: "Drone & aerial" },
  { slug: "hanfu", zh: "汉服国潮", en: "Hanfu & guochao" },
  { slug: "dental", zh: "口腔诊所", en: "Dental clinics" },
  { slug: "accounting", zh: "会计财税", en: "Accounting & tax" },
  { slug: "livestream", zh: "直播电商", en: "Livestream commerce" },
  { slug: "translation", zh: "翻译本地化", en: "Translation & localization" },
  { slug: "gardening", zh: "园艺绿植", en: "Gardening & plants" },
  { slug: "coworking", zh: "联合办公", en: "Coworking spaces" },
  { slug: "solar", zh: "光伏新能源", en: "Solar & clean energy" },
  { slug: "coach", zh: "健身私教", en: "Personal training" },
  { slug: "codingschool", zh: "编程培训", en: "Coding bootcamps" },
  { slug: "jewelry", zh: "珠宝首饰", en: "Jewelry" },
  { slug: "toys", zh: "玩具品牌", en: "Toy brands" },
  { slug: "brewery", zh: "精酿酒饮", en: "Craft beer & drinks" },
  { slug: "furniture", zh: "家具品牌", en: "Furniture" },
  { slug: "crossfit", zh: "CrossFit 综合体能", en: "CrossFit & functional fitness" },
  { slug: "language", zh: "语言学习", en: "Language learning" },
  { slug: "resume", zh: "简历求职", en: "Resume & job search" },
  { slug: "events", zh: "活动策划", en: "Event planning" },
  { slug: "moving", zh: "搬家服务", en: "Moving services" },
  { slug: "aquarium", zh: "水族爬宠", en: "Aquariums & reptiles" },
  { slug: "indiehacker", zh: "独立开发者", en: "Indie hackers" },
  { slug: "petsupplies", zh: "宠物用品电商", en: "Pet supplies e-commerce" },
  { slug: "preschool", zh: "儿童早教", en: "Early childhood education" },
  { slug: "travelshoot", zh: "旅拍摄影", en: "Travel photography" },
  { slug: "forwarder", zh: "跨境物流", en: "Cross-border logistics" },
  { slug: "mcn", zh: "短视频 MCN", en: "Short-video MCN" },
  { slug: "opensource", zh: "开源项目", en: "Open source" },
  { slug: "indiegame", zh: "独立游戏", en: "Indie games" },
  { slug: "gearrental", zh: "影棚器材租赁", en: "Gear & studio rentals" },
  { slug: "sourcing", zh: "电商选品", en: "Product sourcing" },
  { slug: "fleamarket", zh: "线下市集", en: "Markets & pop-ups" },
  { slug: "ski", zh: "滑雪户外", en: "Ski & snow" },
  { slug: "aiart", zh: "AI 绘画", en: "AI art tools" },
  { slug: "campsite", zh: "露营地", en: "Campgrounds" },
  { slug: "tcm", zh: "中医养生", en: "TCM & wellness" },
  { slug: "deskcraft", zh: "桌面文创", en: "Desk & stationery" },
  { slug: "petmemorial", zh: "宠物殡葬", en: "Pet memorial" },
  { slug: "postpartum", zh: "月子中心", en: "Postpartum care" },
  { slug: "pettraining", zh: "宠物训练", en: "Pet training" },
  { slug: "nailsalon", zh: "美甲美睫", en: "Nail & lash studios" },
  { slug: "laundry", zh: "洗衣洗护", en: "Laundry & garment care" },
  { slug: "rvtravel", zh: "房车旅行", en: "RV travel" },
  { slug: "knowledgepay", zh: "知识付费", en: "Paid knowledge" },
  { slug: "matchmaking", zh: "婚恋相亲", en: "Matchmaking & dating" },
  { slug: "tattoo", zh: "纹身工作室", en: "Tattoo studios" },
  { slug: "climbing", zh: "攀岩馆", en: "Climbing gyms" },
  { slug: "swimschool", zh: "游泳培训", en: "Swim schools" },
  { slug: "3dprint", zh: "3D 打印", en: "3D printing" },
  { slug: "vending", zh: "无人零售", en: "Vending & unattended retail" },
  { slug: "kidsart", zh: "少儿美术", en: "Kids' art schools" },
  { slug: "danceschool", zh: "舞蹈工作室", en: "Dance studios" },
  { slug: "martialarts", zh: "武术格斗馆", en: "Martial arts gyms" },
  { slug: "bikeshop", zh: "骑行单车", en: "Bike shops & cycling" },
  { slug: "fishing", zh: "垂钓渔具", en: "Fishing & tackle" },
  { slug: "foodtruck", zh: "餐车小吃", en: "Food trucks & street food" },
  { slug: "repair", zh: "维修服务", en: "Repair & handyman services" },
  { slug: "pottery", zh: "陶艺手作", en: "Pottery & ceramics" },
  { slug: "billiards", zh: "台球桌球馆", en: "Billiards & pool halls" },
  { slug: "drivingschool", zh: "驾校驾培", en: "Driving schools" },
  { slug: "optician", zh: "眼镜视光", en: "Opticians & eyewear" },
  { slug: "massage", zh: "按摩推拿", en: "Massage & bodywork" },
  { slug: "mealprep", zh: "轻食健康餐", en: "Meal prep & healthy eats" },
  { slug: "petphoto", zh: "宠物摄影", en: "Pet photography" },
  { slug: "campgear", zh: "露营装备", en: "Camping gear" },
  { slug: "careercoach", zh: "职业规划咨询", en: "Career coaching" },
  { slug: "fragrance", zh: "香氛蜡烛", en: "Home fragrance & candles" },
  { slug: "diving", zh: "潜水俱乐部", en: "Diving & scuba" },
  { slug: "carwash", zh: "汽车美容洗车", en: "Car wash & detailing" },
  { slug: "studytour", zh: "研学营地", en: "Study camps & tours" },
  { slug: "petboarding", zh: "宠物寄养", en: "Pet boarding" },
  { slug: "upcycling", zh: "旧物改造", en: "Upcycling & rework" },
  { slug: "zine", zh: "独立杂志", en: "Indie magazines & zines" },
  { slug: "locksmith", zh: "开锁换锁", en: "Locksmiths" },
  { slug: "skateshop", zh: "滑板店", en: "Skate shops" },
  { slug: "surf", zh: "冲浪俱乐部", en: "Surf clubs" },
  { slug: "golf", zh: "高尔夫", en: "Golf" },
  { slug: "vr", zh: "VR 体验馆", en: "VR arcades" },
  { slug: "bar", zh: "酒吧清吧", en: "Bars & lounges" },
  { slug: "musicschool", zh: "音乐培训琴行", en: "Music schools" },
  { slug: "chess", zh: "棋类培训", en: "Chess & Go academies" },
  { slug: "hotpot", zh: "火锅烧烤", en: "Hotpot & BBQ" },
  { slug: "dessert", zh: "甜品冰淇淋", en: "Dessert & ice cream" },
  { slug: "convenience", zh: "社区便利店", en: "Convenience stores" },
  { slug: "stationery", zh: "文创文具", en: "Stationery & paper goods" },
  { slug: "cybercafe", zh: "电竞网咖", en: "Esports cafés" },
  { slug: "carrental", zh: "租车出行", en: "Car rental & mobility" },
  { slug: "noodle", zh: "粉面小吃", en: "Noodle shops" },
  { slug: "grocery", zh: "社区生鲜", en: "Fresh groceries" },
  { slug: "tutoring", zh: "课外辅导", en: "Tutoring & test prep" },
  { slug: "printshop", zh: "图文快印", en: "Print shops" },
  { slug: "errand", zh: "同城跑腿", en: "Errand & courier services" },
  { slug: "plumber", zh: "管道疏通维修", en: "Plumbing & repair" },
  { slug: "travelagency", zh: "旅行社", en: "Travel agencies" },
  { slug: "teahouse", zh: "茶馆茶室", en: "Tea houses & tea brands" },
  { slug: "petcafe", zh: "宠物咖啡", en: "Pet cafés" },
  { slug: "weddingphoto", zh: "婚纱摄影", en: "Wedding photography" },
  { slug: "footspa", zh: "足疗采耳", en: "Foot spas & wellness lounges" },
  { slug: "parcel", zh: "快递驿站", en: "Parcel stations & pickup points" },
  { slug: "realtor", zh: "房产中介", en: "Real estate agencies" },
  { slug: "propertymgmt", zh: "物业管理", en: "Property management" },
  { slug: "apartment", zh: "长租公寓", en: "Apartment rentals" },
  { slug: "construction", zh: "建筑施工", en: "Construction & contracting" },
  { slug: "appliancerepair", zh: "家电维修", en: "Appliance repair" },
  { slug: "equipmentrental", zh: "设备租赁", en: "Equipment rental" },
  { slug: "hotel", zh: "酒店旅宿", en: "Hotels & lodging" },
  { slug: "karaoke", zh: "量贩KTV", en: "Karaoke lounges" },
  { slug: "bubbletea", zh: "奶茶茶饮", en: "Bubble tea shops" },
  { slug: "bbq", zh: "烧烤夜宵", en: "BBQ & late-night grills" },
  { slug: "pharmacy", zh: "连锁药店", en: "Pharmacies" },
  { slug: "clinic", zh: "诊所门诊", en: "Clinics & outpatient care" },
  { slug: "evcharging", zh: "充电桩运营", en: "EV charging" },
  { slug: "energystorage", zh: "储能系统", en: "Energy storage" },
  { slug: "recycling", zh: "再生资源回收", en: "Recycling & recovery" },
  { slug: "retrofit", zh: "节能改造", en: "Energy retrofits" },
  { slug: "hvac", zh: "暖通空调", en: "HVAC services" },
  { slug: "watertreatment", zh: "水处理环保", en: "Water treatment" },
  { slug: "babystore", zh: "母婴用品", en: "Baby & maternity stores" },
  { slug: "kidsphoto", zh: "儿童摄影", en: "Kids' photography" },
  { slug: "giftcustom", zh: "礼品定制", en: "Custom gifts" },
  { slug: "petgrooming", zh: "宠物美容", en: "Pet grooming" },
  { slug: "housekeeping", zh: "家政服务", en: "Housekeeping services" },
  { slug: "kidsplayground", zh: "亲子乐园", en: "Kids' playgrounds" },
  { slug: "productphoto", zh: "电商产品摄影", en: "Product photography" },
  { slug: "portrait", zh: "个人写真", en: "Portrait studios" },
  { slug: "foodreview", zh: "探店测评", en: "Food reviews" },
  { slug: "nutrition", zh: "营养师咨询", en: "Nutrition coaching" },
  { slug: "physio", zh: "康复理疗", en: "Physiotherapy & rehab" },
  { slug: "runclub", zh: "跑步俱乐部", en: "Run clubs" },
  { slug: "tennis", zh: "网球俱乐部", en: "Tennis clubs" },
  { slug: "soccer", zh: "足球青训", en: "Soccer academies" },
  { slug: "football", zh: "腰旗橄榄球", en: "Flag football" },
  { slug: "hockey", zh: "冰球俱乐部", en: "Hockey clubs" },
  { slug: "pickleball", zh: "匹克球", en: "Pickleball" },
  { slug: "pilates", zh: "普拉提馆", en: "Pilates studios" },
  { slug: "companyreg", zh: "公司注册代办", en: "Company formation services" },
  { slug: "consulting", zh: "管理咨询", en: "Management consulting" },
  { slug: "wholesale", zh: "B2B 批发平台", en: "B2B wholesale platforms" },
  { slug: "trading", zh: "外贸公司", en: "Import & export trading" },
  { slug: "coupon", zh: "优惠券导购", en: "Coupon & deals platforms" },
  { slug: "flashsale", zh: "限时特卖电商", en: "Flash sale e-commerce" },
  { slug: "pestcontrol", zh: "害虫防治", en: "Pest control" },
  { slug: "roofing", zh: "屋顶施工", en: "Roofing" },
  { slug: "towing", zh: "道路救援", en: "Towing & roadside" },
  { slug: "selfstorage", zh: "自助仓储", en: "Self-storage" },
  { slug: "catering", zh: "宴会团餐", en: "Catering" },
  { slug: "signage", zh: "广告标识", en: "Signage & signs" },
  { slug: "shortvideo", zh: "短视频制作", en: "Short-video production" },
  { slug: "audiobook", zh: "有声书配音", en: "Audiobooks & voiceover" },
  { slug: "postproduction", zh: "影视后期", en: "Post-production & VFX" },
  { slug: "animation", zh: "动画工作室", en: "Animation studios" },
  { slug: "documentary", zh: "纪录片工作室", en: "Documentary studios" },
  { slug: "newsmedia", zh: "独立新闻媒体", en: "Independent news media" },
  { slug: "fruitshop", zh: "水果店", en: "Fruit shops" },
  { slug: "seafood", zh: "海鲜餐厅", en: "Seafood restaurants" },
  { slug: "tailor", zh: "服装定制", en: "Custom tailoring" },
  { slug: "equestrian", zh: "马术俱乐部", en: "Equestrian clubs" },
  { slug: "archery", zh: "射箭馆", en: "Archery ranges" },
  { slug: "immigration", zh: "移民咨询", en: "Immigration consulting" },
  { slug: "deli", zh: "卤味熟食", en: "Deli & braised food" },
  { slug: "winery", zh: "精品酒庄", en: "Boutique wineries" },
  { slug: "sushi", zh: "日料餐厅", en: "Sushi & Japanese dining" },
  { slug: "icecream", zh: "冰淇淋品牌", en: "Ice cream brands" },
  { slug: "hostel", zh: "青年旅舍", en: "Hostels" },
  { slug: "bowling", zh: "保龄球馆", en: "Bowling alleys" },
  { slug: "tea", zh: "茶叶品牌", en: "Tea brands" },
  { slug: "hotspring", zh: "温泉度假", en: "Hot spring resorts" },
  { slug: "trampoline", zh: "蹦床公园", en: "Trampoline parks" },
  { slug: "funeral", zh: "殡葬服务", en: "Funeral & memorial services" },
  { slug: "securityguard", zh: "安保服务", en: "Security services" },
  { slug: "ipagency", zh: "知识产权代理", en: "IP & patent services" },
  { slug: "wig", zh: "假发品牌", en: "Wig brands" },
  { slug: "skincare", zh: "护肤品牌", en: "Skincare brands" },
  { slug: "makeupartist", zh: "化妆造型工作室", en: "Makeup artists" },
  { slug: "homestaging", zh: "房屋整备布置", en: "Home staging" },
  { slug: "yachtcharter", zh: "游艇租赁俱乐部", en: "Yacht charters" },
  { slug: "autoparts", zh: "汽配用品品牌", en: "Auto parts brands" },
  { slug: "robotics", zh: "机器人公司", en: "Robotics companies" },
  { slug: "nocode", zh: "无代码工具", en: "No-code tools" },
  { slug: "badminton", zh: "羽毛球馆", en: "Badminton clubs" },
  { slug: "gokart", zh: "卡丁车馆", en: "Go-kart venues" },
  { slug: "sauna", zh: "汗蒸桑拿馆", en: "Sauna studios" },
  { slug: "pizza", zh: "披萨店", en: "Pizza shops" },
  { slug: "electrician", zh: "电工电气服务", en: "Electricians" },
  { slug: "landscaping", zh: "园林景观", en: "Landscaping" },
  { slug: "painting", zh: "油漆粉刷", en: "Painting contractors" },
  { slug: "jobboard", zh: "招聘求职平台", en: "Job boards" },
  { slug: "restaurantsupply", zh: "餐饮设备供应", en: "Restaurant supply" },
  { slug: "motorcycleparts", zh: "摩托车配件", en: "Motorcycle parts" },
  { slug: "auction", zh: "拍卖行", en: "Auction houses" },
  { slug: "antiques", zh: "古董古玩店", en: "Antique shops" },
  { slug: "lightingbrand", zh: "灯具照明品牌", en: "Lighting brands" },
  { slug: "outlet", zh: "折扣特卖店", en: "Outlet & discount stores" },
  { slug: "watches", zh: "腕表钟表店", en: "Watch brands & dealers" },
  { slug: "sneakers", zh: "球鞋潮鞋店", en: "Sneaker shops" },
  { slug: "dollarstore", zh: "一元折扣店", en: "Dollar stores" },
  { slug: "thriftstore", zh: "二手循环店", en: "Thrift stores" },
  { slug: "officesupplies", zh: "办公用品", en: "Office supplies" },
  { slug: "medicalsupplies", zh: "医疗用品", en: "Medical supplies" },
  { slug: "buildingmaterials", zh: "建材五金", en: "Building materials" },
  { slug: "franchise", zh: "连锁加盟", en: "Franchise brands" },
  { slug: "villarental", zh: "民宿别墅短租", en: "Villa rentals" },
  { slug: "cruise", zh: "邮轮旅行社", en: "Cruise agencies" },
  { slug: "customtour", zh: "定制旅行", en: "Bespoke travel" },
  { slug: "limoservice", zh: "豪车接送", en: "Limo services" },
  { slug: "ticketing", zh: "票务平台", en: "Ticketing platforms" },
  { slug: "flowerdelivery", zh: "鲜花电商", en: "Flower delivery" },
  { slug: "taproom", zh: "精酿酒馆", en: "Taprooms" },
  { slug: "izakaya", zh: "居酒屋", en: "Izakayas" },
  { slug: "dayspa", zh: "水疗会所", en: "Day spas" },
  { slug: "snacks", zh: "零食品牌", en: "Snack brands" },
  { slug: "lawfirm", zh: "律师事务所", en: "Law firms" },
  { slug: "orthodontics", zh: "正畸齿科", en: "Orthodontics" },
  { slug: "kidswear", zh: "童装品牌", en: "Kidswear brands" },
  { slug: "cookingclass", zh: "烹饪教室", en: "Cooking classes" },
  { slug: "souvenir", zh: "伴手礼品牌", en: "Souvenir brands" },
  { slug: "partyplanner", zh: "派对策划", en: "Party planners" },
  { slug: "seafishing", zh: "海钓包船", en: "Sea fishing charters" },
  { slug: "horseranch", zh: "马场骑乘", en: "Horse ranches" },
  { slug: "datingapp", zh: "交友App", en: "Dating apps" },
  { slug: "singlesevents", zh: "单身社交活动", en: "Singles events" },
  { slug: "luxuryresale", zh: "中古奢侈品", en: "Luxury resale" },
  { slug: "organicfood", zh: "有机食品电商", en: "Organic food" },
  { slug: "permanentmakeup", zh: "半永久纹绣", en: "Permanent makeup" },
  { slug: "homedecor", zh: "家居饰品", en: "Home decor" },
  { slug: "craftvodka", zh: "精酿伏特加", en: "Craft vodka" },
  { slug: "esportsnews", zh: "棋牌电竞资讯", en: "Esports & gaming news" },
  { slug: "sportsodds", zh: "体育竞猜资讯", en: "Sports odds & analysis" },
  { slug: "tabletopclub", zh: "桌游俱乐部", en: "Tabletop clubs" },
  { slug: "futsal", zh: "五人制足球场馆", en: "Futsal venues" },
  { slug: "fashionbuyer", zh: "快时尚买手店", en: "Fashion select shops" },
  { slug: "basketball", zh: "篮球培训", en: "Basketball training" },
  { slug: "rugby", zh: "橄榄球俱乐部", en: "Rugby clubs" },
  { slug: "cricket", zh: "板球社区", en: "Cricket communities" },
  { slug: "aquascaping", zh: "观赏鱼造景", en: "Aquascaping" },
  { slug: "fanclub", zh: "粉丝应援站", en: "Fan clubs" },
  { slug: "giveaway", zh: "抽奖活动平台", en: "Giveaway platforms" },
  { slug: "volleyball", zh: "排球俱乐部", en: "Volleyball clubs" },
  { slug: "tabletennis", zh: "乒乓球俱乐部", en: "Table tennis clubs" },
  { slug: "baseball", zh: "棒球培训", en: "Baseball training" },
  { slug: "boxing", zh: "拳击馆", en: "Boxing gyms" },
  { slug: "taekwondo", zh: "跆拳道馆", en: "Taekwondo schools" },
  { slug: "fencing", zh: "击剑俱乐部", en: "Fencing clubs" },
  { slug: "gymnastics", zh: "体操培训", en: "Gymnastics academies" },
  { slug: "cheerleading", zh: "啦啦操", en: "Cheerleading" },
  { slug: "squash", zh: "壁球馆", en: "Squash clubs" },
  { slug: "lacrosse", zh: "长曲棍球", en: "Lacrosse clubs" },
  { slug: "judo", zh: "柔道馆", en: "Judo dojos" },
  { slug: "bjj", zh: "巴西柔术", en: "BJJ academies" },
  { slug: "wrestling", zh: "摔跤馆", en: "Wrestling clubs" },
  { slug: "muaythai", zh: "泰拳馆", en: "Muay Thai gyms" },
  { slug: "handball", zh: "手球俱乐部", en: "Handball clubs" },
  { slug: "curling", zh: "冰壶俱乐部", en: "Curling clubs" },
  { slug: "rowing", zh: "赛艇俱乐部", en: "Rowing clubs" },
  { slug: "skating", zh: "轮滑滑冰", en: "Skating clubs" },
  { slug: "candle", zh: "香薰蜡烛", en: "Candle brands" },
  { slug: "juicebar", zh: "果汁轻食吧", en: "Juice bars" },
  { slug: "leathercraft", zh: "皮具工作室", en: "Leather studios" },
  { slug: "calligraphy", zh: "书法工作室", en: "Calligraphy studios" },
  { slug: "instrumentstore", zh: "乐器行", en: "Instrument stores" },
  { slug: "meditation", zh: "冥想馆", en: "Meditation studios" },
  { slug: "woodworking", zh: "木工工作室", en: "Woodworking studios" },
  { slug: "soapmaking", zh: "手工皂", en: "Soap brands" },
  { slug: "modelkit", zh: "模型手办店", en: "Model kit stores" },
  { slug: "framing", zh: "装裱画框店", en: "Framing shops" },
  { slug: "recordingstudio", zh: "录音棚", en: "Recording studios" },
  { slug: "hearingaid", zh: "助听器验配", en: "Hearing aid centers" },
  { slug: "watchrepair", zh: "钟表维修", en: "Watch repair shops" },
  { slug: "beekeeping", zh: "蜂蜜品牌", en: "Honey brands" },
  { slug: "glassblowing", zh: "玻璃工作室", en: "Glass studios" },
  { slug: "bonsai", zh: "盆景园", en: "Bonsai studios" },
  { slug: "recordstore", zh: "黑胶唱片店", en: "Record stores" },
  { slug: "embroidery", zh: "刺绣工作室", en: "Embroidery studios" },
  { slug: "sealcarving", zh: "篆刻工作室", en: "Seal carving studios" },
  { slug: "incense", zh: "香道工作室", en: "Incense studios" },
  { slug: "papercut", zh: "剪纸工作室", en: "Papercut studios" },
  { slug: "lantern", zh: "灯笼工坊", en: "Lantern workshops" },
  { slug: "quilting", zh: "拼布工作室", en: "Quilting studios" },
  { slug: "teaware", zh: "茶器工作室", en: "Teaware studios" },
  { slug: "kite", zh: "风筝工坊", en: "Kite workshops" },
  { slug: "succulent", zh: "多肉植物店", en: "Succulent shops" },
  { slug: "chocolate", zh: "手工巧克力", en: "Craft chocolate" },
  { slug: "weaving", zh: "织造工作室", en: "Weaving studios" },
  { slug: "puppet", zh: "木偶皮影工作室", en: "Puppetry studios" },
  { slug: "birding", zh: "观鸟俱乐部", en: "Birding clubs" },
  { slug: "stargazing", zh: "观星俱乐部", en: "Stargazing clubs" },
  { slug: "cidery", zh: "苹果酒坊", en: "Craft cideries" },
  { slug: "bookbinding", zh: "手工装帧工作室", en: "Bookbinding studios" },
  { slug: "letterpress", zh: "活版印刷工作室", en: "Letterpress studios" },
  { slug: "terrarium", zh: "生态瓶工作室", en: "Terrarium studios" },
  { slug: "axethrowing", zh: "飞斧馆", en: "Axe-throwing venues" },
  { slug: "lasertag", zh: "镭射对战馆", en: "Laser tag arenas" },
  { slug: "paintball", zh: "彩弹射击场", en: "Paintball fields" },
  { slug: "mushroomfarm", zh: "菌菇农场", en: "Mushroom farms" },
  { slug: "neonsign", zh: "霓虹灯工作室", en: "Neon sign studios" },
  { slug: "millinery", zh: "制帽工作室", en: "Millinery studios" },
  { slug: "mosaic", zh: "马赛克工作室", en: "Mosaic studios" },
  { slug: "blacksmith", zh: "铁匠铺", en: "Blacksmith forges" },
  { slug: "distillery", zh: "精酿蒸馏厂", en: "Craft distilleries" },
  { slug: "kombucha", zh: "康普茶品牌", en: "Kombucha brands" },
  { slug: "climbinggym", zh: "攀岩馆", en: "Climbing gyms" },
  { slug: "stainedglass", zh: "彩绘玻璃工作室", en: "Stained glass studios" },
  { slug: "minigolf", zh: "迷你高尔夫球场", en: "Mini golf courses" },
  { slug: "taxidermy", zh: "标本工作室", en: "Taxidermy studios" },
  { slug: "cheesemaking", zh: "奶酪工坊", en: "Cheesemaking studios" },
  { slug: "meadery", zh: "蜂蜜酒厂", en: "Meaderies" },
  { slug: "tufting", zh: "簇绒工作室", en: "Tufting studios" },
  { slug: "silversmith", zh: "银匠工作室", en: "Silversmith studios" },
  { slug: "falconry", zh: "猛禽体验基地", en: "Falconry experiences" },
  { slug: "lutherie", zh: "制琴工作室", en: "Lutherie studios" },
  { slug: "lapidary", zh: "宝石切磨工作室", en: "Lapidary studios" },
  { slug: "cooperage", zh: "制桶工坊", en: "Cooperages" },
  { slug: "kintsugi", zh: "金缮修复工作室", en: "Kintsugi studios" },
  { slug: "indigodye", zh: "蓝染工坊", en: "Indigo dye studios" },
  { slug: "penmaking", zh: "手工制笔工作室", en: "Penmaking studios" },
  { slug: "marquetry", zh: "细木镶嵌工作室", en: "Marquetry studios" },
  { slug: "cloisonne", zh: "掐丝珐琅工作室", en: "Cloisonné studios" },
  { slug: "papermaking", zh: "手工造纸工坊", en: "Papermaking studios" },
  { slug: "inkstone", zh: "制砚工坊", en: "Inkstone studios" },
  { slug: "fletching", zh: "制箭工坊", en: "Fletching workshops" },
  { slug: "gilding", zh: "贴金工坊", en: "Gilding studios" },
  { slug: "lacquerware", zh: "漆艺工坊", en: "Lacquerware studios" },
  { slug: "batik", zh: "蜡染工坊", en: "Batik studios" },
  { slug: "horology", zh: "独立制表工作室", en: "Watchmaking ateliers" },
  { slug: "saddlery", zh: "马具工坊", en: "Saddlery workshops" },
  { slug: "ikebana", zh: "花道教室", en: "Ikebana schools" },
  { slug: "fanmaking", zh: "制扇工坊", en: "Fan-making studios" },
  { slug: "bambooweaving", zh: "竹编工坊", en: "Bamboo weaving studios" },
  { slug: "swordsmith", zh: "刀剑锻造工坊", en: "Swordsmith forges" },
  { slug: "shadowpuppet", zh: "皮影工作室", en: "Shadow puppet studios" },
  { slug: "guqin", zh: "斫琴工坊", en: "Guqin workshops" },
  { slug: "brocade", zh: "织锦工坊", en: "Brocade weaving studios" },
  { slug: "jadecarving", zh: "玉雕工作室", en: "Jade carving studios" },
  { slug: "claysculpture", zh: "泥塑工作室", en: "Clay sculpture studios" },
  { slug: "sugarpainting", zh: "糖画工作室", en: "Sugar painting studios" },
  { slug: "velvetflower", zh: "绒花工坊", en: "Velvet flower studios" },
  { slug: "oilpaperumbrella", zh: "油纸伞工坊", en: "Oil-paper umbrella workshops" },
  { slug: "bronzecasting", zh: "铸铜工坊", en: "Bronze casting studios" },
  { slug: "pyrography", zh: "烙画工作室", en: "Pyrography studios" },
];
