/**
 * 首页行业模板 chips 的轻量清单（slug + 双语短标签）。
 * 模板全文在 home-template-texts.ts，仅在点击 chip / ?tpl= 预填时动态加载，
 * 不进首屏主 bundle（全文文案约 200KB 源码，曾占主 bundle 三分之一）。
 */
export interface TemplateLabel {
  slug: string;
  labelZh: string;
  labelEn: string;
}

export const TEMPLATE_LABELS: TemplateLabel[] = [
  { slug: "saas", labelZh: "SaaS 工具", labelEn: "SaaS tool" },
  { slug: "ecommerce", labelZh: "电商品牌", labelEn: "E-commerce brand" },
  { slug: "ai", labelZh: "AI 产品", labelEn: "AI product" },
  { slug: "blog", labelZh: "个人博客", labelEn: "Personal blog" },
  { slug: "pets", labelZh: "宠物", labelEn: "Pets" },
  { slug: "fintech", labelZh: "金融科技", labelEn: "Fintech" },
  { slug: "game", labelZh: "游戏", labelEn: "Games" },
  { slug: "edu", labelZh: "教育学习", labelEn: "Education" },
  { slug: "travel", labelZh: "旅行", labelEn: "Travel" },
  { slug: "food", labelZh: "餐饮美食", labelEn: "Food & dining" },
  { slug: "fitness", labelZh: "健身健康", labelEn: "Fitness" },
  { slug: "devtools", labelZh: "开发者工具", labelEn: "Dev tools" },
  { slug: "web3", labelZh: "Web3 项目", labelEn: "Web3 project" },
  { slug: "agency", labelZh: "咨询工作室", labelEn: "Agency / studio" },
  { slug: "photography", labelZh: "摄影工作室", labelEn: "Photo studio" },
  { slug: "podcast", labelZh: "播客节目", labelEn: "Podcast" },
  { slug: "realestate", labelZh: "房产家居", labelEn: "Real estate" },
  { slug: "health", labelZh: "医疗健康", labelEn: "Health app" },
  { slug: "legal", labelZh: "法律服务", labelEn: "Legal service" },
  { slug: "newsletter", labelZh: "Newsletter", labelEn: "Newsletter" },
  { slug: "music", labelZh: "音乐人", labelEn: "Music & labels" },
  { slug: "beauty", labelZh: "美妆个护", labelEn: "Beauty brand" },
  { slug: "nonprofit", labelZh: "公益组织", labelEn: "Nonprofit" },
  { slug: "parenting", labelZh: "母婴亲子", labelEn: "Baby & parenting" },
  { slug: "hardware", labelZh: "智能硬件", labelEn: "Hardware" },
  { slug: "security", labelZh: "网络安全", labelEn: "Cybersecurity" },
  { slug: "creator", labelZh: "视频创作者", labelEn: "Creator" },
  { slug: "freelance", labelZh: "自由职业", labelEn: "Freelance" },
  { slug: "fashion", labelZh: "服饰潮牌", labelEn: "Fashion label" },
  { slug: "coffee", labelZh: "咖啡茶饮", labelEn: "Coffee & tea" },
  { slug: "automotive", labelZh: "汽车出行", labelEn: "Automotive" },
  { slug: "community", labelZh: "社区俱乐部", labelEn: "Community" },
  { slug: "wedding", labelZh: "婚庆策划", labelEn: "Wedding planning" },
  { slug: "bnb", labelZh: "民宿短租", labelEn: "BnB & stays" },
  { slug: "courses", labelZh: "在线课程", labelEn: "Online courses" },
  { slug: "boardgame", labelZh: "桌游工作室", labelEn: "Board games" },
  { slug: "outdoor", labelZh: "户外露营", labelEn: "Outdoor & camping" },
  { slug: "cleaning", labelZh: "家政清洁", labelEn: "Cleaning services" },
  { slug: "marketing", labelZh: "数字营销", labelEn: "Digital marketing" },
  { slug: "therapy", labelZh: "心理咨询", labelEn: "Therapy & mental health" },
  { slug: "resale", labelZh: "二手循环", labelEn: "Resale & recommerce" },
  { slug: "recruiting", labelZh: "招聘人力", labelEn: "Recruiting & HR" },
  { slug: "eldercare", labelZh: "养老服务", labelEn: "Senior care" },
  { slug: "logistics", labelZh: "物流货运", labelEn: "Logistics & freight" },
  { slug: "agent", labelZh: "AI 智能体", labelEn: "AI agents" },
  { slug: "crossborder", labelZh: "跨境电商", labelEn: "Cross-border e-commerce" },
  { slug: "escaperoom", labelZh: "剧本杀密室", labelEn: "Escape rooms" },
  { slug: "bakery", labelZh: "烘焙甜品", labelEn: "Bakeries & desserts" },
  { slug: "bookstore", labelZh: "书店出版", labelEn: "Bookstores & publishing" },
  { slug: "florist", labelZh: "花店花艺", labelEn: "Florists" },
  { slug: "interior", labelZh: "装修设计", labelEn: "Interior & renovation" },
  { slug: "studyabroad", labelZh: "留学教育", labelEn: "Study abroad" },
  { slug: "usedcar", labelZh: "二手车", labelEn: "Used cars" },
  { slug: "insurance", labelZh: "保险经纪", labelEn: "Insurance" },
  { slug: "farm", labelZh: "农场生鲜", labelEn: "Farms & fresh food" },
  { slug: "barber", labelZh: "美发理容", labelEn: "Barbershops & salons" },
  { slug: "yoga", labelZh: "瑜伽普拉提", labelEn: "Yoga & Pilates" },
  { slug: "vet", labelZh: "宠物医院", labelEn: "Vet clinics" },
  { slug: "esports", labelZh: "电竞战队", labelEn: "Esports team" },
  { slug: "drone", labelZh: "无人机航拍", labelEn: "Drone & aerial" },
  { slug: "hanfu", labelZh: "汉服国潮", labelEn: "Hanfu & guochao" },
  { slug: "dental", labelZh: "口腔诊所", labelEn: "Dental clinic" },
  { slug: "accounting", labelZh: "会计财税", labelEn: "Accounting & tax" },
  { slug: "livestream", labelZh: "直播电商", labelEn: "Livestream commerce" },
  { slug: "translation", labelZh: "翻译本地化", labelEn: "Translation & localization" },
  { slug: "gardening", labelZh: "园艺绿植", labelEn: "Gardening & plants" },
  { slug: "coworking", labelZh: "联合办公", labelEn: "Coworking space" },
  { slug: "solar", labelZh: "光伏新能源", labelEn: "Solar & clean energy" },
  { slug: "coach", labelZh: "健身私教", labelEn: "Personal training" },
  { slug: "codingschool", labelZh: "编程培训", labelEn: "Coding bootcamp" },
  { slug: "jewelry", labelZh: "珠宝首饰", labelEn: "Jewelry" },
  { slug: "toys", labelZh: "玩具品牌", labelEn: "Toy brand" },
  { slug: "brewery", labelZh: "精酿酒饮", labelEn: "Craft beer & drinks" },
  { slug: "furniture", labelZh: "家具品牌", labelEn: "Furniture" },
  { slug: "crossfit", labelZh: "CrossFit 综合体能", labelEn: "CrossFit & functional fitness" },
  { slug: "language", labelZh: "语言学习", labelEn: "Language learning" },
  { slug: "resume", labelZh: "简历求职", labelEn: "Resume & job search" },
  { slug: "events", labelZh: "活动策划", labelEn: "Event planning" },
  { slug: "moving", labelZh: "搬家服务", labelEn: "Moving services" },
  { slug: "aquarium", labelZh: "水族爬宠", labelEn: "Aquariums & reptiles" },
  { slug: "indiehacker", labelZh: "独立开发者", labelEn: "Indie hacker" },
  { slug: "petsupplies", labelZh: "宠物用品电商", labelEn: "Pet supplies store" },
  { slug: "preschool", labelZh: "儿童早教", labelEn: "Early education" },
  { slug: "travelshoot", labelZh: "旅拍摄影", labelEn: "Travel photography" },
  { slug: "forwarder", labelZh: "跨境物流", labelEn: "Cross-border logistics" },
  { slug: "mcn", labelZh: "短视频 MCN", labelEn: "Short-video MCN" },
  { slug: "opensource", labelZh: "开源项目", labelEn: "Open source" },
  { slug: "indiegame", labelZh: "独立游戏", labelEn: "Indie games" },
  { slug: "gearrental", labelZh: "影棚器材租赁", labelEn: "Gear & studio rentals" },
  { slug: "sourcing", labelZh: "电商选品", labelEn: "Product sourcing" },
  { slug: "fleamarket", labelZh: "线下市集", labelEn: "Markets & pop-ups" },
  { slug: "ski", labelZh: "滑雪户外", labelEn: "Ski & snow" },
  { slug: "aiart", labelZh: "AI 绘画", labelEn: "AI art tool" },
  { slug: "campsite", labelZh: "露营地", labelEn: "Campground" },
  { slug: "tcm", labelZh: "中医养生", labelEn: "TCM wellness" },
  { slug: "deskcraft", labelZh: "桌面文创", labelEn: "Desk & stationery" },
  { slug: "petmemorial", labelZh: "宠物殡葬", labelEn: "Pet memorial" },
  { slug: "postpartum", labelZh: "月子中心", labelEn: "Postpartum care" },
  { slug: "pettraining", labelZh: "宠物训练", labelEn: "Pet training" },
  { slug: "nailsalon", labelZh: "美甲美睫", labelEn: "Nail & lash studios" },
  { slug: "laundry", labelZh: "洗衣洗护", labelEn: "Laundry & garment care" },
  { slug: "rvtravel", labelZh: "房车旅行", labelEn: "RV travel" },
  { slug: "knowledgepay", labelZh: "知识付费", labelEn: "Paid knowledge" },
  { slug: "matchmaking", labelZh: "婚恋相亲", labelEn: "Matchmaking & dating" },
  { slug: "tattoo", labelZh: "纹身工作室", labelEn: "Tattoo studios" },
  { slug: "climbing", labelZh: "攀岩馆", labelEn: "Climbing gyms" },
  { slug: "swimschool", labelZh: "游泳培训", labelEn: "Swim schools" },
  { slug: "3dprint", labelZh: "3D 打印", labelEn: "3D printing" },
  { slug: "vending", labelZh: "无人零售", labelEn: "Vending & unattended retail" },
  { slug: "kidsart", labelZh: "少儿美术", labelEn: "Kids' art schools" },
  { slug: "danceschool", labelZh: "舞蹈工作室", labelEn: "Dance studios" },
  { slug: "martialarts", labelZh: "武术格斗馆", labelEn: "Martial arts gyms" },
  { slug: "bikeshop", labelZh: "骑行单车", labelEn: "Bike shops & cycling" },
  { slug: "fishing", labelZh: "垂钓渔具", labelEn: "Fishing & tackle" },
  { slug: "foodtruck", labelZh: "餐车小吃", labelEn: "Food trucks & street food" },
  { slug: "repair", labelZh: "维修服务", labelEn: "Repair & handyman services" },
  { slug: "pottery", labelZh: "陶艺手作", labelEn: "Pottery & ceramics" },
  { slug: "billiards", labelZh: "台球桌球馆", labelEn: "Billiards & pool halls" },
  { slug: "drivingschool", labelZh: "驾校驾培", labelEn: "Driving schools" },
  { slug: "optician", labelZh: "眼镜视光", labelEn: "Opticians & eyewear" },
  { slug: "massage", labelZh: "按摩推拿", labelEn: "Massage & bodywork" },
  { slug: "mealprep", labelZh: "轻食健康餐", labelEn: "Meal prep & healthy eats" },
  { slug: "petphoto", labelZh: "宠物摄影", labelEn: "Pet photography" },
  { slug: "campgear", labelZh: "露营装备", labelEn: "Camping gear" },
  { slug: "careercoach", labelZh: "职业规划咨询", labelEn: "Career coaching" },
  { slug: "fragrance", labelZh: "香氛蜡烛", labelEn: "Home fragrance & candles" },
  { slug: "diving", labelZh: "潜水俱乐部", labelEn: "Diving & scuba" },
  { slug: "carwash", labelZh: "汽车美容洗车", labelEn: "Car wash & detailing" },
  { slug: "studytour", labelZh: "研学营地", labelEn: "Study camps & tours" },
  { slug: "petboarding", labelZh: "宠物寄养", labelEn: "Pet boarding" },
  { slug: "upcycling", labelZh: "旧物改造", labelEn: "Upcycling & rework" },
  { slug: "zine", labelZh: "独立杂志", labelEn: "Indie magazines & zines" },
  { slug: "locksmith", labelZh: "开锁换锁", labelEn: "Locksmiths" },
  { slug: "skateshop", labelZh: "滑板店", labelEn: "Skate shops" },
  { slug: "surf", labelZh: "冲浪俱乐部", labelEn: "Surf clubs" },
  { slug: "golf", labelZh: "高尔夫", labelEn: "Golf" },
  { slug: "vr", labelZh: "VR 体验馆", labelEn: "VR arcades" },
  { slug: "bar", labelZh: "酒吧清吧", labelEn: "Bars & lounges" },
  { slug: "musicschool", labelZh: "音乐培训琴行", labelEn: "Music schools" },
  { slug: "chess", labelZh: "棋类培训", labelEn: "Chess & Go academies" },
  { slug: "hotpot", labelZh: "火锅烧烤", labelEn: "Hotpot & BBQ" },
  { slug: "dessert", labelZh: "甜品冰淇淋", labelEn: "Dessert & ice cream" },
  { slug: "convenience", labelZh: "社区便利店", labelEn: "Convenience stores" },
  { slug: "stationery", labelZh: "文创文具", labelEn: "Stationery & paper goods" },
  { slug: "cybercafe", labelZh: "电竞网咖", labelEn: "Esports cafés" },
  { slug: "carrental", labelZh: "租车出行", labelEn: "Car rental & mobility" },
  { slug: "noodle", labelZh: "粉面小吃", labelEn: "Noodle shops" },
  { slug: "grocery", labelZh: "社区生鲜", labelEn: "Fresh groceries" },
  { slug: "tutoring", labelZh: "课外辅导", labelEn: "Tutoring & test prep" },
  { slug: "printshop", labelZh: "图文快印", labelEn: "Print shops" },
  { slug: "errand", labelZh: "同城跑腿", labelEn: "Errand & courier services" },
  { slug: "plumber", labelZh: "管道疏通维修", labelEn: "Plumbing & repair" },
  { slug: "travelagency", labelZh: "旅行社", labelEn: "Travel agencies" },
  { slug: "teahouse", labelZh: "茶馆茶室", labelEn: "Tea houses & tea brands" },
  { slug: "petcafe", labelZh: "宠物咖啡", labelEn: "Pet cafés" },
  { slug: "weddingphoto", labelZh: "婚纱摄影", labelEn: "Wedding photography" },
  { slug: "footspa", labelZh: "足疗采耳", labelEn: "Foot spas & wellness lounges" },
  { slug: "parcel", labelZh: "快递驿站", labelEn: "Parcel stations & pickup points" },
  { slug: "realtor", labelZh: "房产中介", labelEn: "Real estate agencies" },
  { slug: "propertymgmt", labelZh: "物业管理", labelEn: "Property management" },
  { slug: "apartment", labelZh: "长租公寓", labelEn: "Apartment rentals" },
  { slug: "construction", labelZh: "建筑施工", labelEn: "Construction & contracting" },
  { slug: "appliancerepair", labelZh: "家电维修", labelEn: "Appliance repair" },
  { slug: "equipmentrental", labelZh: "设备租赁", labelEn: "Equipment rental" },
  { slug: "hotel", labelZh: "酒店旅宿", labelEn: "Hotels & lodging" },
  { slug: "karaoke", labelZh: "量贩KTV", labelEn: "Karaoke lounges" },
  { slug: "bubbletea", labelZh: "奶茶茶饮", labelEn: "Bubble tea shops" },
  { slug: "bbq", labelZh: "烧烤夜宵", labelEn: "BBQ & late-night grills" },
  { slug: "pharmacy", labelZh: "连锁药店", labelEn: "Pharmacies" },
  { slug: "clinic", labelZh: "诊所门诊", labelEn: "Clinics & outpatient care" },
  { slug: "evcharging", labelZh: "充电桩运营", labelEn: "EV charging" },
  { slug: "energystorage", labelZh: "储能系统", labelEn: "Energy storage" },
  { slug: "recycling", labelZh: "再生资源回收", labelEn: "Recycling & recovery" },
  { slug: "retrofit", labelZh: "节能改造", labelEn: "Energy retrofit" },
  { slug: "hvac", labelZh: "暖通空调", labelEn: "HVAC services" },
  { slug: "watertreatment", labelZh: "水处理环保", labelEn: "Water treatment" },
  { slug: "babystore", labelZh: "母婴用品", labelEn: "Baby & maternity" },
  { slug: "kidsphoto", labelZh: "儿童摄影", labelEn: "Kids' photography" },
  { slug: "giftcustom", labelZh: "礼品定制", labelEn: "Custom gifts" },
  { slug: "petgrooming", labelZh: "宠物美容", labelEn: "Pet grooming" },
  { slug: "housekeeping", labelZh: "家政服务", labelEn: "Housekeeping" },
  { slug: "kidsplayground", labelZh: "亲子乐园", labelEn: "Kids' playgrounds" },
  { slug: "productphoto", labelZh: "电商产品摄影", labelEn: "Product photography" },
  { slug: "portrait", labelZh: "个人写真", labelEn: "Portrait studios" },
  { slug: "foodreview", labelZh: "探店测评", labelEn: "Food reviews" },
  { slug: "nutrition", labelZh: "营养师咨询", labelEn: "Nutrition coaching" },
  { slug: "physio", labelZh: "康复理疗", labelEn: "Physiotherapy & rehab" },
  { slug: "runclub", labelZh: "跑步俱乐部", labelEn: "Run clubs" },
  { slug: "tennis", labelZh: "网球俱乐部", labelEn: "Tennis clubs" },
  { slug: "soccer", labelZh: "足球青训", labelEn: "Soccer academies" },
  { slug: "football", labelZh: "腰旗橄榄球", labelEn: "Flag football" },
  { slug: "hockey", labelZh: "冰球俱乐部", labelEn: "Hockey clubs" },
  { slug: "pickleball", labelZh: "匹克球", labelEn: "Pickleball" },
  { slug: "pilates", labelZh: "普拉提馆", labelEn: "Pilates studios" },
  { slug: "companyreg", labelZh: "公司注册代办", labelEn: "Company formation" },
  { slug: "consulting", labelZh: "管理咨询", labelEn: "Consulting firms" },
  { slug: "wholesale", labelZh: "B2B 批发平台", labelEn: "B2B wholesale" },
  { slug: "trading", labelZh: "外贸公司", labelEn: "Import & export" },
  { slug: "coupon", labelZh: "优惠券导购", labelEn: "Coupon & deals" },
  { slug: "flashsale", labelZh: "限时特卖电商", labelEn: "Flash sales" },
  { slug: "pestcontrol", labelZh: "害虫防治", labelEn: "Pest control" },
  { slug: "roofing", labelZh: "屋顶施工", labelEn: "Roofing" },
  { slug: "towing", labelZh: "道路救援", labelEn: "Towing & roadside" },
  { slug: "selfstorage", labelZh: "自助仓储", labelEn: "Self-storage" },
  { slug: "catering", labelZh: "宴会团餐", labelEn: "Catering" },
  { slug: "signage", labelZh: "广告标识", labelEn: "Signage & signs" },
  { slug: "shortvideo", labelZh: "短视频制作", labelEn: "Short-video production" },
  { slug: "audiobook", labelZh: "有声书配音", labelEn: "Audiobooks & voiceover" },
  { slug: "postproduction", labelZh: "影视后期", labelEn: "Post-production & VFX" },
  { slug: "animation", labelZh: "动画工作室", labelEn: "Animation studios" },
  { slug: "documentary", labelZh: "纪录片工作室", labelEn: "Documentary studios" },
  { slug: "newsmedia", labelZh: "独立新闻媒体", labelEn: "Independent news media" },
  { slug: "fruitshop", labelZh: "水果店", labelEn: "Fruit shops" },
  { slug: "seafood", labelZh: "海鲜餐厅", labelEn: "Seafood restaurants" },
  { slug: "tailor", labelZh: "服装定制", labelEn: "Custom tailoring" },
  { slug: "equestrian", labelZh: "马术俱乐部", labelEn: "Equestrian clubs" },
  { slug: "archery", labelZh: "射箭馆", labelEn: "Archery ranges" },
  { slug: "immigration", labelZh: "移民咨询", labelEn: "Immigration consulting" },
  { slug: "deli", labelZh: "卤味熟食", labelEn: "Deli & braised food" },
  { slug: "winery", labelZh: "精品酒庄", labelEn: "Boutique winery" },
  { slug: "sushi", labelZh: "日料餐厅", labelEn: "Sushi restaurant" },
  { slug: "icecream", labelZh: "冰淇淋品牌", labelEn: "Ice cream brand" },
  { slug: "hostel", labelZh: "青年旅舍", labelEn: "Hostel" },
  { slug: "bowling", labelZh: "保龄球馆", labelEn: "Bowling alley" },
  { slug: "tea", labelZh: "茶叶品牌", labelEn: "Tea brand" },
  { slug: "hotspring", labelZh: "温泉度假", labelEn: "Hot spring resort" },
  { slug: "trampoline", labelZh: "蹦床公园", labelEn: "Trampoline park" },
  { slug: "funeral", labelZh: "殡葬服务", labelEn: "Funeral services" },
  { slug: "securityguard", labelZh: "安保服务", labelEn: "Security services" },
  { slug: "ipagency", labelZh: "知识产权代理", labelEn: "IP & patent services" },
  { slug: "wig", labelZh: "假发品牌", labelEn: "Wig brand" },
  { slug: "skincare", labelZh: "护肤品牌", labelEn: "Skincare brand" },
  { slug: "makeupartist", labelZh: "化妆造型工作室", labelEn: "Makeup artist studio" },
  { slug: "homestaging", labelZh: "房屋整备布置", labelEn: "Home staging" },
  { slug: "yachtcharter", labelZh: "游艇租赁俱乐部", labelEn: "Yacht charter" },
  { slug: "autoparts", labelZh: "汽配用品品牌", labelEn: "Auto parts brand" },
  { slug: "robotics", labelZh: "机器人公司", labelEn: "Robotics company" },
  { slug: "nocode", labelZh: "无代码工具", labelEn: "No-code tool" },
  { slug: "badminton", labelZh: "羽毛球馆", labelEn: "Badminton club" },
  { slug: "gokart", labelZh: "卡丁车馆", labelEn: "Go-kart venue" },
  { slug: "sauna", labelZh: "汗蒸桑拿馆", labelEn: "Sauna studio" },
  { slug: "pizza", labelZh: "披萨店", labelEn: "Pizza shop" },
  { slug: "electrician", labelZh: "电工电气服务", labelEn: "Electrical services" },
  { slug: "landscaping", labelZh: "园林景观", labelEn: "Landscaping company" },
  { slug: "painting", labelZh: "油漆粉刷", labelEn: "Painting company" },
  { slug: "jobboard", labelZh: "招聘求职平台", labelEn: "Job board" },
  { slug: "restaurantsupply", labelZh: "餐饮设备供应", labelEn: "Restaurant supply" },
  { slug: "motorcycleparts", labelZh: "摩托车配件", labelEn: "Motorcycle parts" },
  { slug: "auction", labelZh: "拍卖行", labelEn: "Auction house" },
  { slug: "antiques", labelZh: "古董古玩店", labelEn: "Antique shop" },
  { slug: "lightingbrand", labelZh: "灯具照明品牌", labelEn: "Lighting brand" },
  { slug: "outlet", labelZh: "折扣特卖店", labelEn: "Outlet store" },
  { slug: "watches", labelZh: "腕表钟表店", labelEn: "Watch brand" },
  { slug: "sneakers", labelZh: "球鞋潮鞋店", labelEn: "Sneaker shop" },
  { slug: "dollarstore", labelZh: "一元折扣店", labelEn: "Dollar store" },
  { slug: "thriftstore", labelZh: "二手循环店", labelEn: "Thrift store" },
  { slug: "officesupplies", labelZh: "办公用品", labelEn: "Office supplies" },
  { slug: "medicalsupplies", labelZh: "医疗用品", labelEn: "Medical supplies" },
  { slug: "buildingmaterials", labelZh: "建材五金", labelEn: "Building materials" },
  { slug: "franchise", labelZh: "连锁加盟", labelEn: "Franchise brand" },
  { slug: "villarental", labelZh: "民宿别墅短租", labelEn: "Villa rental" },
  { slug: "cruise", labelZh: "邮轮旅行社", labelEn: "Cruise agency" },
  { slug: "customtour", labelZh: "定制旅行", labelEn: "Bespoke travel" },
  { slug: "limoservice", labelZh: "豪车接送", labelEn: "Limo service" },
  { slug: "ticketing", labelZh: "票务平台", labelEn: "Ticketing platform" },
  { slug: "flowerdelivery", labelZh: "鲜花电商", labelEn: "Flower delivery" },
  { slug: "taproom", labelZh: "精酿酒馆", labelEn: "Taproom" },
  { slug: "izakaya", labelZh: "居酒屋", labelEn: "Izakaya" },
  { slug: "dayspa", labelZh: "水疗会所", labelEn: "Day spa" },
  { slug: "snacks", labelZh: "零食品牌", labelEn: "Snack brand" },
  { slug: "lawfirm", labelZh: "律师事务所", labelEn: "Law firm" },
  { slug: "orthodontics", labelZh: "正畸齿科", labelEn: "Orthodontics" },
  { slug: "kidswear", labelZh: "童装品牌", labelEn: "Kidswear brand" },
  { slug: "cookingclass", labelZh: "烹饪教室", labelEn: "Cooking class" },
  { slug: "souvenir", labelZh: "伴手礼品牌", labelEn: "Souvenir brand" },
  { slug: "partyplanner", labelZh: "派对策划", labelEn: "Party planner" },
  { slug: "seafishing", labelZh: "海钓包船", labelEn: "Sea fishing charter" },
  { slug: "horseranch", labelZh: "马场骑乘", labelEn: "Horse ranch" },
  { slug: "datingapp", labelZh: "交友App", labelEn: "Dating app" },
  { slug: "singlesevents", labelZh: "单身社交活动", labelEn: "Singles events" },
  { slug: "luxuryresale", labelZh: "中古奢侈品", labelEn: "Luxury resale" },
  { slug: "organicfood", labelZh: "有机食品电商", labelEn: "Organic food store" },
  { slug: "permanentmakeup", labelZh: "半永久纹绣", labelEn: "Permanent makeup studio" },
  { slug: "homedecor", labelZh: "家居饰品", labelEn: "Home decor brand" },
  { slug: "craftvodka", labelZh: "精酿伏特加", labelEn: "Craft vodka" },
  { slug: "esportsnews", labelZh: "棋牌电竞资讯", labelEn: "Esports & gaming news" },
  { slug: "sportsodds", labelZh: "体育竞猜资讯", labelEn: "Sports odds & analysis" },
  { slug: "tabletopclub", labelZh: "桌游俱乐部", labelEn: "Tabletop club" },
  { slug: "futsal", labelZh: "五人制足球场馆", labelEn: "Futsal venue" },
  { slug: "fashionbuyer", labelZh: "快时尚买手店", labelEn: "Fashion select shop" },
  { slug: "basketball", labelZh: "篮球培训", labelEn: "Basketball training" },
  { slug: "rugby", labelZh: "橄榄球俱乐部", labelEn: "Rugby club" },
  { slug: "cricket", labelZh: "板球社区", labelEn: "Cricket community" },
  { slug: "aquascaping", labelZh: "观赏鱼造景", labelEn: "Aquascaping studio" },
  { slug: "fanclub", labelZh: "粉丝应援站", labelEn: "Fan club" },
  { slug: "giveaway", labelZh: "抽奖活动平台", labelEn: "Giveaway platform" },
  { slug: "volleyball", labelZh: "排球俱乐部", labelEn: "Volleyball club" },
  { slug: "tabletennis", labelZh: "乒乓球俱乐部", labelEn: "Table tennis club" },
  { slug: "baseball", labelZh: "棒球培训", labelEn: "Baseball training" },
  { slug: "boxing", labelZh: "拳击馆", labelEn: "Boxing gym" },
  { slug: "taekwondo", labelZh: "跆拳道馆", labelEn: "Taekwondo school" },
  { slug: "fencing", labelZh: "击剑俱乐部", labelEn: "Fencing club" },
  { slug: "gymnastics", labelZh: "体操培训", labelEn: "Gymnastics academy" },
  { slug: "cheerleading", labelZh: "啦啦操", labelEn: "Cheerleading gym" },
  { slug: "squash", labelZh: "壁球馆", labelEn: "Squash club" },
  { slug: "lacrosse", labelZh: "长曲棍球", labelEn: "Lacrosse club" },
  { slug: "judo", labelZh: "柔道馆", labelEn: "Judo dojo" },
  { slug: "bjj", labelZh: "巴西柔术", labelEn: "BJJ academy" },
  { slug: "wrestling", labelZh: "摔跤馆", labelEn: "Wrestling club" },
  { slug: "muaythai", labelZh: "泰拳馆", labelEn: "Muay Thai gym" },
  { slug: "handball", labelZh: "手球俱乐部", labelEn: "Handball club" },
  { slug: "curling", labelZh: "冰壶俱乐部", labelEn: "Curling club" },
  { slug: "rowing", labelZh: "赛艇俱乐部", labelEn: "Rowing club" },
  { slug: "skating", labelZh: "轮滑滑冰", labelEn: "Skating club" },
  { slug: "candle", labelZh: "香薰蜡烛", labelEn: "Candle brand" },
  { slug: "juicebar", labelZh: "果汁轻食吧", labelEn: "Juice bar" },
  { slug: "leathercraft", labelZh: "皮具工作室", labelEn: "Leather workshop" },
  { slug: "calligraphy", labelZh: "书法工作室", labelEn: "Calligraphy studio" },
  { slug: "instrumentstore", labelZh: "乐器行", labelEn: "Instrument store" },
  { slug: "meditation", labelZh: "冥想馆", labelEn: "Meditation studio" },
  { slug: "woodworking", labelZh: "木工工作室", labelEn: "Woodworking studio" },
  { slug: "soapmaking", labelZh: "手工皂", labelEn: "Soap brand" },
  { slug: "modelkit", labelZh: "模型手办店", labelEn: "Model kit store" },
  { slug: "framing", labelZh: "装裱画框店", labelEn: "Framing shop" },
  { slug: "recordingstudio", labelZh: "录音棚", labelEn: "Recording studio" },
  { slug: "hearingaid", labelZh: "助听器验配", labelEn: "Hearing aid center" },
  { slug: "watchrepair", labelZh: "钟表维修", labelEn: "Watch repair" },
  { slug: "beekeeping", labelZh: "蜂蜜品牌", labelEn: "Honey brand" },
  { slug: "glassblowing", labelZh: "玻璃工作室", labelEn: "Glass studio" },
  { slug: "bonsai", labelZh: "盆景园", labelEn: "Bonsai studio" },
  { slug: "recordstore", labelZh: "黑胶唱片店", labelEn: "Record store" },
  { slug: "embroidery", labelZh: "刺绣工作室", labelEn: "Embroidery studio" },
  { slug: "sealcarving", labelZh: "篆刻工作室", labelEn: "Seal carving studio" },
  { slug: "incense", labelZh: "香道工作室", labelEn: "Incense studio" },
  { slug: "papercut", labelZh: "剪纸工作室", labelEn: "Papercut studio" },
  { slug: "lantern", labelZh: "灯笼工坊", labelEn: "Lantern workshop" },
  { slug: "quilting", labelZh: "拼布工作室", labelEn: "Quilting studio" },
  { slug: "teaware", labelZh: "茶器工作室", labelEn: "Teaware studio" },
  { slug: "kite", labelZh: "风筝工坊", labelEn: "Kite workshop" },
  { slug: "succulent", labelZh: "多肉植物店", labelEn: "Succulent shop" },
  { slug: "chocolate", labelZh: "手工巧克力", labelEn: "Craft chocolate" },
  { slug: "weaving", labelZh: "织造工作室", labelEn: "Weaving studio" },
  { slug: "puppet", labelZh: "木偶皮影工作室", labelEn: "Puppetry studio" },
  { slug: "birding", labelZh: "观鸟俱乐部", labelEn: "Birding club" },
  { slug: "stargazing", labelZh: "观星俱乐部", labelEn: "Stargazing club" },
  { slug: "cidery", labelZh: "苹果酒坊", labelEn: "Craft cidery" },
  { slug: "bookbinding", labelZh: "手工装帧工作室", labelEn: "Bookbinding studio" },
  { slug: "letterpress", labelZh: "活版印刷工作室", labelEn: "Letterpress studio" },
  { slug: "terrarium", labelZh: "生态瓶工作室", labelEn: "Terrarium studio" },
  { slug: "axethrowing", labelZh: "飞斧馆", labelEn: "Axe-throwing venue" },
  { slug: "lasertag", labelZh: "镭射对战馆", labelEn: "Laser tag arena" },
  { slug: "paintball", labelZh: "彩弹射击场", labelEn: "Paintball field" },
  { slug: "mushroomfarm", labelZh: "菌菇农场", labelEn: "Mushroom farm" },
  { slug: "neonsign", labelZh: "霓虹灯工作室", labelEn: "Neon sign studio" },
  { slug: "millinery", labelZh: "制帽工作室", labelEn: "Millinery studio" },
  { slug: "mosaic", labelZh: "马赛克工作室", labelEn: "Mosaic studio" },
  { slug: "blacksmith", labelZh: "铁匠铺", labelEn: "Blacksmith forge" },
  { slug: "distillery", labelZh: "精酿蒸馏厂", labelEn: "Craft distillery" },
  { slug: "kombucha", labelZh: "康普茶品牌", labelEn: "Kombucha brand" },
  { slug: "climbinggym", labelZh: "攀岩馆", labelEn: "Climbing gym" },
  { slug: "stainedglass", labelZh: "彩绘玻璃工作室", labelEn: "Stained glass studio" },
  { slug: "minigolf", labelZh: "迷你高尔夫球场", labelEn: "Mini golf course" },
  { slug: "taxidermy", labelZh: "标本工作室", labelEn: "Taxidermy studio" },
  { slug: "cheesemaking", labelZh: "奶酪工坊", labelEn: "Cheesemaking studio" },
  { slug: "meadery", labelZh: "蜂蜜酒厂", labelEn: "Meadery" },
  { slug: "tufting", labelZh: "簇绒工作室", labelEn: "Tufting studio" },
  { slug: "silversmith", labelZh: "银匠工作室", labelEn: "Silversmith studio" },
  { slug: "falconry", labelZh: "猛禽体验基地", labelEn: "Falconry experience" },
  { slug: "lutherie", labelZh: "制琴工作室", labelEn: "Lutherie studio" },
  { slug: "lapidary", labelZh: "宝石切磨工作室", labelEn: "Lapidary studio" },
  { slug: "cooperage", labelZh: "制桶工坊", labelEn: "Cooperage" },
  { slug: "kintsugi", labelZh: "金缮修复工作室", labelEn: "Kintsugi studio" },
  { slug: "indigodye", labelZh: "蓝染工坊", labelEn: "Indigo dye studio" },
  { slug: "penmaking", labelZh: "手工制笔工作室", labelEn: "Penmaking studio" },
  { slug: "marquetry", labelZh: "细木镶嵌工作室", labelEn: "Marquetry studio" },
  { slug: "cloisonne", labelZh: "掐丝珐琅工作室", labelEn: "Cloisonné studio" },
  { slug: "papermaking", labelZh: "手工造纸工坊", labelEn: "Papermaking studio" },
  { slug: "inkstone", labelZh: "制砚工坊", labelEn: "Inkstone studio" },
  { slug: "fletching", labelZh: "制箭工坊", labelEn: "Fletching workshop" },
  { slug: "gilding", labelZh: "贴金工坊", labelEn: "Gilding studio" },
  { slug: "lacquerware", labelZh: "漆艺工坊", labelEn: "Lacquerware studio" },
  { slug: "batik", labelZh: "蜡染工坊", labelEn: "Batik studio" },
  { slug: "horology", labelZh: "独立制表工作室", labelEn: "Watchmaking atelier" },
  { slug: "saddlery", labelZh: "马具工坊", labelEn: "Saddlery workshop" },
  { slug: "ikebana", labelZh: "花道教室", labelEn: "Ikebana school" },
  { slug: "fanmaking", labelZh: "制扇工坊", labelEn: "Fan-making studio" },
  { slug: "bambooweaving", labelZh: "竹编工坊", labelEn: "Bamboo weaving studio" },
  { slug: "swordsmith", labelZh: "刀剑锻造工坊", labelEn: "Swordsmith forge" },
  { slug: "shadowpuppet", labelZh: "皮影工作室", labelEn: "Shadow puppet studio" },
  { slug: "guqin", labelZh: "斫琴工坊", labelEn: "Guqin workshop" },
  { slug: "brocade", labelZh: "织锦工坊", labelEn: "Brocade weaving studio" },
  { slug: "jadecarving", labelZh: "玉雕工作室", labelEn: "Jade carving studio" },
  { slug: "claysculpture", labelZh: "泥塑工作室", labelEn: "Clay sculpture studio" },
  { slug: "sugarpainting", labelZh: "糖画工作室", labelEn: "Sugar painting studio" },
  { slug: "velvetflower", labelZh: "绒花工坊", labelEn: "Velvet flower studio" },
  { slug: "oilpaperumbrella", labelZh: "油纸伞工坊", labelEn: "Oil-paper umbrella workshop" },
  { slug: "bronzecasting", labelZh: "铸铜工坊", labelEn: "Bronze casting studio" },
  { slug: "pyrography", labelZh: "烙画工作室", labelEn: "Pyrography studio" },
];
