/**
 * hub 索引页轻量数据 —— 由 scripts/gen-hub-index.mjs 从
 * tlds.ts / guides.ts / compares.ts 全文内容生成，请勿手改。
 * 内容源变更（新增/修改 TLD、行业指南、对比页）后运行 node scripts/gen-hub-index.mjs 重新生成；
 * CI/审计可用 --check 校验一致性。
 * 存在意义：hub 页组件只需一句话定位/标签/标题，引用本模块而非全文 chunk（R271 移动性能优化）；
 * 按 hub 分立三个文件，每个 hub 页只加载自己那份索引（R282 移动性能优化）。
 */
type Localized = { zh: string; en: string };

/** 对比页索引（顺序与 COMPARE_LIST 一致）：slug + 左右 TLD + 双语标题 */
export const COMPARE_INDEX: { slug: string; a: string; b: string; title: Localized }[] = [
  { slug: "com-vs-cn", a: "com", b: "cn", title: { zh: ".com 和 .cn 怎么选：面向人群、备案与品牌保护对比", en: ".com vs .cn: Audience, Compliance & Brand Protection Compared" } },
  { slug: "com-vs-io", a: "com", b: "io", title: { zh: ".com 和 .io 怎么选：信任感与极客感的取舍", en: ".com vs .io: Trust vs Hacker Credibility" } },
  { slug: "com-vs-net", a: "com", b: "net", title: { zh: ".com 和 .net 怎么选：主选与备选的正确用法", en: ".com vs .net: Using the Fallback Right" } },
  { slug: "io-vs-ai", a: "io", b: "ai", title: { zh: ".io 和 .ai 怎么选：开发者身份与 AI 叙事的对比", en: ".io vs .ai: Developer Badge vs AI Narrative" } },
  { slug: "app-vs-dev", a: "app", b: "dev", title: { zh: ".app 和 .dev 怎么选：面向用户还是面向开发者", en: ".app vs .dev: End Users or Developers" } },
  { slug: "co-vs-me", a: "co", b: "me", title: { zh: ".co 和 .me 怎么选：品牌简写与个人品牌的对比", en: ".co vs .me: Startup Shorthand or Personal Brand" } },
  { slug: "com-vs-ai", a: "com", b: "ai", title: { zh: ".com 和 .ai 怎么选：通用信任与 AI 品类信号的取舍", en: ".com vs .ai: Universal Trust or AI Category Signal" } },
  { slug: "net-vs-org", a: "net", b: "org", title: { zh: ".net 和 .org 怎么选：技术气质与公信力的对比", en: ".net vs .org: Technical Vibe or Public Trust" } },
  { slug: "com-vs-xyz", a: "com", b: "xyz", title: { zh: ".com 和 .xyz 怎么选：默认信任与新锐低价的取舍", en: ".com vs .xyz: Default Trust or Edgy Bargain" } },
  { slug: "io-vs-co", a: "io", b: "co", title: { zh: ".io 和 .co 怎么选：极客身份与创业简写的对比", en: ".io vs .co: Hacker Badge or Startup Shorthand" } },
  { slug: "ai-vs-dev", a: "ai", b: "dev", title: { zh: ".ai 和 .dev 怎么选：品类叙事与工程师信誉的对比", en: ".ai vs .dev: Category Narrative or Engineer Credibility" } },
  { slug: "xyz-vs-top", a: "xyz", b: "top", title: { zh: ".xyz 和 .top 怎么选：两大低价后缀的真实差别", en: ".xyz vs .top: What Really Separates the Two Budget Suffixes" } },
  { slug: "shop-vs-store", a: "shop", b: "store", title: { zh: ".shop 和 .store 怎么选：电商域名双雄对比", en: ".shop vs .store: The Two E-commerce Suffixes Compared" } },
  { slug: "cloud-vs-tech", a: "cloud", b: "tech", title: { zh: ".cloud 和 .tech 怎么选：云服务与泛科技的定位对比", en: ".cloud vs .tech: Precise Cloud Positioning or Broad Tech" } },
  { slug: "pro-vs-co", a: "pro", b: "co", title: { zh: ".pro 和 .co 怎么选：专业人士与创业公司的对比", en: ".pro vs .co: Professional Badge or Startup Shorthand" } },
  { slug: "vip-vs-club", a: "vip", b: "club", title: { zh: ".vip 和 .club 怎么选：会员体系与社群文化的对比", en: ".vip vs .club: Membership Tiers or Community Belonging" } },
  { slug: "link-vs-cc", a: "link", b: "cc", title: { zh: ".link 和 .cc 怎么选：链接工具与万能简写的对比", en: ".link vs .cc: Literal Link Tools or the Versatile Two-Letter" } },
  { slug: "shop-vs-com", a: "shop", b: "com", title: { zh: ".shop 和 .com 怎么选：电商专属与默认信任的取舍", en: ".shop vs .com: E-commerce Native or Default Trust" } },
  { slug: "com-vs-me", a: "com", b: "me", title: { zh: ".com 和 .me 怎么选：品牌资产与个人表达的取舍", en: ".com vs .me: Brand Asset or Personal Expression" } },
  { slug: "io-vs-tech", a: "io", b: "tech", title: { zh: ".io 和 .tech 怎么选：极客身份与直白语义的取舍", en: ".io vs .tech: Hacker Cred or Literal Meaning" } },
  { slug: "online-vs-site", a: "online", b: "site", title: { zh: ".online 和 .site 怎么选：两个通用后缀的实用对比", en: ".online vs .site: A Practical Comparison of Two Generic Suffixes" } },
  { slug: "store-vs-online", a: "store", b: "online", title: { zh: ".store 和 .online 怎么选：卖货语义与通用在线的取舍", en: ".store vs .online: Commerce Semantics or Generic Presence" } },
  { slug: "cc-vs-tv", a: "cc", b: "tv", title: { zh: ".cc 和 .tv 怎么选：两个「转义」国别后缀的对比", en: ".cc vs .tv: Two Repurposed Country Codes Compared" } },
  { slug: "cn-vs-top", a: "cn", b: "top", title: { zh: ".cn 和 .top 怎么选：两个低价后缀的实用对比", en: ".cn vs .top: A Practical Comparison of Two Budget Suffixes" } },
  { slug: "art-vs-design", a: "art", b: "design", title: { zh: ".art 和 .design 怎么选：艺术身份与设计职业的取舍", en: ".art vs .design: Artistic Identity or Professional Craft" } },
  { slug: "studio-vs-design", a: "studio", b: "design", title: { zh: ".studio 和 .design 怎么选：团队形态与职业身份的取舍", en: ".studio vs .design: Team Shape or Professional Label" } },
  { slug: "live-vs-tv", a: "live", b: "tv", title: { zh: ".live 和 .tv 怎么选：直播现场感与视频频道感的取舍", en: ".live vs .tv: Happening Now or Channel Brand" } },
  { slug: "fun-vs-club", a: "fun", b: "club", title: { zh: ".fun 和 .club 怎么选：好玩体验与归属感社群的取舍", en: ".fun vs .club: Playful Experience or Belonging" } },
  { slug: "space-vs-site", a: "space", b: "site", title: { zh: ".space 和 .site 怎么选：个人小天地与通用建站的取舍", en: ".space vs .site: A Place With Character or a Neutral Website" } },
  { slug: "live-vs-online", a: "live", b: "online", title: { zh: ".live 和 .online 怎么选：实时现场感与线上存在感的取舍", en: ".live vs .online: Happening Now or Simply Online" } },
  { slug: "com-vs-app", a: "com", b: "app", title: { zh: ".com 和 .app 怎么选：通用信任与应用属性的取舍", en: ".com vs .app: Universal Trust or Built-in App Semantics" } },
  { slug: "com-vs-dev", a: "com", b: "dev", title: { zh: ".com 和 .dev 怎么选：大众品牌与开发者身份的取舍", en: ".com vs .dev: Mainstream Brand or Developer Identity" } },
  { slug: "io-vs-dev", a: "io", b: "dev", title: { zh: ".io 和 .dev 怎么选：极客老牌与开发者新贵的对比", en: ".io vs .dev: The Veteran Hacker Suffix or the Purpose-Built One" } },
  { slug: "ai-vs-app", a: "ai", b: "app", title: { zh: ".ai 和 .app 怎么选：AI 光环与应用属性的取舍", en: ".ai vs .app: The AI Halo or the App Identity" } },
  { slug: "pro-vs-vip", a: "pro", b: "vip", title: { zh: ".pro 和 .vip 怎么选：专业感与会员感的取舍", en: ".pro vs .vip: Professional Credentials or Member Exclusivity" } },
  { slug: "cloud-vs-online", a: "cloud", b: "online", title: { zh: ".cloud 和 .online 怎么选：云服务属性与通用线上存在的取舍", en: ".cloud vs .online: Cloud-Native Semantics or Neutral Web Presence" } },
  { slug: "sh-vs-dev", a: "sh", b: "dev", title: { zh: ".sh 和 .dev 怎么选：极客暗号与官方认证的取舍", en: ".sh vs .dev: Insider Pun or the Official Developer TLD" } },
  { slug: "gg-vs-tv", a: "gg", b: "tv", title: { zh: ".gg 和 .tv 怎么选：游戏圈暗号与直播视频的取舍", en: ".gg vs .tv: Gaming Cred or Streaming Heritage" } },
  { slug: "so-vs-io", a: "so", b: "io", title: { zh: ".so 和 .io 怎么选：Notion 系新贵与技术圈老牌的取舍", en: ".so vs .io: The Notion-Era Upstart or the Dev-Scene Classic" } },
  { slug: "us-vs-com", a: "us", b: "com", title: { zh: ".us 和 .com 怎么选：美国本土信号与全球通用的取舍", en: ".us vs .com: The Domestic Signal or the Global Default" } },
  { slug: "in-vs-com", a: "in", b: "com", title: { zh: ".in 和 .com 怎么选：印度市场与短语梗 vs 全球默认", en: ".in vs .com: India Reach and Phrase Puns vs the Global Default" } },
  { slug: "info-vs-org", a: "info", b: "org", title: { zh: ".info 和 .org 怎么选：信息站与公信力的取舍", en: ".info vs .org: Information Utility or Institutional Trust" } },
  { slug: "com-vs-org", a: "com", b: "org", title: { zh: ".com 和 .org 怎么选：商业默认与公益公信力的分界", en: ".com vs .org: Commercial Default or Nonprofit Credibility" } },
  { slug: "com-vs-co", a: "com", b: "co", title: { zh: ".com 和 .co 怎么选：一个字母的分流代价", en: ".com vs .co: What One Missing Letter Costs You" } },
  { slug: "club-vs-gg", a: "club", b: "gg", title: { zh: ".club 和 .gg 怎么选：泛社区与游戏圈的身份对比", en: ".club vs .gg: General Community or Gaming Credibility" } },
  { slug: "studio-vs-co", a: "studio", b: "co", title: { zh: ".studio 和 .co 怎么选：作品气质与公司气质的取舍", en: ".studio vs .co: Portfolio Vibe or Company Polish" } },
  { slug: "me-vs-io", a: "me", b: "io", title: { zh: ".me 和 .io 怎么选：个人品牌与技术身份的对比", en: ".me vs .io: Personal Brand or Technical Identity" } },
  { slug: "ai-vs-tech", a: "ai", b: "tech", title: { zh: ".ai 和 .tech 怎么选：品类信号与泛科技的取舍", en: ".ai vs .tech: Category Precision or Broad-Tech Flexibility" } },
  { slug: "world-vs-com", a: "world", b: "com", title: { zh: ".world 和 .com 怎么选：全球化叙事与万能默认的取舍", en: ".world vs .com: Global Storytelling or the Universal Default" } },
  { slug: "life-vs-me", a: "life", b: "me", title: { zh: ".life 和 .me 怎么选：生活方式品牌与个人身份的对比", en: ".life vs .me: Lifestyle Brand or Personal Identity" } },
  { slug: "agency-vs-co", a: "agency", b: "co", title: { zh: ".agency 和 .co 怎么选：行业自述与简洁公司感的对比", en: ".agency vs .co: Self-Describing Suffix or Sleek Company Shorthand" } },
  { slug: "games-vs-gg", a: "games", b: "gg", title: { zh: ".games 和 .gg 怎么选：语义完整与电竞黑话的对比", en: ".games vs .gg: Full-Word Clarity or Esports Slang" } },
  { slug: "email-vs-net", a: "email", b: "net", title: { zh: ".email 和 .net 怎么选：品类精准与老牌通用的取舍", en: ".email vs .net: Category Precision or Veteran Generality" } },
  { slug: "network-vs-tech", a: "network", b: "tech", title: { zh: ".network 和 .tech 怎么选：协议叙事与泛科技的对比", en: ".network vs .tech: Protocol Narrative or Broad-Tech Flexibility" } },
  { slug: "life-vs-live", a: "life", b: "live", title: { zh: ".life 和 .live 怎么选：生活方式与实时现场的分野", en: ".life vs .live: Lifestyle Brand or Real-Time Broadcast" } },
  { slug: "email-vs-cloud", a: "email", b: "cloud", title: { zh: ".email 和 .cloud 怎么选：通信工具与云平台的定位对比", en: ".email vs .cloud: Messaging Niche or Cloud-Platform Breadth" } },
  { slug: "dev-vs-tech", a: "dev", b: "tech", title: { zh: ".dev 和 .tech 怎么选：开发者身份与泛科技声明的对比", en: ".dev vs .tech: Developer Badge or Broad Tech Statement" } },
  { slug: "app-vs-io", a: "app", b: "io", title: { zh: ".app 和 .io 怎么选：应用产品与技术圈层的取舍", en: ".app vs .io: Product Clarity or Developer Cachet" } },
  { slug: "info-vs-net", a: "info", b: "net", title: { zh: ".info 和 .net 怎么选：信息站与技术备选的老牌对决", en: ".info vs .net: Information Hub or Legacy Workhorse" } },
  { slug: "fun-vs-games", a: "fun", b: "games", title: { zh: ".fun 和 .games 怎么选：泛娱乐与游戏垂直的定位对比", en: ".fun vs .games: Broad Playfulness or Gaming-Industry Signal" } },
  { slug: "digital-vs-tech", a: "digital", b: "tech", title: { zh: ".digital 和 .tech 怎么选：数字服务与科技品牌的定位对比", en: ".digital vs .tech: Digital Services or Tech Identity" } },
  { slug: "media-vs-studio", a: "media", b: "studio", title: { zh: ".media 和 .studio 怎么选：内容公司与创作工作室的对比", en: ".media vs .studio: Content Company or Creative Workshop" } },
  { slug: "group-vs-agency", a: "group", b: "agency", title: { zh: ".group 和 .agency 怎么选：集团母牌与服务机构的对比", en: ".group vs .agency: Corporate Parent or Service Shop" } },
  { slug: "center-vs-club", a: "center", b: "club", title: { zh: ".center 和 .club 怎么选：服务枢纽与会员社群的对比", en: ".center vs .club: Service Hub or Member Community" } },
  { slug: "works-vs-studio", a: "works", b: "studio", title: { zh: ".works 和 .studio 怎么选：工坊双关与创作招牌的对比", en: ".works vs .studio: It-Works Pun or Creative Signboard" } },
  { slug: "zone-vs-site", a: "zone", b: "site", title: { zh: ".zone 和 .site 怎么选：主题地带与通用建站的对比", en: ".zone vs .site: Themed Territory or Neutral Website" } },
  { slug: "site-vs-com", a: "site", b: "com", title: { zh: ".site 和 .com 怎么选：一美元起步与黄金标准的取舍", en: ".site vs .com: One-Dollar Entry or the Gold Standard" } },
  { slug: "tech-vs-com", a: "tech", b: "com", title: { zh: ".tech 和 .com 怎么选：行业标签与万能默认的对比", en: ".tech vs .com: Industry Label or Universal Default" } },
  { slug: "store-vs-com", a: "store", b: "com", title: { zh: ".store 和 .com 怎么选：把「商店」写进域名值不值", en: ".store vs .com: Is Writing 'Store' into the Domain Worth It" } },
  { slug: "vip-vs-top", a: "vip", b: "top", title: { zh: ".vip 和 .top 怎么选：会员感与性价比的国内市场对比", en: ".vip vs .top: Membership Cachet vs Rock-Bottom Price" } },
  { slug: "art-vs-studio", a: "art", b: "studio", title: { zh: ".art 和 .studio 怎么选：作品身份与工作室招牌的对比", en: ".art vs .studio: Artistic Identity or Studio Signboard" } },
  { slug: "media-vs-tv", a: "media", b: "tv", title: { zh: ".media 和 .tv 怎么选：全媒体品牌与视频频道的对比", en: ".media vs .tv: Full-Stack Media Brand or Video Channel" } },
  { slug: "news-vs-media", a: "news", b: "media", title: { zh: ".news 和 .media 怎么选：资讯站招牌与内容公司门牌的对比", en: ".news vs .media: Publication Sign or Content-Company Nameplate" } },
  { slug: "tools-vs-app", a: "tools", b: "app", title: { zh: ".tools 和 .app 怎么选：工具箱招牌与应用产品的对比", en: ".tools vs .app: Toolbox Sign or Application Product" } },
  { slug: "run-vs-club", a: "run", b: "club", title: { zh: ".run 和 .club 怎么选：跑步双关与社群归属感的对比", en: ".run vs .club: The Running Pun or Community Belonging" } },
  { slug: "codes-vs-dev", a: "codes", b: "dev", title: { zh: ".codes 和 .dev 怎么选：双赛道后缀与开发者标配的对比", en: ".codes vs .dev: The Two-Track Suffix or the Developer Standard" } },
  { slug: "company-vs-group", a: "company", b: "group", title: { zh: ".company 和 .group 怎么选：一家公司与一个集团的门牌对比", en: ".company vs .group: Nameplate for a Company or a Group" } },
  { slug: "wiki-vs-info", a: "wiki", b: "info", title: { zh: ".wiki 和 .info 怎么选：百科招牌与信息老将的对比", en: ".wiki vs .info: The Encyclopedia Sign or the Information Veteran" } },
  { slug: "blog-vs-com", a: "blog", b: "com", title: { zh: ".blog 和 .com 怎么选：写作者身份与万能默认的对比", en: ".blog vs .com: Writer Identity vs the Universal Default" } },
  { slug: "team-vs-com", a: "team", b: "com", title: { zh: ".team 和 .com 怎么选：讲「人」的后缀与讲「产品」的默认", en: ".team vs .com: The People Suffix vs the Product Default" } },
  { slug: "chat-vs-app", a: "chat", b: "app", title: { zh: ".chat 和 .app 怎么选：对话形态与应用形态的信号对比", en: ".chat vs .app: Conversation Signal vs Application Signal" } },
  { slug: "finance-vs-com", a: "finance", b: "com", title: { zh: ".finance 和 .com 怎么选：品类信号与通用信任的对比", en: ".finance vs .com: Category Signal vs Universal Trust" } },
  { slug: "global-vs-world", a: "global", b: "world", title: { zh: ".global 和 .world 怎么选：企业宣言与叙事画布的对比", en: ".global vs .world: Corporate Statement vs Narrative Canvas" } },
  { slug: "host-vs-cloud", a: "host", b: "cloud", title: { zh: ".host 和 .cloud 怎么选：托管行业词与云品类词的对比", en: ".host vs .cloud: The Hosting Trade Word vs the Cloud Category Word" } },
  { slug: "social-vs-com", a: "social", b: "com", title: { zh: ".social 和 .com 怎么选：社区身份词与通用默认值的对比", en: ".social vs .com: Community Badge vs Universal Default" } },
  { slug: "video-vs-tv", a: "video", b: "tv", title: { zh: ".video 和 .tv 怎么选：内容形态词与频道气质词的对比", en: ".video vs .tv: The Format Word vs the Channel Vibe" } },
  { slug: "fund-vs-finance", a: "fund", b: "finance", title: { zh: ".fund 和 .finance 怎么选：一只基金与一个行业的对比", en: ".fund vs .finance: One Fund vs a Whole Industry" } },
  { slug: "land-vs-com", a: "land", b: "com", title: { zh: ".land 和 .com 怎么选：世界感行业词与通用默认值的对比", en: ".land vs .com: The World-Building Word vs the Universal Default" } },
  { slug: "click-vs-link", a: "click", b: "link", title: { zh: ".click 和 .link 怎么选：动作号召与聚合语义的对比", en: ".click vs .link: Call-to-Action vs Link-Hub Semantics" } },
  { slug: "icu-vs-xyz", a: "icu", b: "xyz", title: { zh: ".icu 和 .xyz 怎么选：低价三字母梗与年轻反叛旗帜的对比", en: ".icu vs .xyz: The Bargain Three-Letter Pun vs the Young Rebel Flag" } },
  { slug: "page-vs-com", a: "page", b: "com", title: { zh: ".page 和 .com 怎么选：Google 系诚实定价与通用默认值的对比", en: ".page vs .com: Google's Honest Pricing vs the Universal Default" } },
  { slug: "bio-vs-me", a: "bio", b: "me", title: { zh: ".bio 和 .me 怎么选：创作者简介页与个人品牌的对比", en: ".bio vs .me: The Creator Bio Page vs the Personal Brand Classic" } },
  { slug: "ink-vs-art", a: "ink", b: "art", title: { zh: ".ink 和 .art 怎么选：用墨的手艺与艺术圈名片的对比", en: ".ink vs .art: The Ink Trade's Slang vs the Art World's Business Card" } },
  { slug: "moe-vs-fun", a: "moe", b: "fun", title: { zh: ".moe 和 .fun 怎么选：二次元身份牌与泛娱乐后缀的对比", en: ".moe vs .fun: The Anime Identity Badge vs the General Entertainment Suffix" } },
  { slug: "lol-vs-gg", a: "lol", b: "gg", title: { zh: ".lol 和 .gg 怎么选：梗后缀与电竞行货的对比", en: ".lol vs .gg: The Meme Suffix vs Esports Standard Issue" } },
  { slug: "uk-vs-com", a: "uk", b: "com", title: { zh: ".uk 和 .com 怎么选：英国本地信任与全球默认值的对比", en: ".uk vs .com: British Local Trust vs the Global Default" } },
  { slug: "io-vs-sh", a: "io", b: "sh", title: { zh: ".io 和 .sh 怎么选：开发者两大极客后缀的对比", en: ".io vs .sh: Developer Suffix Showdown" } },
  { slug: "blog-vs-me", a: "blog", b: "me", title: { zh: ".blog 和 .me 怎么选：写作者与个人品牌后缀的对比", en: ".blog vs .me: The Writer's Suffix vs the Personal Brand Suffix" } },
  { slug: "org-vs-co", a: "org", b: "co", title: { zh: ".org 和 .co 怎么选：公信力与商业感的对比", en: ".org vs .co: Institutional Trust vs Startup Energy" } },
  { slug: "app-vs-site", a: "app", b: "site", title: { zh: ".app 和 .site 怎么选：产品信号与万能白纸的对比", en: ".app vs .site: The Product Signal vs the Blank Canvas" } },
  { slug: "com-vs-top", a: "com", b: "top", title: { zh: ".com 和 .top 怎么选：全球默认值与极致性价比的对比", en: ".com vs .top: The Global Default vs Rock-Bottom Pricing" } },
  { slug: "info-vs-com", a: "info", b: "com", title: { zh: ".info 和 .com 怎么选：信息站专属与商业默认值的对比", en: ".info vs .com: The Information Suffix vs the Commercial Default" } },
  { slug: "cc-vs-com", a: "cc", b: "com", title: { zh: ".cc 和 .com 怎么选：最像 .com 的替补与默认值本尊的对比", en: ".cc vs .com: The Closest Lookalike vs the Real Default" } },
  { slug: "tv-vs-com", a: "tv", b: "com", title: { zh: ".tv 和 .com 怎么选：视频品类信号与商业默认值的对比", en: ".tv vs .com: The Video Category Signal vs the Commercial Default" } },
  { slug: "fm-vs-tv", a: "fm", b: "tv", title: { zh: ".fm 和 .tv 怎么选：音频电台感与视频直播感的对比", en: ".fm vs .tv: Radio Vibes vs Streaming Vibes" } },
  { slug: "one-vs-me", a: "one", b: "me", title: { zh: ".one 和 .me 怎么选：极简品牌词与个人化后缀的对比", en: ".one vs .me: The Minimalist Brand Word vs the Personal Suffix" } },
  { slug: "cool-vs-fun", a: "cool", b: "fun", title: { zh: ".cool 和 .fun 怎么选：酷感调性与玩乐气质的对比", en: ".cool vs .fun: Attitude vs Playfulness" } },
  { slug: "red-vs-vip", a: "red", b: "vip", title: { zh: ".red 和 .vip 怎么选：红色喜庆感与会员尊贵感的对比", en: ".red vs .vip: Festive Red vs Members-Only Prestige" } },
  { slug: "bar-vs-cafe", a: "bar", b: "cafe", title: { zh: ".bar 和 .cafe 怎么选：酒吧夜场与咖啡日常的后缀对比", en: ".bar vs .cafe: Nightlife or Daytime Coffee Culture" } },
  { slug: "cafe-vs-shop", a: "cafe", b: "shop", title: { zh: ".cafe 和 .shop 怎么选：场景氛围与电商通用的对比", en: ".cafe vs .shop: Venue Vibe or E-commerce Default" } },
  { slug: "pizza-vs-com", a: "pizza", b: "com", title: { zh: ".pizza 和 .com 怎么选：品类直给与通用信任的对比", en: ".pizza vs .com: Category Punch or Universal Trust" } },
  { slug: "money-vs-finance", a: "money", b: "finance", title: { zh: ".money 和 .finance 怎么选：直白钱味与专业金融感的对比", en: ".money vs .finance: Blunt Cash Appeal or Institutional Polish" } },
  { slug: "gold-vs-vip", a: "gold", b: "vip", title: { zh: ".gold 和 .vip 怎么选：贵金属质感与会员尊贵感的对比", en: ".gold vs .vip: Precious-Metal Weight or Members-Only Status" } },
  { slug: "wtf-vs-lol", a: "wtf", b: "lol", title: { zh: ".wtf 和 .lol 怎么选：荒诞冲击与轻松好笑的对比", en: ".wtf vs .lol: Absurd Shock Value or Harmless Fun" } },
  { slug: "band-vs-fm", a: "band", b: "fm", title: { zh: ".band 和 .fm 怎么选：乐队身份与音频行业标签的对比", en: ".band vs .fm: Band Identity or Audio-Industry Badge" } },
  { slug: "cash-vs-money", a: "cash", b: "money", title: { zh: ".cash 和 .money 怎么选：到手的钱与理财叙事的对比", en: ".cash vs .money: Money in Hand or Money Managed" } },
  { slug: "city-vs-world", a: "city", b: "world", title: { zh: ".city 和 .world 怎么选：本地指向与全球叙事的对比", en: ".city vs .world: Local Focus or Global Narrative" } },
  { slug: "estate-vs-land", a: "estate", b: "land", title: { zh: ".estate 和 .land 怎么选：房产品牌与土地语义的对比", en: ".estate vs .land: Property Brand or Land Semantics" } },
  { slug: "expert-vs-pro", a: "expert", b: "pro", title: { zh: ".expert 和 .pro 怎么选：权威个体与泛专业感的对比", en: ".expert vs .pro: Named Authority or Generic Professionalism" } },
  { slug: "farm-vs-cafe", a: "farm", b: "cafe", title: { zh: ".farm 和 .cafe 怎么选：产地直供与场所空间的对比", en: ".farm vs .cafe: Source Story or Gathering Place" } },
  { slug: "ninja-vs-dev", a: "ninja", b: "dev", title: { zh: ".ninja 和 .dev 怎么选：梗后缀与开发者正装的对比", en: ".ninja vs .dev: Meme Badge or Developer Formalwear" } },
  { slug: "pet-vs-shop", a: "pet", b: "shop", title: { zh: ".pet 和 .shop 怎么选：行业专属与电商通用的对比", en: ".pet vs .shop: Industry Precision or E-commerce Generic" } },
  { slug: "blue-vs-red", a: "blue", b: "red", title: { zh: ".blue 和 .red 怎么选：冷静信任与热情流量的颜色对比", en: ".blue vs .red: Calm Trust or Hot Energy in a Color" } },
  { slug: "black-vs-gold", a: "black", b: "gold", title: { zh: ".black 和 .gold 怎么选：黑金两色的高端叙事对比", en: ".black vs .gold: Two Colors of Premium" } },
  { slug: "rocks-vs-fun", a: "rocks", b: "fun", title: { zh: ".rocks 和 .fun 怎么选：喝彩表达与娱乐气质的对比", en: ".rocks vs .fun: A Cheer or an Amusement Sign" } },
  { slug: "pink-vs-me", a: "pink", b: "me", title: { zh: ".pink 和 .me 怎么选：甜美调性与个人身份的对比", en: ".pink vs .me: A Color Mood or a Personal Identity" } },
  { slug: "academy-vs-school", a: "academy", b: "school", title: { zh: ".academy 和 .school 怎么选：体系化学院与日常学校的对比", en: ".academy vs .school: Structured Curriculum or Everyday Classroom" } },
  { slug: "care-vs-doctor", a: "care", b: "doctor", title: { zh: ".care 和 .doctor 怎么选：服务温度与专业身份的对比", en: ".care vs .doctor: Service Warmth or Professional Authority" } },
  { slug: "coach-vs-expert", a: "coach", b: "expert", title: { zh: ".coach 和 .expert 怎么选：带练身份与权威招牌的对比", en: ".coach vs .expert: Training Partner or Authority Sign" } },
  { slug: "restaurant-vs-cafe", a: "restaurant", b: "cafe", title: { zh: ".restaurant 和 .cafe 怎么选：正餐门面与轻食空间的对比", en: ".restaurant vs .cafe: Full-Service Storefront or Cozy Corner" } },
  { slug: "academy-vs-coach", a: "academy", b: "coach", title: { zh: ".academy 和 .coach 怎么选：课程体系与个人带练的对比", en: ".academy vs .coach: A Curriculum or a Person" } },
  { slug: "restaurant-vs-bar", a: "restaurant", b: "bar", title: { zh: ".restaurant 和 .bar 怎么选：正餐招牌与夜生活霓虹的对比", en: ".restaurant vs .bar: Daytime Sign or Neon Lights" } },
  { slug: "clinic-vs-care", a: "clinic", b: "care", title: { zh: ".clinic 和 .care 怎么选：门诊场所与服务温度的对比", en: ".clinic vs .care: The Place You Visit or the Way You're Treated" } },
  { slug: "dental-vs-doctor", a: "dental", b: "doctor", title: { zh: ".dental 和 .doctor 怎么选：垂直科室与执业身份的对比", en: ".dental vs .doctor: One Specialty Deep or the Whole Profession" } },
  { slug: "fitness-vs-coach", a: "fitness", b: "coach", title: { zh: ".fitness 和 .coach 怎么选：场馆项目与教练个人的对比", en: ".fitness vs .coach: The Venue and Program or the Person Training You" } },
  { slug: "photos-vs-gallery", a: "photos", b: "gallery", title: { zh: ".photos 和 .gallery 怎么选：照片交付与策展陈列的对比", en: ".photos vs .gallery: Delivering Pictures or Curating a Show" } },
  { slug: "boutique-vs-shop", a: "boutique", b: "shop", title: { zh: ".boutique 和 .shop 怎么选：策展精品与货架电商的对比", en: ".boutique vs .shop: Curated Taste or Conversion Shelf" } },
  { slug: "gallery-vs-art", a: "gallery", b: "art", title: { zh: ".gallery 和 .art 怎么选：展出动作与艺术身份的对比", en: ".gallery vs .art: The Act of Exhibiting or the Identity of Art" } },
  { slug: "salon-vs-studio", a: "salon", b: "studio", title: { zh: ".salon 和 .studio 怎么选：美业门店与创作团队的对比", en: ".salon vs .studio: The Beauty Storefront or the Creative Workshop" } },
  { slug: "yoga-vs-fitness", a: "yoga", b: "fitness", title: { zh: ".yoga 和 .fitness 怎么选：垂直流派与全场馆的对比", en: ".yoga vs .fitness: One Practice Deep or the Whole Gym Floor" } },
  { slug: "coffee-vs-cafe", a: "coffee", b: "cafe", title: { zh: ".coffee 和 .cafe 怎么选：咖啡这件事与那家店的对比", en: ".coffee vs .cafe: The Thing Itself or the Place You Sit" } },
  { slug: "wine-vs-bar", a: "wine", b: "bar", title: { zh: ".wine 和 .bar 怎么选：产业链与夜场门店的对比", en: ".wine vs .bar: The Whole Chain or the Neon Doorway" } },
  { slug: "kitchen-vs-restaurant", a: "kitchen", b: "restaurant", title: { zh: ".kitchen 和 .restaurant 怎么选：做菜的地方与堂食的店的对比", en: ".kitchen vs .restaurant: Where You Cook or Where They Dine" } },
  { slug: "garden-vs-farm", a: "garden", b: "farm", title: { zh: ".garden 和 .farm 怎么选：花园意象与农场直供的对比", en: ".garden vs .farm: Green Imagery or Farm-to-Table Trust" } },
  { slug: "photography-vs-photos", a: "photography", b: "photos", title: { zh: ".photography 和 .photos 怎么选：手艺身份与照片本身的对比", en: ".photography vs .photos: The Craft or The Pictures" } },
  { slug: "events-vs-live", a: "events", b: "live", title: { zh: ".events 和 .live 怎么选：活动日历与正在直播的对比", en: ".events vs .live: The Calendar or The Broadcast" } },
  { slug: "solutions-vs-services", a: "solutions", b: "services", title: { zh: ".solutions 和 .services 怎么选：解决问题与提供服务的对比", en: ".solutions vs .services: We Fix Problems or We Offer Services" } },
  { slug: "consulting-vs-expert", a: "consulting", b: "expert", title: { zh: ".consulting 和 .expert 怎么选：职业身份与专业断言的对比", en: ".consulting vs .expert: The Profession or The Claim" } },
  { slug: "software-vs-app", a: "software", b: "app", title: { zh: ".software 和 .app 怎么选：正经软件与轻快应用的对比", en: ".software vs .app: The Suit or The T-Shirt" } },
  { slug: "services-vs-agency", a: "services", b: "agency", title: { zh: ".services 和 .agency 怎么选：服务清单与创意团队的对比", en: ".services vs .agency: The Menu or The Team" } },
  { slug: "marketing-vs-agency", a: "marketing", b: "agency", title: { zh: ".marketing 和 .agency 怎么选：专业能力与机构身份的对比", en: ".marketing vs .agency: The Expertise or The Firm" } },
  { slug: "capital-vs-fund", a: "capital", b: "fund", title: { zh: ".capital 和 .fund 怎么选：机构全名与一只基金的对比", en: ".capital vs .fund: The Firm or The Pool of Money" } },
  { slug: "guru-vs-expert", a: "guru", b: "expert", title: { zh: ".guru 和 .expert 怎么选：亲切人设与一本正经的对比", en: ".guru vs .expert: The Wink or The Straight Face" } },
  { slug: "systems-vs-network", a: "systems", b: "network", title: { zh: ".systems 和 .network 怎么选：成套工程与互联叙事的对比", en: ".systems vs .network: The Machine or The Mesh" } },
  { slug: "ventures-vs-capital", a: "ventures", b: "capital", title: { zh: ".ventures 和 .capital 怎么选：早期押注与机构规模的对比", en: ".ventures vs .capital: The Bet or The Institution" } },
  { slug: "tips-vs-blog", a: "tips", b: "blog", title: { zh: ".tips 和 .blog 怎么选：实用承诺与写作园地的对比", en: ".tips vs .blog: The Promise of Useful or The Promise of Writing" } },
  { slug: "market-vs-exchange", a: "market", b: "exchange", title: { zh: ".market 和 .exchange 怎么选：多方陈列与双向撮合的对比", en: ".market vs .exchange: The Bazaar or The Match" } },
  { slug: "watch-vs-show", a: "watch", b: "show", title: { zh: ".watch 和 .show 怎么选：观看动作与节目名号的对比", en: ".watch vs .show: The Verb or The Title" } },
  { slug: "house-vs-style", a: "house", b: "style", title: { zh: ".house 和 .style 怎么选：居住场景与审美主张的对比", en: ".house vs .style: The Place or The Taste" } },
  { slug: "institute-vs-international", a: "institute", b: "international", title: { zh: ".institute 和 .international 怎么选：研究权威与全球版图的对比", en: ".institute vs .international: The Authority or The Footprint" } },
  { slug: "partners-vs-group", a: "partners", b: "group", title: { zh: ".partners 和 .group 怎么选：合伙名号与集团门面的对比", en: ".partners vs .group: The Nameplate or The Parent" } },
  { slug: "support-vs-center", a: "support", b: "center", title: { zh: ".support 和 .center 怎么选：帮助入口与枢纽名号的对比", en: ".support vs .center: The Help Door or The Hub" } },
  { slug: "website-vs-site", a: "website", b: "site", title: { zh: ".website 和 .site 怎么选：完整单词与中性白纸的对比", en: ".website vs .site: The Full Word or The Blank Canvas" } },
  { slug: "technology-vs-tech", a: "technology", b: "tech", title: { zh: ".technology 和 .tech 怎么选：正式全称与创业短音的对比", en: ".technology vs .tech: The Full Name or The Startup Clip" } },
  { slug: "community-vs-club", a: "community", b: "club", title: { zh: ".community 和 .club 怎么选：开放家园与会员俱乐部的对比", en: ".community vs .club: The Open Home or The Members' Door" } },
  { slug: "education-vs-academy", a: "education", b: "academy", title: { zh: ".education 和 .academy 怎么选：行业大词与机构名号的对比", en: ".education vs .academy: The Industry Word or The Institution's Name" } },
  { slug: "training-vs-coach", a: "training", b: "coach", title: { zh: ".training 和 .coach 怎么选：练什么与谁来带的对比", en: ".training vs .coach: The Drill or The Person" } },
  { slug: "love-vs-me", a: "love", b: "me", title: { zh: ".love 和 .me 怎么选：情感宣言与个人名片的对比", en: ".love vs .me: The Declaration or The Calling Card" } },
  { slug: "beauty-vs-salon", a: "beauty", b: "salon", title: { zh: ".beauty 和 .salon 怎么选：行业大词与门店招牌的对比", en: ".beauty vs .salon: The Industry Word or The Shop Sign" } },
  { slug: "fashion-vs-style", a: "fashion", b: "style", title: { zh: ".fashion 和 .style 怎么选：行业专词与审美泛词的对比", en: ".fashion vs .style: The Industry Word or The Aesthetic Word" } },
  { slug: "work-vs-works", a: "work", b: "works", title: { zh: ".work 和 .works 怎么选：一字之差的职业与作品分工", en: ".work vs .works: One Letter Between the Job and the Craft" } },
  { slug: "sale-vs-shop", a: "sale", b: "shop", title: { zh: ".sale 和 .shop 怎么选：促销档期与常设店面的对比", en: ".sale vs .shop: The Limited-Time Event or The Open Store" } },
  { slug: "help-vs-support", a: "help", b: "support", title: { zh: ".help 和 .support 怎么选：短口语与全称的求助入口对比", en: ".help vs .support: The Short Word or The Full Word at the Front Desk" } },
  { slug: "wedding-vs-love", a: "wedding", b: "love", title: { zh: ".wedding 和 .love 怎么选：一场婚礼与一份情感的对比", en: ".wedding vs .love: The Big Day or The Big Feeling" } },
  { slug: "law-vs-pro", a: "law", b: "pro", title: { zh: ".law 和 .pro 怎么选：行业门牌与泛专业感的对比", en: ".law vs .pro: The Industry Nameplate or The Generic Credential" } },
  { slug: "tax-vs-finance", a: "tax", b: "finance", title: { zh: ".tax 和 .finance 怎么选：报税专词与金融泛词的对比", en: ".tax vs .finance: The Filing Word or The Industry Word" } },
  { slug: "menu-vs-restaurant", a: "menu", b: "restaurant", title: { zh: ".menu 和 .restaurant 怎么选：一张菜单与一家店的对比", en: ".menu vs .restaurant: The Card or The House" } },
  { slug: "bike-vs-fitness", a: "bike", b: "fitness", title: { zh: ".bike 和 .fitness 怎么选：一项运动与一个行业的对比", en: ".bike vs .fitness: One Sport or The Whole Industry" } },
  { slug: "toys-vs-shop", a: "toys", b: "shop", title: { zh: ".toys 和 .shop 怎么选：品类货架与万能商店的对比", en: ".toys vs .shop: The Category Shelf or The Universal Store" } },
  { slug: "shoes-vs-fashion", a: "shoes", b: "fashion", title: { zh: ".shoes 和 .fashion 怎么选：品类垂直与行业全称的对比", en: ".shoes vs .fashion: The Vertical or The Industry" } },
  { slug: "plus-vs-vip", a: "plus", b: "vip", title: { zh: ".plus 和 .vip 怎么选：升级入口与会员身份的对比", en: ".plus vs .vip: The Upgrade or The Membership" } },
  { slug: "house-vs-estate", a: "house", b: "estate", title: { zh: ".house 和 .estate 怎么选：一栋房子与一份资产的对比", en: ".house vs .estate: The Home or The Asset" } },
  { slug: "shoes-vs-store", a: "shoes", b: "store", title: { zh: ".shoes 和 .store 怎么选：品类招牌与万能商城的对比", en: ".shoes vs .store: The Category Sign or The Universal Mall" } },
  { slug: "toys-vs-games", a: "toys", b: "games", title: { zh: ".toys 和 .games 怎么选：实体玩具与游戏行业的对比", en: ".toys vs .games: Physical Play or The Games Industry" } },
  { slug: "menu-vs-cafe", a: "menu", b: "cafe", title: { zh: ".menu 和 .cafe 怎么选：一张菜单与一间咖啡馆的对比", en: ".menu vs .cafe: The Card or The Corner Shop" } },
  { slug: "law-vs-expert", a: "law", b: "expert", title: { zh: ".law 和 .expert 怎么选：行业门牌与权威人设的对比", en: ".law vs .expert: The Trade Plaque or The Authority Claim" } },
  { slug: "com-vs-travel", a: "com", b: "travel", title: { zh: ".com 和 .travel 怎么选：万能牌与行业老牌的取舍", en: ".com vs .travel: The Universal Card or The Industry Veteran" } },
  { slug: "travel-vs-tours", a: "travel", b: "tours", title: { zh: ".travel 和 .tours 怎么选：行业词与产品词的分工", en: ".travel vs .tours: The Industry Word or The Product Word" } },
  { slug: "vacations-vs-holiday", a: "vacations", b: "holiday", title: { zh: ".vacations 和 .holiday 怎么选：度假场景与节庆语义的分野", en: ".vacations vs .holiday: The Getaway Word or The Festive Word" } },
  { slug: "flights-vs-travel", a: "flights", b: "travel", title: { zh: ".flights 和 .travel 怎么选：垂直航段与行业全域的取舍", en: ".flights vs .travel: The Vertical Leg or The Whole Industry" } },
  { slug: "tours-vs-vacations", a: "tours", b: "vacations", title: { zh: ".tours 和 .vacations 怎么选：走线路与住下来的场景分工", en: ".tours vs .vacations: The Route or The Stay" } },
  { slug: "taxi-vs-city", a: "taxi", b: "city", title: { zh: ".taxi 和 .city 怎么选：接送专线与城市门户的分工", en: ".taxi vs .city: The Ride Service or The City Portal" } },
  { slug: "properties-vs-estate", a: "properties", b: "estate", title: { zh: ".properties 和 .estate 怎么选：资产清单与行业门牌的分工", en: ".properties vs .estate: The Portfolio Word or The Trade Plaque" } },
  { slug: "apartments-vs-rentals", a: "apartments", b: "rentals", title: { zh: ".apartments 和 .rentals 怎么选：房型词与交易词的分工", en: ".apartments vs .rentals: The Property Type or The Transaction Word" } },
  { slug: "properties-vs-rentals", a: "properties", b: "rentals", title: { zh: ".properties 和 .rentals 怎么选：卖与租两种生意的分工", en: ".properties vs .rentals: Selling Assets or Renting Them Out" } },
  { slug: "builders-vs-construction", a: "builders", b: "construction", title: { zh: ".builders 和 .construction 怎么选：施工班组与工程公司的分工", en: ".builders vs .construction: The Crew or The Firm" } },
  { slug: "repair-vs-services", a: "repair", b: "services", title: { zh: ".repair 和 .services 怎么选：修一件事与包一揽子的分工", en: ".repair vs .services: The One Fix or The Full Bundle" } },
  { slug: "apartments-vs-house", a: "apartments", b: "house", title: { zh: ".apartments 和 .house 怎么选：招租页与家宅品牌的分工", en: ".apartments vs .house: The Leasing Page or The House Brand" } },
  { slug: "energy-vs-solar", a: "energy", b: "solar", title: { zh: ".energy 和 .solar 怎么选：全行业与单赛道的分工", en: ".energy vs .solar: The Whole Industry or The Single Lane" } },
  { slug: "green-vs-eco", a: "green", b: "eco", title: { zh: ".green 和 .eco 怎么选：形容词与认证徽章的分工", en: ".green vs .eco: The Adjective or The Vetted Badge" } },
  { slug: "eco-vs-earth", a: "eco", b: "earth", title: { zh: ".eco 和 .earth 怎么选：承诺档案与星球叙事的分工", en: ".eco vs .earth: The Vetted Pledge or The Planet Story" } },
  { slug: "earth-vs-world", a: "earth", b: "world", title: { zh: ".earth 和 .world 怎么选：星球词与世界词的分工", en: ".earth vs .world: The Planet Word or The People Word" } },
  { slug: "engineering-vs-tech", a: "engineering", b: "tech", title: { zh: ".engineering 和 .tech 怎么选：职业身份与科技氛围的分工", en: ".engineering vs .tech: The Profession or The Vibe" } },
  { slug: "engineering-vs-dev", a: "engineering", b: "dev", title: { zh: ".engineering 和 .dev 怎么选：工程门牌与开发者签名的分工", en: ".engineering vs .dev: The Firm's Plaque or The Developer's Signature" } },
  { slug: "family-vs-com", a: "family", b: "com", title: { zh: ".family 和 .com 怎么选：家庭温度与通用信任的取舍", en: ".family vs .com: Warmth of the Household or Default Trust" } },
  { slug: "baby-vs-store", a: "baby", b: "store", title: { zh: ".baby 和 .store 怎么选：母婴垂直与通用货架的分工", en: ".baby vs .store: The Vertical Audience or The General Shelf" } },
  { slug: "mom-vs-me", a: "mom", b: "me", title: { zh: ".mom 和 .me 怎么选：妈妈身份与个人品牌的分工", en: ".mom vs .me: The Mom Identity or The Personal Brand" } },
  { slug: "dad-vs-blog", a: "dad", b: "blog", title: { zh: ".dad 和 .blog 怎么选：爸爸人设与写作阵地的分工", en: ".dad vs .blog: The Dad Persona or The Writing Home" } },
  { slug: "dog-vs-pet", a: "dog", b: "pet", title: { zh: ".dog 和 .pet 怎么选：犬类专营与全宠物赛道的分工", en: ".dog vs .pet: The Dog Lane or The Whole Pet Aisle" } },
  { slug: "gifts-vs-shop", a: "gifts", b: "shop", title: { zh: ".gifts 和 .shop 怎么选：送礼场景与通用店铺的分工", en: ".gifts vs .shop: The Occasion or The Storefront" } },
  { slug: "photo-vs-photography", a: "photo", b: "photography", title: { zh: ".photo 和 .photography 怎么选：单数名片与全拼手艺的分工", en: ".photo vs .photography: The Business Card or The Craft in Full" } },
  { slug: "health-vs-life", a: "health", b: "life", title: { zh: ".health 和 .life 怎么选：行业信号与生活温度的取舍", en: ".health vs .life: The Industry Signal or The Warmth of Living" } },
  { slug: "fit-vs-fitness", a: "fit", b: "fitness", title: { zh: ".fit 和 .fitness 怎么选：口号短词与全拼场馆的分工", en: ".fit vs .fitness: The Slogan or The Gym in Full" } },
  { slug: "dance-vs-studio", a: "dance", b: "studio", title: { zh: ".dance 和 .studio 怎么选：舞种锐度与创作空间的分工", en: ".dance vs .studio: The Dance Lane or The Creative Room" } },
  { slug: "guide-vs-tips", a: "guide", b: "tips", title: { zh: ".guide 和 .tips 怎么选：成体系攻略与轻量技巧的分工", en: ".guide vs .tips: The Full Walkthrough or The Quick Trick" } },
  { slug: "reviews-vs-blog", a: "reviews", b: "blog", title: { zh: ".reviews 和 .blog 怎么选：评测立场与写作阵地的分工", en: ".reviews vs .blog: The Verdict Stand or The Writing Home" } },
  { slug: "golf-vs-club", a: "golf", b: "club", title: { zh: ".golf 和 .club 怎么选：球场品类与社群归属的分工", en: ".golf vs .club: The Course Category or The Member Circle" } },
  { slug: "tennis-vs-coach", a: "tennis", b: "coach", title: { zh: ".tennis 和 .coach 怎么选：项目招牌与职业身份的分工", en: ".tennis vs .coach: The Sport's Banner or The Trainer's Title" } },
  { slug: "soccer-vs-football", a: "soccer", b: "football", title: { zh: ".soccer 和 .football 怎么选：北美叫法与全球叫法的分工", en: ".soccer vs .football: The American Word or The World's Word" } },
  { slug: "hockey-vs-team", a: "hockey", b: "team", title: { zh: ".hockey 和 .team 怎么选：冰球专营与队伍通用的分工", en: ".hockey vs .team: The Rink Vertical or The Any-Squad Banner" } },
  { slug: "surf-vs-fun", a: "surf", b: "fun", title: { zh: ".surf 和 .fun 怎么选：浪点垂直与泛娱乐的分工", en: ".surf vs .fun: The Break Vertical or The Playground Banner" } },
  { slug: "golf-vs-travel", a: "golf", b: "travel", title: { zh: ".golf 和 .travel 怎么选：球场生意与行程生意的分工", en: ".golf vs .travel: The Course Business or The Itinerary Business" } },
  { slug: "tennis-vs-club", a: "tennis", b: "club", title: { zh: ".tennis 和 .club 怎么选：网球品类与社群归属的分工", en: ".tennis vs .club: The Court Category or The Member Circle" } },
  { slug: "soccer-vs-club", a: "soccer", b: "club", title: { zh: ".soccer 和 .club 怎么选：足球品类与俱乐部招牌的分工", en: ".soccer vs .club: The Pitch Category or The Clubhouse Sign" } },
  { slug: "football-vs-team", a: "football", b: "team", title: { zh: ".football 和 .team 怎么选：足球专营与队伍通用的分工", en: ".football vs .team: The Sport Vertical or The Any-Squad Banner" } },
  { slug: "health-vs-care", a: "health", b: "care", title: { zh: ".health 和 .care 怎么选：健康行业与照护服务的分工", en: ".health vs .care: The Industry Storefront or The Service Warmth" } },
  { slug: "family-vs-life", a: "family", b: "life", title: { zh: ".family 和 .life 怎么选：家庭场景与生活方式的分工", en: ".family vs .life: The Household Unit or The Lifestyle Topic" } },
  { slug: "surf-vs-travel", a: "surf", b: "travel", title: { zh: ".surf 和 .travel 怎么选：浪点生意与行程生意的分工", en: ".surf vs .travel: The Break Business or The Itinerary Business" } },
  { slug: "ltd-vs-llc", a: "ltd", b: "llc", title: { zh: ".ltd 和 .llc 怎么选：注册地决定的公司抬头对比", en: ".ltd vs .llc: The Letterhead Suffix, Picked by Where You're Registered" } },
  { slug: "ltd-vs-co", a: "ltd", b: "co", title: { zh: ".ltd 和 .co 怎么选：注册抬头与品牌简写的取舍", en: ".ltd vs .co: The Certificate or The Brand Shorthand" } },
  { slug: "biz-vs-com", a: "biz", b: "com", title: { zh: ".biz 和 .com 怎么选：老牌替补与默认答案的对比", en: ".biz vs .com: The Veteran Fallback or The Default Answer" } },
  { slug: "fyi-vs-info", a: "fyi", b: "info", title: { zh: ".fyi 和 .info 怎么选：轻快速查与正式资料的分工", en: ".fyi vs .info: The Quick Lookup or The Formal Reference" } },
  { slug: "promo-vs-shop", a: "promo", b: "shop", title: { zh: ".promo 和 .shop 怎么选：活动阵地与常设店铺的分工", en: ".promo vs .shop: The Campaign Outpost or The Permanent Storefront" } },
  { slug: "express-vs-store", a: "express", b: "store", title: { zh: ".express 和 .store 怎么选：快服务与常设商店的分工", en: ".express vs .store: Selling Speed or Selling Shelves" } },
  { slug: "press-vs-news", a: "press", b: "news", title: { zh: ".press 和 .news 怎么选：媒体身份与资讯站的分工", en: ".press vs .news: Editorial Identity or The News Destination" } },
  { slug: "stream-vs-live", a: "stream", b: "live", title: { zh: ".stream 和 .live 怎么选：流本身与现场感的分工", en: ".stream vs .live: The Stream Itself or The Live Moment" } },
  { slug: "movie-vs-tv", a: "movie", b: "tv", title: { zh: ".movie 和 .tv 怎么选：单片战役与频道品牌的分工", en: ".movie vs .tv: The Film Campaign or The Channel Brand" } },
  { slug: "pictures-vs-photos", a: "pictures", b: "photos", title: { zh: ".pictures 和 .photos 怎么选：制片公司范与照片交付的分工", en: ".pictures vs .photos: Studio Pedigree or Photo Delivery" } },
  { slug: "productions-vs-studio", a: "productions", b: "studio", title: { zh: ".productions 和 .studio 怎么选：接案制作公司与创意小团队的分工", en: ".productions vs .studio: The For-Hire Shop or The Creative Studio" } },
  { slug: "audio-vs-fm", a: "audio", b: "fm", title: { zh: ".audio 和 .fm 怎么选：声音产业与电台气质的分工", en: ".audio vs .fm: The Sound Industry or The Radio Vibe" } },
  { slug: "credit-vs-finance", a: "credit", b: "finance", title: { zh: ".credit 和 .finance 怎么选：信用垂直与综合金融的分工", en: ".credit vs .finance: The Credit Vertical or Finance at Large" } },
  { slug: "loans-vs-money", a: "loans", b: "money", title: { zh: ".loans 和 .money 怎么选：贷款产品与理财内容的分界", en: ".loans vs .money: Lending Products or Money Content" } },
  { slug: "investments-vs-fund", a: "investments", b: "fund", title: { zh: ".investments 和 .fund 怎么选：综合投资门面与一笔钱的分工", en: ".investments vs .fund: The Firm's Front Door or The Single Pool" } },
  { slug: "holdings-vs-group", a: "holdings", b: "group", title: { zh: ".holdings 和 .group 怎么选：控股主体与经营集团的分工", en: ".holdings vs .group: The Asset Holder or The Operating Group" } },
  { slug: "mortgage-vs-estate", a: "mortgage", b: "estate", title: { zh: ".mortgage 和 .estate 怎么选：房贷生意与房产招牌的分工", en: ".mortgage vs .estate: The Home-Loan Business or The Property Sign" } },
  { slug: "computer-vs-tech", a: "computer", b: "tech", title: { zh: ".computer 和 .tech 怎么选：硬件维修具体词与科技泛称的分工", en: ".computer vs .tech: The Machine Itself or The Industry at Large" } },
  { slug: "lawyer-vs-legal", a: "lawyer", b: "legal", title: { zh: ".lawyer 和 .legal 怎么选：律师个人牌与法律行业牌的分工", en: ".lawyer vs .legal: The Attorney's Nameplate or The Industry's Address" } },
  { slug: "vet-vs-pet", a: "vet", b: "pet", title: { zh: ".vet 和 .pet 怎么选：兽医专业与宠物生意的分工", en: ".vet vs .pet: The Clinic's Credential or The Pet Economy's Address" } },
  { slug: "delivery-vs-express", a: "delivery", b: "express", title: { zh: ".delivery 和 .express 怎么选：送上门与快承诺的分工", en: ".delivery vs .express: To Your Door or At Full Speed" } },
  { slug: "recipes-vs-menu", a: "recipes", b: "menu", title: { zh: ".recipes 和 .menu 怎么选：做法内容与点餐入口的分工", en: ".recipes vs .menu: Follow-Along Content or The Ordering Door" } },
  { slug: "rent-vs-rentals", a: "rent", b: "rentals", title: { zh: ".rent 和 .rentals 怎么选：动词品牌与列表聚合的分工", en: ".rent vs .rentals: The Verb Brand or The Listings Aggregator" } },
  { slug: "legal-vs-law", a: "legal", b: "law", title: { zh: ".legal 和 .law 怎么选：法律平台与律所门牌的分工", en: ".legal vs .law: The Legal Platform or The Firm's Brass Nameplate" } },
  { slug: "jewelry-vs-boutique", a: "jewelry", b: "boutique", title: { zh: ".jewelry 和 .boutique 怎么选：品类门牌与精品调性的分工", en: ".jewelry vs .boutique: The Category Nameplate or The Curated Air" } },
  { slug: "cleaning-vs-services", a: "cleaning", b: "services", title: { zh: ".cleaning 和 .services 怎么选：精准品类与多业态平台的分工", en: ".cleaning vs .services: The Precise Category or The Multi-Trade Platform" } },
  { slug: "plumbing-vs-repair", a: "plumbing", b: "repair", title: { zh: ".plumbing 和 .repair 怎么选：水暖专业身份与综合维修的分工", en: ".plumbing vs .repair: The Trade Identity or The Catch-All Fix" } },
  { slug: "catering-vs-restaurant", a: "catering", b: "restaurant", title: { zh: ".catering 和 .restaurant 怎么选：外烩承办与堂食门店的分工", en: ".catering vs .restaurant: Bringing the Feast or Seating the Guest" } },
  { slug: "florist-vs-garden", a: "florist", b: "garden", title: { zh: ".florist 和 .garden 怎么选：花艺师门牌与园艺生活的分工", en: ".florist vs .garden: The Bouquet Counter or The Growing Ground" } },
  { slug: "church-vs-community", a: "church", b: "community", title: { zh: ".church 和 .community 怎么选：教会身份与社群平台的分工", en: ".church vs .community: The Faith Nameplate or The Gathering Ground" } },
  { slug: "courses-vs-academy", a: "courses", b: "academy", title: { zh: ".courses 和 .academy 怎么选：课程目录与教学机构的分工", en: ".courses vs .academy: The Course Catalog or The Institution's Nameplate" } },
  { slug: "degree-vs-education", a: "degree", b: "education", title: { zh: ".degree 和 .education 怎么选：学位项目与教育机构的分工", en: ".degree vs .education: The Credential or The Industry Nameplate" } },
  { slug: "mba-vs-school", a: "mba", b: "school", title: { zh: ".mba 和 .school 怎么选：商学院身份与泛教学场景的分工", en: ".mba vs .school: The B-School Badge or The Everyteach Nameplate" } },
  { slug: "study-vs-courses", a: "study", b: "courses", title: { zh: ".study 和 .courses 怎么选：学习动作与课程目录的分工", en: ".study vs .courses: The Verb of Learning or The Product on the Shelf" } },
  { slug: "forum-vs-community", a: "forum", b: "community", title: { zh: ".forum 和 .community 怎么选：发帖式论坛与泛社群身份的分工", en: ".forum vs .community: The Threaded Board or The Broad Gathering" } },
  { slug: "review-vs-reviews", a: "review", b: "reviews", title: { zh: ".review 和 .reviews 怎么选：评测媒体与点评聚合的分工", en: ".review vs .reviews: The Editorial Verdict or The Rating Pile" } },
  { slug: "hair-vs-salon", a: "hair", b: "salon", title: { zh: ".hair 和 .salon 怎么选：美发垂类与门店业态的分工", en: ".hair vs .salon: The Hair Vertical or The Shop Format" } },
  { slug: "skin-vs-beauty", a: "skin", b: "beauty", title: { zh: ".skin 和 .beauty 怎么选：护肤垂类与美妆全域的分工", en: ".skin vs .beauty: The Skincare Vertical or The Whole Beauty Aisle" } },
  { slug: "makeup-vs-boutique", a: "makeup", b: "boutique", title: { zh: ".makeup 和 .boutique 怎么选：彩妆品类与精品调性的分工", en: ".makeup vs .boutique: The Cosmetics Category or The Curated Vibe" } },
  { slug: "homes-vs-house", a: "homes", b: "house", title: { zh: ".homes 和 .house 怎么选：房源清单与单栋场景的分工", en: ".homes vs .house: The Listing Pile or The Single Address" } },
  { slug: "boats-vs-travel", a: "boats", b: "travel", title: { zh: ".boats 和 .travel 怎么选：船艇垂类与旅游行业的分工", en: ".boats vs .travel: The Vessel Vertical or The Industry Badge" } },
  { slug: "autos-vs-repair", a: "autos", b: "repair", title: { zh: ".autos 和 .repair 怎么选：汽车行业与维修服务的分工", en: ".autos vs .repair: The Industry Nameplate or The Action Word" } },
  { slug: "careers-vs-work", a: "careers", b: "work", title: { zh: ".careers 和 .work 怎么选：招聘门户与泛工作场景的分工", en: ".careers vs .work: The Hiring Portal or The Broad Work Scene" } },
  { slug: "management-vs-consulting", a: "management", b: "consulting", title: { zh: ".management 和 .consulting 怎么选：管理服务与咨询行业的分工", en: ".management vs .consulting: Running It For You or Advising You" } },
  { slug: "contractors-vs-construction", a: "contractors", b: "construction", title: { zh: ".contractors 和 .construction 怎么选：承包商身份与建筑行业的分工", en: ".contractors vs .construction: The Crew Identity or The Industry Name" } },
  { slug: "equipment-vs-rentals", a: "equipment", b: "rentals", title: { zh: ".equipment 和 .rentals 怎么选：卖设备与租设备的分工", en: ".equipment vs .rentals: Selling The Gear or Renting It Out" } },
  { slug: "supply-vs-express", a: "supply", b: "express", title: { zh: ".supply 和 .express 怎么选：供货口径与快送口径的分工", en: ".supply vs .express: The Source of Goods or The Speed Promise" } },
  { slug: "parts-vs-repair", a: "parts", b: "repair", title: { zh: ".parts 和 .repair 怎么选：卖配件与修东西的分工", en: ".parts vs .repair: Selling The Piece or Fixing The Thing" } },
  { slug: "auction-vs-market", a: "auction", b: "market", title: { zh: ".auction 和 .market 怎么选：竞价成交与挂牌交易的分工", en: ".auction vs .market: Bidding Floor or Open Marketplace" } },
  { slug: "deals-vs-coupons", a: "deals", b: "coupons", title: { zh: ".deals 和 .coupons 怎么选：找便宜与发码的分工", en: ".deals vs .coupons: Deal Feeds or Code Distribution" } },
  { slug: "discount-vs-sale", a: "discount", b: "sale", title: { zh: ".discount 和 .sale 怎么选：常年折扣与档期特卖的分工", en: ".discount vs .sale: Everyday Low Prices or Event Markdowns" } },
  { slug: "furniture-vs-boutique", a: "furniture", b: "boutique", title: { zh: ".furniture 和 .boutique 怎么选：品类直给与精选气质的取舍", en: ".furniture vs .boutique: Category Precision or Curated Character" } },
  { slug: "lighting-vs-garden", a: "lighting", b: "garden", title: { zh: ".lighting 和 .garden 怎么选：庭院灯光生意的两个入口", en: ".lighting vs .garden: Two Doors Into the Outdoor-Lighting Trade" } },
  { slug: "lighting-vs-solar", a: "lighting", b: "solar", title: { zh: ".lighting 和 .solar 怎么选：太阳能灯生意站哪边", en: ".lighting vs .solar: Where a Solar-Lighting Business Belongs" } },
  { slug: "business-vs-company", a: "business", b: "company", title: { zh: ".business 和 .company 怎么选：报经营还是报主体", en: ".business vs .company: Naming the Trade or the Entity" } },
  { slug: "limited-vs-ltd", a: "limited", b: "ltd", title: { zh: ".limited 和 .ltd 怎么选：全拼正式感与缩写实用感", en: ".limited vs .ltd: Full Spelling vs the Working Abbreviation" } },
  { slug: "associates-vs-partners", a: "associates", b: "partners", title: { zh: ".associates 和 .partners 怎么选：字号传统与合伙关系", en: ".associates vs .partners: The Firm Name or the Relationship" } },
  { slug: "cheap-vs-discount", a: "cheap", b: "discount", title: { zh: ".cheap 和 .discount 怎么选：报价格标签还是报打折动作", en: ".cheap vs .discount: The Price Tag or the Markdown" } },
  { slug: "bargains-vs-deals", a: "bargains", b: "deals", title: { zh: ".bargains 和 .deals 怎么选：捡漏乐趣与交易促成", en: ".bargains vs .deals: The Thrill of the Find or the Transaction" } },
  { slug: "supplies-vs-supply", a: "supplies", b: "supply", title: { zh: ".supplies 和 .supply 怎么选：一件件耗材与供给概念", en: ".supplies vs .supply: The Items or the Provisioning" } },
  { slug: "camp-vs-courses", a: "camp", b: "courses", title: { zh: ".camp 和 .courses 怎么选：沉浸式集训与体系化课程", en: ".camp vs .courses: Immersive Cohorts or Structured Curriculum" } },
  { slug: "camera-vs-photography", a: "camera", b: "photography", title: { zh: ".camera 和 .photography 怎么选：器材设备与摄影手艺", en: ".camera vs .photography: The Gear or the Craft" } },
  { slug: "diamonds-vs-jewelry", a: "diamonds", b: "jewelry", title: { zh: ".diamonds 和 .jewelry 怎么选：单一品类锋利度与全品类覆盖", en: ".diamonds vs .jewelry: Category Sharpness or Full-Range Coverage" } },
  { slug: "theater-vs-show", a: "theater", b: "show", title: { zh: ".theater 和 .show 怎么选：剧场场所感与泛演出内容", en: ".theater vs .show: The Venue or the Program" } },
  { slug: "accountants-vs-tax", a: "accountants", b: "tax", title: { zh: ".accountants 和 .tax 怎么选：职业身份与业务主题", en: ".accountants vs .tax: The Profession or the Subject" } },
  { slug: "engineer-vs-engineering", a: "engineer", b: "engineering", title: { zh: ".engineer 和 .engineering 怎么选：个人身份与公司生意", en: ".engineer vs .engineering: The Person or the Practice" } },
  { slug: "villas-vs-rentals", a: "villas", b: "rentals", title: { zh: ".villas 和 .rentals 怎么选：产品定位与交易动作", en: ".villas vs .rentals: The Product or the Transaction" } },
  { slug: "cruises-vs-travel", a: "cruises", b: "travel", title: { zh: ".cruises 和 .travel 怎么选：垂直锋利与行业正统", en: ".cruises vs .travel: Vertical Edge or Industry Credential" } },
  { slug: "voyage-vs-tours", a: "voyage", b: "tours", title: { zh: ".voyage 和 .tours 怎么选：叙事意象与产品直给", en: ".voyage vs .tours: The Narrative or the Product" } },
  { slug: "limo-vs-taxi", a: "limo", b: "taxi", title: { zh: ".limo 和 .taxi 怎么选：礼宾预约与即叫即走", en: ".limo vs .taxi: Booked Chauffeur or Street Hail" } },
  { slug: "tickets-vs-events", a: "tickets", b: "events", title: { zh: ".tickets 和 .events 怎么选：交易入口与活动本身", en: ".tickets vs .events: The Checkout or the Occasion" } },
  { slug: "flowers-vs-florist", a: "flowers", b: "florist", title: { zh: ".flowers 和 .florist 怎么选：商品直给与职业身份", en: ".flowers vs .florist: The Product or the Profession" } },
  { slug: "beer-vs-pub", a: "beer", b: "pub", title: { zh: ".beer 和 .pub 怎么选：品类直给与场所双关", en: ".beer vs .pub: The Category or the Venue" } },
  { slug: "pub-vs-bar", a: "pub", b: "bar", title: { zh: ".pub 和 .bar 怎么选：英式烟火气与泛酒吧通吃", en: ".pub vs .bar: Tavern Warmth or Catch-All Nightlife" } },
  { slug: "spa-vs-salon", a: "spa", b: "salon", title: { zh: ".spa 和 .salon 怎么选：康养链条与美业门店", en: ".spa vs .salon: The Wellness Chain or the Beauty Shop" } },
  { slug: "food-vs-restaurant", a: "food", b: "restaurant", title: { zh: ".food 和 .restaurant 怎么选：品类总词与门店直给", en: ".food vs .restaurant: The Umbrella or the Storefront" } },
  { slug: "attorney-vs-lawyer", a: "attorney", b: "lawyer", title: { zh: ".attorney 和 .lawyer 怎么选：美式正式与全球通称", en: ".attorney vs .lawyer: The Formal American or the Global Word" } },
  { slug: "dentist-vs-dental", a: "dentist", b: "dental", title: { zh: ".dentist 和 .dental 怎么选：职业身份与行业大词", en: ".dentist vs .dental: The Professional or the Industry" } },
  { slug: "clothing-vs-fashion", a: "clothing", b: "fashion", title: { zh: ".clothing 和 .fashion 怎么选：卖衣服的品类与说时尚的概念", en: ".clothing vs .fashion: The Garments or the Concept" } },
  { slug: "cooking-vs-recipes", a: "cooking", b: "recipes", title: { zh: ".cooking 和 .recipes 怎么选：做菜这件事与菜谱这份交付", en: ".cooking vs .recipes: The Act or the Deliverable" } },
  { slug: "gift-vs-gifts", a: "gift", b: "gifts", title: { zh: ".gift 和 .gifts 怎么选：单数动词感与复数商品感", en: ".gift vs .gifts: The Verb or the Shelf" } },
  { slug: "party-vs-events", a: "party", b: "events", title: { zh: ".party 和 .events 怎么选：热闹直给与全场景专业词", en: ".party vs .events: The Vibe or the Industry" } },
  { slug: "fishing-vs-boats", a: "fishing", b: "boats", title: { zh: ".fishing 和 .boats 怎么选：钓鱼这件事与船这台设备", en: ".fishing vs .boats: The Activity or the Vessel" } },
  { slug: "horse-vs-pet", a: "horse", b: "pet", title: { zh: ".horse 和 .pet 怎么选：马术垂类与宠物大类", en: ".horse vs .pet: The Vertical Blade or the Industry Umbrella" } },
  { slug: "singles-vs-dating", a: "singles", b: "dating", title: { zh: ".singles 和 .dating 怎么选：人群画像与行业产品", en: ".singles vs .dating: The Demographic or the Industry" } },
  { slug: "dating-vs-love", a: "dating", b: "love", title: { zh: ".dating 和 .love 怎么选：行业后缀与情感大词", en: ".dating vs .love: The Industry Suffix or the Emotion Word" } },
  { slug: "luxury-vs-vip", a: "luxury", b: "vip", title: { zh: ".luxury 和 .vip 怎么选：奢侈定位与会员身份", en: ".luxury vs .vip: The Positioning or the Membership" } },
  { slug: "organic-vs-bio", a: "organic", b: "bio", title: { zh: ".organic 和 .bio 怎么选：有机品类标准与一词双关", en: ".organic vs .bio: The Category Standard or the Continental Shorthand" } },
  { slug: "tattoo-vs-ink", a: "tattoo", b: "ink", title: { zh: ".tattoo 和 .ink 怎么选：行业直给与意象留白", en: ".tattoo vs .ink: Industry-Direct or Imagery With Room" } },
  { slug: "casa-vs-house", a: "casa", b: "house", title: { zh: ".casa 和 .house 怎么选：西语的家与英语的房子", en: ".casa vs .house: Home in Spanish or English" } },
  { slug: "casino-vs-bet", a: "casino", b: "bet", title: { zh: ".casino 和 .bet 怎么选：场馆招牌与动作词", en: ".casino vs .bet: The Venue Sign or the Action Word" } },
  { slug: "bet-vs-poker", a: "bet", b: "poker", title: { zh: ".bet 和 .poker 怎么选：泛博彩动作与单一牌种", en: ".bet vs .poker: The Broad Action or the Single Game" } },
  { slug: "poker-vs-games", a: "poker", b: "games", title: { zh: ".poker 和 .games 怎么选：单一牌种与泛游戏行业", en: ".poker vs .games: One Card Game or the Whole Industry" } },
  { slug: "vodka-vs-wine", a: "vodka", b: "wine", title: { zh: ".vodka 和 .wine 怎么选：烈酒单品与酒文化大类", en: ".vodka vs .wine: The Single Spirit or the Whole Cellar" } },
  { slug: "futbol-vs-soccer", a: "futbol", b: "soccer", title: { zh: ".futbol 和 .soccer 怎么选：西语的足球与北美的足球", en: ".futbol vs .soccer: The Spanish Game or the North American Name" } },
  { slug: "moda-vs-fashion", a: "moda", b: "fashion", title: { zh: ".moda 和 .fashion 怎么选：西语的时尚与英语的时尚", en: ".moda vs .fashion: Style in Spanish or English" } },
  { slug: "basketball-vs-team", a: "basketball", b: "team", title: { zh: ".basketball 和 .team 怎么选：单项官方域与万队通用牌", en: ".basketball vs .team: The Sport's Official Badge or Any Squad's Banner" } },
  { slug: "rugby-vs-football", a: "rugby", b: "football", title: { zh: ".rugby 和 .football 怎么选：橄榄球与足球各说各的", en: ".rugby vs .football: Each Sport Under Its Own Banner" } },
  { slug: "cricket-vs-club", a: "cricket", b: "club", title: { zh: ".cricket 和 .club 怎么选：板球品类与社群归属的分工", en: ".cricket vs .club: The Sport's Category or The Member Circle" } },
  { slug: "fish-vs-fishing", a: "fish", b: "fishing", title: { zh: ".fish 和 .fishing 怎么选：水产品类与钓鱼活动的分工", en: ".fish vs .fishing: The Category or The Activity" } },
  { slug: "fan-vs-club", a: "fan", b: "club", title: { zh: ".fan 和 .club 怎么选：粉丝身份与社群组织的分工", en: ".fan vs .club: The Fan's Identity or The Member Organization" } },
  { slug: "win-vs-bet", a: "win", b: "bet", title: { zh: ".win 和 .bet 怎么选：赢的结果与下注的动作", en: ".win vs .bet: The Outcome or The Action" } },
  { slug: "wang-vs-com", a: "wang", b: "com", title: { zh: ".wang 和 .com 怎么选：说中文的后缀与全球默认值", en: ".wang vs .com: The Chinese-Speaking Suffix or The Global Default" } },
  { slug: "day-vs-today", a: "day", b: "today", title: { zh: ".day 和 .today 怎么选：日子的名词与今天的号角", en: ".day vs .today: The Named Day or The Call of Now" } },
  { slug: "meme-vs-fun", a: "meme", b: "fun", title: { zh: ".meme 和 .fun 怎么选：梗文化身份牌与泛娱乐通配符", en: ".meme vs .fun: The Meme-Culture Badge or The Entertainment Wildcard" } },
  { slug: "quest-vs-games", a: "quest", b: "games", title: { zh: ".quest 和 .games 怎么选：冒险的过程与游戏的行业", en: ".quest vs .games: The Journey or The Industry" } },
  { slug: "kids-vs-family", a: "kids", b: "family", title: { zh: ".kids 和 .family 怎么选：儿童受众与全家归属的分工", en: ".kids vs .family: The Child Audience or The Whole Household" } },
  { slug: "foundation-vs-org", a: "foundation", b: "org", title: { zh: ".foundation 和 .org 怎么选：基金会的全称与非营利的正统", en: ".foundation vs .org: The Institution's Full Name or The Nonprofit Standard" } },
  { slug: "wang-vs-cn", a: "wang", b: "cn", title: { zh: ".wang 和 .cn 怎么选：说中文的通用后缀与国家域名的正统", en: ".wang vs .cn: The Chinese-Speaking Generic or The Country Code" } },
  { slug: "day-vs-life", a: "day", b: "life", title: { zh: ".day 和 .life 怎么选：一天的刻度与生活的全景", en: ".day vs .life: The Single Day or The Whole Life" } },
  { slug: "meme-vs-lol", a: "meme", b: "lol", title: { zh: ".meme 和 .lol 怎么选：梗的名词与笑的动词", en: ".meme vs .lol: The Meme Itself or The Laugh It Gets" } },
  { slug: "quest-vs-fun", a: "quest", b: "fun", title: { zh: ".quest 和 .fun 怎么选：冒险的叙事与好玩的气质", en: ".quest vs .fun: The Adventure Story or The Playful Vibe" } },
  { slug: "kids-vs-baby", a: "kids", b: "baby", title: { zh: ".kids 和 .baby 怎么选：儿童内容的承诺与母婴品类的招牌", en: ".kids vs .baby: The Child-Safe Promise or The Baby-Market Sign" } },
  { slug: "win-vs-vip", a: "win", b: "vip", title: { zh: ".win 和 .vip 怎么选：赢的情绪与会员的身份", en: ".win vs .vip: The Thrill of Winning or The Status of Membership" } },
  { slug: "bond-vs-finance", a: "bond", b: "finance", title: { zh: ".bond 和 .finance 怎么选：纽带的双关与金融的行业词", en: ".bond vs .finance: The Double-Meaning Tie or The Industry Word" } },
  { slug: "sbs-vs-xyz", a: "sbs", b: "xyz", title: { zh: ".sbs 和 .xyz 怎么选：留白的缩写与反叛的亚文化", en: ".sbs vs .xyz: The Blank Abbreviation or The Subculture Flag" } },
  { slug: "cyou-vs-fun", a: "cyou", b: "fun", title: { zh: ".cyou 和 .fun 怎么选：邀约的语气与好玩的气氛", en: ".cyou vs .fun: The Invitation or The Vibe" } },
  { slug: "monster-vs-games", a: "monster", b: "games", title: { zh: ".monster 和 .games 怎么选：猛的气质与行业的品类", en: ".monster vs .games: The Attitude or The Industry" } },
  { slug: "pics-vs-photos", a: "pics", b: "photos", title: { zh: ".pics 和 .photos 怎么选：随手的口语与交付的正装", en: ".pics vs .photos: The Casual Shorthand or The Delivery Front" } },
  { slug: "mobi-vs-app", a: "mobi", b: "app", title: { zh: ".mobi 和 .app 怎么选：移动的场景与应用的形态", en: ".mobi vs .app: The Mobile Context or The Application Form" } },
  { slug: "asia-vs-global", a: "asia", b: "global", title: { zh: ".asia 和 .global 怎么选：区域的官方后缀与全球的宣言", en: ".asia vs .global: The Official Region or The Worldwide Claim" } },
  { slug: "buzz-vs-promo", a: "buzz", b: "promo", title: { zh: ".buzz 和 .promo 怎么选：话题的热度与促销的动作", en: ".buzz vs .promo: The Attention Play or The Conversion Play" } },
  { slug: "fans-vs-fan", a: "fans", b: "fan", title: { zh: ".fans 和 .fan 怎么选：粉丝群体的复数与粉丝身份的单数", en: ".fans vs .fan: The Plural Crowd or The Singular Badge" } },
  { slug: "place-vs-space", a: "place", b: "space", title: { zh: ".place 和 .space 怎么选：具体的场所与抽象的天地", en: ".place vs .space: The Concrete Venue or The Open Room" } },
  { slug: "report-vs-news", a: "report", b: "news", title: { zh: ".report 和 .news 怎么选：深度的报告与时效的资讯", en: ".report vs .news: The Deep Dive or The Fast Feed" } },
  { slug: "town-vs-city", a: "town", b: "city", title: { zh: ".town 和 .city 怎么选：小镇的烟火气与城市的大尺度", en: ".town vs .city: The Cozy Scale or The Urban Scale" } },
  { slug: "shopping-vs-shop", a: "shopping", b: "shop", title: { zh: ".shopping 和 .shop 怎么选：逛的体验与店的门面", en: ".shopping vs .shop: The Browsing Experience or The Storefront" } },
  { slug: "graphics-vs-design", a: "graphics", b: "design", title: { zh: ".graphics 和 .design 怎么选：做图的工种与设计的学科", en: ".graphics vs .design: The Visual Trade or The Whole Discipline" } },
  { slug: "glass-vs-art", a: "glass", b: "art", title: { zh: ".glass 和 .art 怎么选：材料的行业与创作的身份", en: ".glass vs .art: The Material Trade or The Creative Identity" } },
  { slug: "vision-vs-care", a: "vision", b: "care", title: { zh: ".vision 和 .care 怎么选：眼睛的专科与照护的温度", en: ".vision vs .care: The Eye Specialty or The Caring Touch" } },
  { slug: "tires-vs-autos", a: "tires", b: "autos", title: { zh: ".tires 和 .autos 怎么选：单一品类与汽车全域", en: ".tires vs .autos: The Single Category or The Whole Trade" } },
  { slug: "surgery-vs-clinic", a: "surgery", b: "clinic", title: { zh: ".surgery 和 .clinic 怎么选：手术的专科纵深与门诊的机构门面", en: ".surgery vs .clinic: The Surgical Depth or The Outpatient Front" } },
  { slug: "domains-vs-tools", a: "domains", b: "tools", title: { zh: ".domains 和 .tools 怎么选：域名行业的自指与通用工具的口径", en: ".domains vs .tools: The Trade's Own Name or The Generic Toolbox" } },
  { slug: "college-vs-academy", a: "college", b: "academy", title: { zh: ".college 和 .academy 怎么选：学院的机构身份与训练营的技能口径", en: ".college vs .academy: The Institution or The Bootcamp" } },
  { slug: "actor-vs-studio", a: "actor", b: "studio", title: { zh: ".actor 和 .studio 怎么选：表演者的个人名片与创作团队的工作室招牌", en: ".actor vs .studio: The Performer's Card or The Team's Signboard" } },
  { slug: "immo-vs-estate", a: "immo", b: "estate", title: { zh: ".immo 和 .estate 怎么选：欧陆行业词与英语地产的门面", en: ".immo vs .estate: The Continental Trade Word or The English Front" } },
  { slug: "vin-vs-wine", a: "vin", b: "wine", title: { zh: ".vin 和 .wine 怎么选：法语酒标的格调与英语市场的直白", en: ".vin vs .wine: The French Label or The English Shelf" } },
  { slug: "university-vs-education", a: "university", b: "education", title: { zh: ".university 和 .education 怎么选：大学的机构层级与教育的行业全域", en: ".university vs .education: The Institutional Tier or The Whole Industry" } },
  { slug: "hospital-vs-clinic", a: "hospital", b: "clinic", title: { zh: ".hospital 和 .clinic 怎么选：住院机构的正门与门诊生意的门牌", en: ".hospital vs .clinic: The Inpatient Gate or The Outpatient Sign" } },
  { slug: "gmbh-vs-company", a: "gmbh", b: "company", title: { zh: ".gmbh 和 .company 怎么选：德语区的注册名与泛公司的通用牌", en: ".gmbh vs .company: The German Register Name or The Generic Card" } },
  { slug: "condos-vs-apartments", a: "condos", b: "apartments", title: { zh: ".condos 和 .apartments 怎么选：产权公寓的售楼处与租赁公寓的招租页", en: ".condos vs .apartments: The Sales Office or The Rental Sign" } },
  { slug: "rehab-vs-care", a: "rehab", b: "care", title: { zh: ".rehab 和 .care 怎么选：康复的过程动词与照护的关系名词", en: ".rehab vs .care: The Recovery Verb or The Caring Noun" } },
  { slug: "nyc-vs-us", a: "nyc", b: "us", title: { zh: ".nyc 和 .us 怎么选：纽约的城市门牌与全美的国家后缀", en: ".nyc vs .us: The City Nameplate or The National Suffix" } },
  { slug: "london-vs-uk", a: "london", b: "uk", title: { zh: ".london 和 .uk 怎么选：伦敦的城市招牌与英国的全国信任", en: ".london vs .uk: The City Signboard or The National Trust" } },
  { slug: "tokyo-vs-asia", a: "tokyo", b: "asia", title: { zh: ".tokyo 和 .asia 怎么选：东京的城市门牌与亚太的区域口径", en: ".tokyo vs .asia: The City Nameplate or The Regional Scope" } },
  { slug: "miami-vs-nyc", a: "miami", b: "nyc", title: { zh: ".miami 和 .nyc 怎么选：两座美国名城的门牌之争", en: ".miami vs .nyc: A Tale of Two City Nameplates" } },
  { slug: "boston-vs-city", a: "boston", b: "city", title: { zh: ".boston 和 .city 怎么选：具体的城市门牌与泛化的城市语义", en: ".boston vs .city: The Specific Nameplate or The Generic City Word" } },
  { slug: "healthcare-vs-health", a: "healthcare", b: "health", title: { zh: ".healthcare 和 .health 怎么选：行业级声明与泛健康赛道", en: ".healthcare vs .health: The Industry Statement or The Wellness Umbrella" } },
  { slug: "abogado-vs-lawyer", a: "abogado", b: "lawyer", title: { zh: ".abogado 和 .lawyer 怎么选：西语客户与英语客户的执业门牌", en: ".abogado vs .lawyer: The Practice Nameplate in Spanish or English" } },
  { slug: "kaufen-vs-shop", a: "kaufen", b: "shop", title: { zh: ".kaufen 和 .shop 怎么选：德语区的购买动词与全球的店铺门面", en: ".kaufen vs .shop: The German Buy Verb or The Global Storefront" } },
  { slug: "berlin-vs-city", a: "berlin", b: "city", title: { zh: ".berlin 和 .city 怎么选：柏林门牌与通用城市词的分工", en: ".berlin vs .city: The Berlin Nameplate or The Generic City Word" } },
  { slug: "paris-vs-london", a: "paris", b: "london", title: { zh: ".paris 和 .london 怎么选：两座欧洲之都的城市门牌", en: ".paris vs .london: Two European Capitals' City Nameplates" } },
  { slug: "amsterdam-vs-berlin", a: "amsterdam", b: "berlin", title: { zh: ".amsterdam 和 .berlin 怎么选：两座创意之都的城市后缀", en: ".amsterdam vs .berlin: Two Creative Capitals' City Suffixes" } },
  { slug: "vegas-vs-casino", a: "vegas", b: "casino", title: { zh: ".vegas 和 .casino 怎么选：城市门牌与博彩品类的分工", en: ".vegas vs .casino: The City Nameplate or The Gambling Category" } },
  { slug: "immobilien-vs-immo", a: "immobilien", b: "immo", title: { zh: ".immobilien 和 .immo 怎么选：德语房产全称与缩写的取舍", en: ".immobilien vs .immo: The German Full Word or The Short Abbreviation" } },
  { slug: "tienda-vs-shop", a: "tienda", b: "shop", title: { zh: ".tienda 和 .shop 怎么选：西语店铺词与全球店铺门面", en: ".tienda vs .shop: The Spanish Store Word or The Global Storefront" } },
  { slug: "de-vs-com", a: "de", b: "com", title: { zh: ".de 和 .com 怎么选：德国本地信任与全球默认值的对比", en: ".de vs .com: German Local Trust vs the Global Default" } },
  { slug: "de-vs-eu", a: "de", b: "eu", title: { zh: ".de 和 .eu 怎么选：单一德国市场与泛欧定位的对比", en: ".de vs .eu: One German Market or the Pan-European Claim" } },
  { slug: "ca-vs-us", a: "ca", b: "us", title: { zh: ".ca 和 .us 怎么选：加拿大与美国两个本土信号的对比", en: ".ca vs .us: Two North American Local Signals Compared" } },
  { slug: "au-vs-com", a: "au", b: "com", title: { zh: ".au 和 .com 怎么选：澳洲本地信任与全球默认值的对比", en: ".au vs .com: Australian Local Trust vs the Global Default" } },
  { slug: "jp-vs-cn", a: "jp", b: "cn", title: { zh: ".jp 和 .cn 怎么选：日本与中国两大东亚市场入口的对比", en: ".jp vs .cn: Japan or China — Two East Asian Market Entrances" } },
  { slug: "sg-vs-asia", a: "sg", b: "asia", title: { zh: ".sg 和 .asia 怎么选：新加坡枢纽信号与亚太区域后缀的对比", en: ".sg vs .asia: The Singapore Hub Signal or the Asia-Pacific Region" } },
  { slug: "fr-vs-com", a: "fr", b: "com", title: { zh: ".fr 和 .com 怎么选：法国本地信任与全球默认值的对比", en: ".fr vs .com: French Local Trust vs the Global Default" } },
  { slug: "it-vs-de", a: "it", b: "de", title: { zh: ".it 和 .de 怎么选：意大利与德国两大本地市场的对比", en: ".it vs .de: Italy or Germany — Two Prime Local Markets Compared" } },
  { slug: "es-vs-eu", a: "es", b: "eu", title: { zh: ".es 和 .eu 怎么选：西班牙单一市场与泛欧覆盖的对比", en: ".es vs .eu: Spain's Home Market or Pan-European Coverage" } },
  { slug: "nl-vs-de", a: "nl", b: "de", title: { zh: ".nl 和 .de 怎么选：荷兰枢纽与德国腹地两大 ccTLD 的对比", en: ".nl vs .de: The Dutch Hub or the German Heartland" } },
  { slug: "kr-vs-jp", a: "kr", b: "jp", title: { zh: ".kr 和 .jp 怎么选：韩国与日本两大东亚市场的对比", en: ".kr vs .jp: Korea or Japan — Two East Asian Markets Compared" } },
  { slug: "hk-vs-sg", a: "hk", b: "sg", title: { zh: ".hk 和 .sg 怎么选：香港与新加坡两大亚洲枢纽的对比", en: ".hk vs .sg: Hong Kong or Singapore — Two Asian Hubs Compared" } },
  { slug: "ch-vs-de", a: "ch", b: "de", title: { zh: ".ch 和 .de 怎么选：瑞士品质与德国腹地两大德语区 ccTLD 的对比", en: ".ch vs .de: Swiss Quality or the German Heartland" } },
  { slug: "at-vs-de", a: "at", b: "de", title: { zh: ".at 和 .de 怎么选：奥地利本地与德国腹地的德语区对比", en: ".at vs .de: Austria's Home Turf or the German Heartland" } },
  { slug: "be-vs-nl", a: "be", b: "nl", title: { zh: ".be 和 .nl 怎么选：比利时与荷兰两大低地国家 ccTLD 的对比", en: ".be vs .nl: Belgium or the Netherlands — Two Low Countries Compared" } },
  { slug: "se-vs-com", a: "se", b: "com", title: { zh: ".se 和 .com 怎么选：瑞典本地信任与全球默认后缀的对比", en: ".se vs .com: Swedish Local Trust or the Global Default" } },
  { slug: "pl-vs-eu", a: "pl", b: "eu", title: { zh: ".pl 和 .eu 怎么选：波兰单一市场与泛欧覆盖的对比", en: ".pl vs .eu: Poland's Home Market or Pan-European Coverage" } },
  { slug: "tw-vs-hk", a: "tw", b: "hk", title: { zh: ".tw 和 .hk 怎么选：台湾与香港两大繁中商圈的对比", en: ".tw vs .hk: Taiwan or Hong Kong — Two Traditional Chinese Markets Compared" } },
];
