/**
 * hub 索引页轻量数据 —— 由 scripts/gen-hub-index.mjs 从
 * tlds.ts / guides.ts / compares.ts 全文内容生成，请勿手改。
 * 内容源变更（新增/修改 TLD、行业指南、对比页）后运行 node scripts/gen-hub-index.mjs 重新生成；
 * CI/审计可用 --check 校验一致性。
 * 存在意义：hub 页组件只需一句话定位/标签/标题，引用本模块而非全文 chunk（R271 移动性能优化）；
 * 按 hub 分立三个文件，每个 hub 页只加载自己那份索引（R282 移动性能优化）。
 */
type Localized = { zh: string; en: string };

/** 行业指南索引（顺序与 GUIDE_LIST 一致）：slug + 双语标签 + 一句话定位 */
export const GUIDE_INDEX: { slug: string; label: Localized; oneLiner: Localized }[] = [
  { slug: "saas", label: { zh: "SaaS 工具", en: "SaaS tools" }, oneLiner: { zh: "SaaS 产品命名完整指南：动词化命名、合成词、隐喻词等 5 种思路。", en: "A complete SaaS naming guide: verb-able names, blends and metaphors." } },
  { slug: "ecommerce", label: { zh: "电商品牌", en: "E-commerce" }, oneLiner: { zh: "电商品牌命名指南：情绪词、创始人故事、品类词升维等 5 种思路。", en: "E-commerce naming guide: emotion-first words, founder stories, category elevation." } },
  { slug: "ai", label: { zh: "AI 产品", en: "AI products" }, oneLiner: { zh: "AI 产品命名指南：人格化、神话借词、去 AI 化命名等 5 种思路。", en: "AI product naming guide: persona names, mythic borrowings, the post-AI naming shift." } },
  { slug: "fintech", label: { zh: "金融科技", en: "Fintech" }, oneLiner: { zh: "金融科技命名指南：信任词根、去金融化、单音节力量词等 5 种思路。", en: "Fintech naming guide: trust-first roots, definancialized names." } },
  { slug: "pets", label: { zh: "宠物品牌", en: "Pet brands" }, oneLiner: { zh: "宠物品牌命名指南：拟声词、人宠双关、萌感音节等 5 种思路。", en: "Pet brand naming guide: onomatopoeia, body-part borrowing." } },
  { slug: "blog", label: { zh: "个人博客", en: "Blogs" }, oneLiner: { zh: "个人博客与内容站命名指南：真名策略、意象命名、栏目化命名等 5 种思路。", en: "Blog and content-site naming guide: real-name strategy, imagery names." } },
  { slug: "game", label: { zh: "游戏", en: "Games" }, oneLiner: { zh: "游戏命名指南：世界观词、动词感、.io 品类现象等 5 种思路。", en: "Game naming guide: worldbuilding roots, shoutability, the .io genre phenomenon." } },
  { slug: "edu", label: { zh: "教育产品", en: "Education" }, oneLiner: { zh: "教育科技命名指南：双重受众、成长隐喻、去说教化等 5 种思路。", en: "EdTech naming guide: the dual-audience balance, growth metaphors, de-schooled naming." } },
  { slug: "travel", label: { zh: "旅行", en: "Travel" }, oneLiner: { zh: "旅行品牌命名指南：目的地联想、动词化出发感、避开 travel 词根堆砌等思路。", en: "Travel naming guide: sell the imagination not the booking flow." } },
  { slug: "food", label: { zh: "餐饮美食", en: "Food & dining" }, oneLiner: { zh: "餐饮品牌命名指南：味觉通感、场景锚定、方言人情味等思路。", en: "F&B naming guide: taste synesthesia, scene anchoring, founder warmth." } },
  { slug: "fitness", label: { zh: "健身健康", en: "Fitness & health" }, oneLiner: { zh: "健身健康品牌命名指南：身份感命名、能量音节、避开说教词根等思路。", en: "Fitness naming guide: identity-badge names, energetic phonetics." } },
  { slug: "devtools", label: { zh: "开发者工具", en: "Dev tools" }, oneLiner: { zh: "开发者工具命名指南：CLI 友好、极客梗与神话词、避开 dev/code 堆砌等思路。", en: "Dev-tool naming guide: CLI-friendly names, mythology and in-jokes." } },
  { slug: "web3", label: { zh: "Web3 加密", en: "Web3 & crypto" }, oneLiner: { zh: "Web3/加密项目命名指南：协议感造词、去土狗化、跨文化预检等思路。", en: "Web3 naming guide: protocol-grade coinage, de-memeing your name." } },
  { slug: "agency", label: { zh: "咨询工作室", en: "Agencies & studios" }, oneLiner: { zh: "咨询/设计工作室命名指南：人名信誉、概念词、避开 studio 堆砌等思路。", en: "Agency naming guide: surname equity vs concept manifestos, classical roots." } },
  { slug: "photography", label: { zh: "摄影工作室", en: "Photography" }, oneLiner: { zh: "摄影工作室与摄影师个人品牌命名指南：光影意象、人名+工艺词、情绪词等思路。", en: "Photography naming guide: light-and-shadow roots, name-plus-craft structures." } },
  { slug: "podcast", label: { zh: "播客节目", en: "Podcasts" }, oneLiner: { zh: "播客与音频节目命名指南：口播测试、悬念式命名、双关梗等思路。", en: "Podcast naming guide: the spoken-intro test, intrigue-first names, format puns." } },
  { slug: "realestate", label: { zh: "房产家居", en: "Real estate" }, oneLiner: { zh: "房产与家居品牌命名指南：安家意象、专业信任词、本地深耕等思路。", en: "Real estate and home-brand naming guide: dwelling imagery, trust words." } },
  { slug: "health", label: { zh: "医疗健康", en: "Health" }, oneLiner: { zh: "医疗健康品牌命名指南：安心词根、科学感与温度的平衡、合规红线等思路。", en: "Health brand naming guide: reassurance roots, balancing science and warmth." } },
  { slug: "legal", label: { zh: "法律服务", en: "Legal" }, oneLiner: { zh: "律所与法律科技命名指南：权威词根、姓氏传统的现代化、法科技去精英化等思路。", en: "Law firm and legaltech naming guide: authority roots." } },
  { slug: "newsletter", label: { zh: "Newsletter", en: "Newsletters" }, oneLiner: { zh: "Newsletter 与订阅制内容命名指南：收件箱场景、承诺式命名、栏目感等思路。", en: "Newsletter naming guide: inbox-first thinking, promise-based names, reading rituals." } },
  { slug: "music", label: { zh: "音乐人", en: "Music & labels" }, oneLiner: { zh: "音乐人/厂牌命名指南：艺名造词、情绪词借用、声音意象等思路。", en: "Music naming guide: coined stage names, sonic imagery, mood-word grafts." } },
  { slug: "beauty", label: { zh: "美妆个护", en: "Beauty & care" }, oneLiner: { zh: "美妆个护品牌命名指南：质感词借用、成分/功效叙事、人名品牌等思路。", en: "Beauty brand naming guide: texture-word borrowing, ingredient-forward naming." } },
  { slug: "nonprofit", label: { zh: "公益组织", en: "Nonprofit" }, oneLiner: { zh: "公益/非营利命名指南：使命动词、受益人视角、去机构化等思路。", en: "Nonprofit naming guide: mission verbs, beneficiary-first naming." } },
  { slug: "parenting", label: { zh: "母婴亲子", en: "Parenting & baby" }, oneLiner: { zh: "母婴亲子品牌命名指南：叠音词、安全感词根、成长意象等思路，好名字拆解与推荐 TLD。", en: "Parenting brand naming guide: reduplication with a twist, safety-word roots." } },
  { slug: "hardware", label: { zh: "智能硬件", en: "Hardware & IoT" }, oneLiner: { zh: "智能硬件命名指南：母品牌+产品线结构、材质/物理词根、短音节原则。", en: "Hardware naming guide: parent-brand + product-line architecture." } },
  { slug: "security", label: { zh: "网络安全", en: "Cybersecurity" }, oneLiner: { zh: "网络安全命名指南：守护/威慑双路线、神话与军事词根、避免恐吓式命名。", en: "Cybersecurity naming guide: guardian vs." } },
  { slug: "creator", label: { zh: "视频创作者", en: "Creators" }, oneLiner: { zh: "视频创作者与自媒体命名指南：频道名 vs 真名、栏目化命名、跨平台一致性。", en: "Creator naming guide: real name vs." } },
  { slug: "freelance", label: { zh: "自由职业", en: "Freelancers" }, oneLiner: { zh: "自由职业与独立开发者命名指南：真名 vs 工作室名、报价单信任感、一人公司命名。", en: "Freelancer and indie-hacker naming guide: real name vs." } },
  { slug: "fashion", label: { zh: "服饰潮牌", en: "Fashion labels" }, oneLiner: { zh: "服饰与潮牌命名指南：创始人名、意象词、反叛词三条路线。", en: "Fashion and streetwear naming guide: founder names." } },
  { slug: "coffee", label: { zh: "咖啡茶饮", en: "Coffee & tea" }, oneLiner: { zh: "咖啡与茶饮品牌命名指南：场所感命名、风味词、地名与故事词根。", en: "Coffee and tea naming guide: place-feel naming, sensory anchors, story roots." } },
  { slug: "automotive", label: { zh: "汽车出行", en: "Automotive" }, oneLiner: { zh: "汽车与出行品牌命名指南：致敬式人名、自然力意象、字母数字车型体系。", en: "Automotive and mobility naming guide: tribute names, force-of-nature imagery." } },
  { slug: "community", label: { zh: "社区俱乐部", en: "Communities" }, oneLiner: { zh: "社区与会员俱乐部命名指南：身份标签命名、内部黑话、地名+Club 结构。", en: "Community and members-club naming guide: identity labels, gathering-place metaphors." } },
  { slug: "wedding", label: { zh: "婚庆策划", en: "Wedding planners" }, oneLiner: { zh: "婚庆策划命名指南：仪式感词根、时刻命名、双姓组合等 5 种思路。", en: "Wedding business naming guide: moment-based names, ceremony-word roots." } },
  { slug: "bnb", label: { zh: "民宿短租", en: "BnBs & stays" }, oneLiner: { zh: "民宿短租命名指南：在地词根、栖居隐喻、房东人格等 5 种思路。", en: "BnB and short-term rental naming guide: place-rooted words, dwelling metaphors." } },
  { slug: "courses", label: { zh: "在线课程", en: "Online courses" }, oneLiner: { zh: "在线课程与知识付费命名指南：结果承诺、方法论命名、师徒人格等 5 种思路。", en: "Online course and creator-education naming guide: outcome promises." } },
  { slug: "boardgame", label: { zh: "桌游工作室", en: "Board games" }, oneLiner: { zh: "桌游与游戏工作室命名指南：盒面法则、机制词根、世界观命名等 5 种思路。", en: "Board game and tabletop studio naming guide: the box-cover rule, mechanism roots." } },
  { slug: "outdoor", label: { zh: "户外露营", en: "Outdoor & camping" }, oneLiner: { zh: "户外露营品牌命名指南：地貌词根、天气与火、装备人格等 5 种思路。", en: "Outdoor and camping brand naming guide: landform proper nouns." } },
  { slug: "cleaning", label: { zh: "家政清洁", en: "Cleaning services" }, oneLiner: { zh: "家政清洁服务命名指南：焕新词根、信任人格、效率承诺等 5 种思路。", en: "Cleaning and home services naming guide: after-state words, trust personas." } },
  { slug: "marketing", label: { zh: "数字营销", en: "Digital marketing" }, oneLiner: { zh: "数字营销机构/MCN 命名指南：增长动词、结果承诺、反行话命名等 5 种思路。", en: "Marketing agency and creator-network naming guide: growth verbs, anti-jargon names." } },
  { slug: "therapy", label: { zh: "心理咨询", en: "Therapy & mental health" }, oneLiner: { zh: "心理咨询与心理健康服务命名指南：庇护意象、成长隐喻、去病耻化等 5 种思路。", en: "Therapy and mental-health naming guide: shelter imagery, growth metaphors." } },
  { slug: "resale", label: { zh: "二手循环", en: "Resale & recommerce" }, oneLiner: { zh: "二手交易/循环经济品牌命名指南：再生词根、寻宝感、价值观词等 5 种思路。", en: "Resale and circular-economy naming guide: re- roots, treasure-hunt framing." } },
  { slug: "recruiting", label: { zh: "招聘人力", en: "Recruiting & HR" }, oneLiner: { zh: "招聘平台/HR SaaS 命名指南：机遇词根、连接隐喻、效率承诺等 5 种思路。", en: "Recruiting platform and HR SaaS naming guide: opportunity roots." } },
  { slug: "eldercare", label: { zh: "养老服务", en: "Senior care" }, oneLiner: { zh: "养老服务与银发经济命名指南：尊严词根、家园意象、双代际沟通等 5 种思路。", en: "Senior care and aging-economy naming guide: dignity roots, home imagery." } },
  { slug: "logistics", label: { zh: "物流货运", en: "Logistics & freight" }, oneLiner: { zh: "物流/货运/跨境供应链命名指南：速度词根、可靠承诺、网络隐喻等 5 种思路。", en: "Logistics, freight and supply-chain naming guide: speed roots, reliability promises." } },
  { slug: "agent", label: { zh: "AI 智能体", en: "AI agents" }, oneLiner: { zh: "AI 智能体/Agent 应用命名指南：拟人化命名、能力动词、协作隐喻等 5 种思路。", en: "AI agent naming guide: human-like names, delegation verbs, coworker metaphors." } },
  { slug: "crossborder", label: { zh: "跨境电商", en: "Cross-border e-commerce" }, oneLiner: { zh: "跨境电商/出海品牌命名指南：无国界造词、多语言避雷、发音全球化等 5 种思路。", en: "Cross-border and global DTC naming guide: borderless coinages." } },
  { slug: "escaperoom", label: { zh: "剧本杀密室", en: "Escape rooms" }, oneLiner: { zh: "剧本杀/密室逃脱/沉浸式娱乐命名指南：悬念词根、世界观命名、组局口播测试等 5 种思路。", en: "Escape room and immersive entertainment naming guide: mystery roots." } },
  { slug: "bakery", label: { zh: "烘焙甜品", en: "Bakeries & desserts" }, oneLiner: { zh: "烘焙/甜品/私房蛋糕命名指南：通感词根、手作叙事、包装上镜测试等 5 种思路。", en: "Bakery and dessert naming guide: synesthetic roots, maker stories, the gift-box test." } },
  { slug: "bookstore", label: { zh: "书店出版", en: "Bookstores & publishing" }, oneLiner: { zh: "书店/独立出版/读书社群命名指南：文学出处、空间意象、书脊测试等 5 种思路。", en: "Bookstore and independent publishing naming guide: literary provenance." } },
  { slug: "florist", label: { zh: "花店花艺", en: "Florists" }, oneLiner: { zh: "花店/花艺工作室/订阅鲜花命名指南：花语词根、诗意意象、贺卡署名测试等 5 种思路。", en: "Florist and floral design naming guide: botanical roots, poetic imagery." } },
  { slug: "interior", label: { zh: "装修设计", en: "Interior & renovation" }, oneLiner: { zh: "装修公司/室内设计工作室命名指南：空间意象、材质词根、业主转述测试等 5 种思路。", en: "Interior design and renovation naming guide: spatial imagery, material roots." } },
  { slug: "studyabroad", label: { zh: "留学教育", en: "Study abroad" }, oneLiner: { zh: "留学中介/国际教育/语培机构命名指南：桥梁意象、目的地词根、双客户测试等 5 种思路。", en: "Study abroad and international education naming guide: journey imagery." } },
  { slug: "usedcar", label: { zh: "二手车", en: "Used cars" }, oneLiner: { zh: "二手车电商/车行/检测服务命名指南：信任词根、透明意象、砍价场景测试等 5 种思路。", en: "Used car marketplace, dealership and inspection naming guide: trust roots." } },
  { slug: "insurance", label: { zh: "保险经纪", en: "Insurance" }, oneLiner: { zh: "保险经纪/保险科技/代理人团队命名指南：庇护意象、确定性词根、理赔场景测试等 5 种思路。", en: "Insurance brokerage and insurtech naming guide: shelter imagery, certainty roots." } },
  { slug: "farm", label: { zh: "农场生鲜", en: "Farms & fresh food" }, oneLiner: { zh: "农场/生鲜电商/农产品品牌命名指南：土地意象、时令词根、产地故事等 5 种思路。", en: "Farm, fresh produce and CSA naming guide: land imagery, harvest roots." } },
  { slug: "barber", label: { zh: "美发理容", en: "Barbershops & salons" }, oneLiner: { zh: "理发店/美发沙龙/男士理容品牌命名指南：手艺词根、场所感命名、熟客转述测试等 5 种思路。", en: "Barbershop and hair salon naming guide: craft roots, place-based naming." } },
  { slug: "yoga", label: { zh: "瑜伽普拉提", en: "Yoga & Pilates" }, oneLiner: { zh: "瑜伽馆/普拉提工作室命名指南：身心词根、空间感命名、会员转述测试等 5 种思路。", en: "Yoga and Pilates studio naming guide: breath-and-balance roots, space-first naming." } },
  { slug: "vet", label: { zh: "宠物医院", en: "Vet clinics" }, oneLiner: { zh: "宠物医院/动物诊所命名指南：安心词根、医者人名、深夜急诊测试等 5 种思路。", en: "Veterinary clinic and animal hospital naming guide: reassurance roots." } },
  { slug: "esports", label: { zh: "电竞战队", en: "Esports teams" }, oneLiner: { zh: "电竞战队/电竞俱乐部命名指南：战意词根、缩写设计、解说喊名测试等 5 种思路。", en: "Esports team and gaming org naming guide: battle roots, abbreviation-first design." } },
  { slug: "drone", label: { zh: "无人机航拍", en: "Drone & aerial" }, oneLiner: { zh: "无人机航拍工作室/飞行服务命名指南：视角词根、飞行意象、片尾署名测试等 5 种思路。", en: "Drone services and aerial photography naming guide: vantage-point roots." } },
  { slug: "hanfu", label: { zh: "汉服国潮", en: "Hanfu & guochao" }, oneLiner: { zh: "汉服/国潮品牌命名指南：古典词重组、诗词化用、出圈度平衡等 5 种思路。", en: "Hanfu and China-chic (guochao) brand naming guide: classical-word remixing." } },
  { slug: "dental", label: { zh: "口腔诊所", en: "Dental clinics" }, oneLiner: { zh: "口腔诊所/牙科品牌命名指南：安心词根、微笑意象、恐惧中和测试等 5 种思路。", en: "Dental clinic and orthodontics naming guide: smile-and-calm roots." } },
  { slug: "accounting", label: { zh: "会计财税", en: "Accounting & tax" }, oneLiner: { zh: "会计财税品牌命名指南：稳健词根、数字联想、合伙人姓氏结构等 5 种思路。", en: "Accounting and tax brand naming guide: trust-and-rigor roots." } },
  { slug: "livestream", label: { zh: "直播电商", en: "Livestream commerce" }, oneLiner: { zh: "直播电商与主播 IP 命名指南：口播友好测试、人设词根、场景词嫁接等 5 种思路。", en: "Livestream commerce naming guide: shout-out friendly tests, persona roots." } },
  { slug: "translation", label: { zh: "翻译本地化", en: "Translation & localization" }, oneLiner: { zh: "翻译与本地化品牌命名指南：跨语言可读测试、桥梁意象、词根国际化等 5 种思路。", en: "Translation and localization naming guide: cross-language readability tests." } },
  { slug: "gardening", label: { zh: "园艺绿植", en: "Gardening & plants" }, oneLiner: { zh: "园艺绿植品牌命名指南：生长意象、治愈系词根、节气花时等 5 种思路。", en: "Gardening and plant brand naming guide: growth imagery, kill-proof reassurance roots." } },
  { slug: "coworking", label: { zh: "联合办公", en: "Coworking spaces" }, oneLiner: { zh: "联合办公与共享空间命名指南：社群归属词根、空间意象、专业与活力平衡等 5 种思路。", en: "Coworking and shared space naming guide: belonging roots, place imagery." } },
  { slug: "solar", label: { zh: "光伏新能源", en: "Solar & clean energy" }, oneLiner: { zh: "光伏与新能源品牌命名指南：光与太阳意象、可靠承诺词根、科技与环保平衡等 5 种思路。", en: "Solar and clean energy naming guide: sun imagery with a second root." } },
  { slug: "coach", label: { zh: "健身私教", en: "Personal training" }, oneLiner: { zh: "健身私教与私教工作室命名指南：教练人名背书、成果词根、社群口号化等 5 种思路。", en: "Personal trainer and PT studio naming guide: coach-name trust, outcome roots." } },
  { slug: "codingschool", label: { zh: "编程培训", en: "Coding bootcamps" }, oneLiner: { zh: "编程培训与少儿编程机构命名指南：造物动词、去恐惧化、职业结果词根等 5 种思路。", en: "Coding bootcamp and kids-coding naming guide: maker verbs, de-fearing the category." } },
  { slug: "jewelry", label: { zh: "珠宝首饰", en: "Jewelry" }, oneLiner: { zh: "珠宝首饰品牌命名指南：创始人姓氏、神话借词、日常轻奢词根等 5 种思路。", en: "Jewelry brand naming guide: founder surnames, mythic borrowings." } },
  { slug: "toys", label: { zh: "玩具品牌", en: "Toy brands" }, oneLiner: { zh: "玩具与潮玩品牌命名指南：欢乐造词、双客群兼容、IP 延展性等 5 种思路。", en: "Toy and designer-toy naming guide: joyful coinages, dual-audience names, IP headroom." } },
  { slug: "brewery", label: { zh: "精酿酒饮", en: "Craft beer & drinks" }, oneLiner: { zh: "精酿啤酒与新酒饮品牌命名指南：反叛态度词、在地文化梗、酒标视觉词等 5 种思路。", en: "Craft beer and new-drinks naming guide: attitude words, local in-jokes." } },
  { slug: "furniture", label: { zh: "家具品牌", en: "Furniture" }, oneLiner: { zh: "家具与家居品牌命名指南：栖居感词根、材质工艺词、设计师姓氏等 5 种思路。", en: "Furniture and home brand naming guide: dwelling roots, material and craft words." } },
  { slug: "crossfit", label: { zh: "CrossFit 综合体能", en: "CrossFit & functional fitness" }, oneLiner: { zh: "CrossFit/综合体能馆命名指南：力量词根、部落感命名、白板喊名测试等 5 种思路。", en: "CrossFit box and functional fitness gym naming guide: strength roots, tribe totems." } },
  { slug: "language", label: { zh: "语言学习", en: "Language learning" }, oneLiner: { zh: "语言学习产品命名指南：跨语言易读、吉祥物人格、打卡传播测试等 5 种思路。", en: "Language learning product naming guide: cross-language readability." } },
  { slug: "resume", label: { zh: "简历求职", en: "Resume & job search" }, oneLiner: { zh: "简历与求职工具命名指南：职业动词、信心词根、焦虑时刻测试等 5 种思路。", en: "Resume and job-search tool naming guide: career verbs, confidence roots." } },
  { slug: "events", label: { zh: "活动策划", en: "Event planning" }, oneLiner: { zh: "活动策划公司命名指南：时刻词根、幕后专业感、提案页测试等 5 种思路。", en: "Event planning company naming guide: moment-and-light roots." } },
  { slug: "moving", label: { zh: "搬家服务", en: "Moving services" }, oneLiner: { zh: "搬家公司命名指南：托付感词根、力量与轻盈的平衡、电话报价测试等 5 种思路。", en: "Moving company naming guide: trust-first roots, strength versus lightness." } },
  { slug: "aquarium", label: { zh: "水族爬宠", en: "Aquariums & reptiles" }, oneLiner: { zh: "水族与爬宠品牌命名指南：生态词根、圈层黑话、玻璃缸美学等 5 种思路。", en: "Aquarium and reptile brand naming guide: ecosystem roots, hobbyist code words." } },
  { slug: "indiehacker", label: { zh: "独立开发者", en: "Indie hackers" }, oneLiner: { zh: "独立开发者（indie hacker）产品命名指南：一人品牌、build in public、可搜索造词等 5 种思路。", en: "Indie hacker product naming guide: name-as-landing-page, build-in-public identity." } },
  { slug: "petsupplies", label: { zh: "宠物用品电商", en: "Pet supplies e-commerce" }, oneLiner: { zh: "宠物用品电商命名指南：拟宠语气、复购信任感、品类升维等 5 种思路。", en: "Pet supplies e-commerce naming guide: pet's-eye-view words, repeat-purchase trust." } },
  { slug: "preschool", label: { zh: "儿童早教", en: "Early childhood education" }, oneLiner: { zh: "儿童早教与少儿启蒙品牌命名指南：双重受众、成长意象、安全信任感等 5 种思路。", en: "Early learning brand naming guide: dual-audience names, growth imagery." } },
  { slug: "travelshoot", label: { zh: "旅拍摄影", en: "Travel photography" }, oneLiner: { zh: "旅拍摄影品牌命名指南：目的地意象、纪念感词根、社交种草传播等 5 种思路。", en: "Travel photography brand naming guide: destination imagery, keepsake framing." } },
  { slug: "forwarder", label: { zh: "跨境物流", en: "Cross-border logistics" }, oneLiner: { zh: "跨境物流与货代品牌命名指南：确定性词根、全球网络感、时效承诺等 5 种思路。", en: "Cross-border logistics and freight forwarder naming guide: certainty roots." } },
  { slug: "mcn", label: { zh: "短视频 MCN", en: "Short-video MCN" }, oneLiner: { zh: "短视频 MCN 与内容机构命名指南：造星工厂感、内容宇宙意象、B 端信任等 5 种思路。", en: "Short-video MCN and creator-network naming guide: star-maker imagery." } },
  { slug: "opensource", label: { zh: "开源项目", en: "Open source" }, oneLiner: { zh: "开源项目命名指南：包管理器可用性、CLI 输入成本、隐喻与彩蛋文化等 5 种思路。", en: "Open source naming guide: package-registry checks first, CLI typing cost." } },
  { slug: "indiegame", label: { zh: "独立游戏", en: "Indie games" }, oneLiner: { zh: "独立游戏与工作室命名指南：情绪钩子、玩法直译、造词世界观等 5 种思路。", en: "Indie game naming guide: emotion hooks, mechanic-literal names, coined worlds." } },
  { slug: "gearrental", label: { zh: "影棚器材租赁", en: "Gear & studio rentals" }, oneLiner: { zh: "摄影棚与摄影器材租赁命名指南：专业信任感、地标场景词、器材圈黑话等 5 种思路。", en: "Photo studio and camera gear rental naming guide: trade-jargon trust, space words." } },
  { slug: "sourcing", label: { zh: "电商选品", en: "Product sourcing" }, oneLiner: { zh: "电商选品与市场分析工具命名指南：数据雷达意象、淘金隐喻、卖家黑话等 5 种思路。", en: "E-commerce product research tool naming guide: scout and radar imagery." } },
  { slug: "fleamarket", label: { zh: "线下市集", en: "Markets & pop-ups" }, oneLiner: { zh: "线下市集与快闪活动命名指南：在地文化词、节令时间词、社群暗号等 5 种思路。", en: "Flea market and pop-up naming guide: local-culture words, seasonal timing." } },
  { slug: "ski", label: { zh: "滑雪户外", en: "Ski & snow" }, oneLiner: { zh: "滑雪装备、雪场服务与雪友社群命名指南：山雪意象、速度词根、雪圈黑话等 5 种思路。", en: "Ski gear, resort service and snow community naming guide: mountain imagery." } },
  { slug: "aiart", label: { zh: "AI 绘画", en: "AI art tools" }, oneLiner: { zh: "AI 绘画与生成式创作工具命名指南：造物动词、艺术意象、模型代号感等 5 种思路。", en: "AI image generation tool naming guide: creation verbs, art-history borrowings." } },
  { slug: "campsite", label: { zh: "露营地", en: "Campgrounds" }, oneLiner: { zh: "露营地与营地运营品牌命名指南：山野意象、栖居动词、在地文化词等 5 种思路。", en: "Campground and camp-operations naming guide: wilderness imagery, dwelling verbs." } },
  { slug: "tcm", label: { zh: "中医养生", en: "TCM & wellness" }, oneLiner: { zh: "中医养生馆、艾灸推拿与草本品牌命名指南：经典借词、草本意象、堂号传统等 5 种思路。", en: "Traditional Chinese medicine and herbal wellness naming guide: heritage hall names." } },
  { slug: "deskcraft", label: { zh: "桌面文创", en: "Desk & stationery" }, oneLiner: { zh: "桌面周边与文创品牌命名指南：器物拟人、纸墨意象、生活切片等 5 种思路。", en: "Stationery and desk accessories brand naming guide: scholar's-object roots." } },
  { slug: "petmemorial", label: { zh: "宠物殡葬", en: "Pet memorial" }, oneLiner: { zh: "宠物殡葬与纪念服务命名指南：彼岸意象、告别动词、纪念词根等 5 种思路。", en: "Pet aftercare and memorial service naming guide: rainbow-bridge imagery." } },
  { slug: "postpartum", label: { zh: "月子中心", en: "Postpartum care" }, oneLiner: { zh: "月子中心与产后护理品牌命名指南：守护意象、新生词根、专业背书等 5 种思路。", en: "Postpartum retreat and maternal care naming guide: guardianship imagery." } },
  { slug: "pettraining", label: { zh: "宠物训练", en: "Pet training" }, oneLiner: { zh: "宠物训练与行为矫正机构命名指南：服从/默契意象、犬校人设、正向训练理念等 5 种思路。", en: "Pet training and behavior brand naming guide: rapport imagery, dog-school personas." } },
  { slug: "nailsalon", label: { zh: "美甲美睫", en: "Nail & lash studios" }, oneLiner: { zh: "美甲美睫工作室命名指南：指尖意象、审美人设、闺蜜昵称感等 5 种思路。", en: "Nail and lash studio naming guide: fingertip imagery, aesthetic-tribe signaling." } },
  { slug: "laundry", label: { zh: "洗衣洗护", en: "Laundry & garment care" }, oneLiner: { zh: "洗衣店与衣物洗护品牌命名指南：焕新意象、护理升维、时间承诺等 5 种思路。", en: "Laundry and garment care naming guide: renewal imagery, care-tier elevation." } },
  { slug: "rvtravel", label: { zh: "房车旅行", en: "RV travel" }, oneLiner: { zh: "房车租赁与房车旅行品牌命名指南：移动的家、在路上、营地生态等 5 种思路。", en: "RV rental and camper travel naming guide: home-on-wheels imagery, open-road roots." } },
  { slug: "knowledgepay", label: { zh: "知识付费", en: "Paid knowledge & communities" }, oneLiner: { zh: "知识付费与付费社群命名指南：认知升级意象、圈层归属感、IP 人设延伸等 5 种思路。", en: "Paid courses, cohorts and membership community naming guide: outcome verbs." } },
  { slug: "matchmaking", label: { zh: "婚恋相亲", en: "Matchmaking & dating" }, oneLiner: { zh: "婚恋相亲与高端匹配服务命名指南：缘分意象、真诚背书、圈层筛选等 5 种思路。", en: "Matchmaking and dating service naming guide: fate imagery, connection metaphors." } },
  { slug: "tattoo", label: { zh: "纹身工作室", en: "Tattoo studios" }, oneLiner: { zh: "纹身工作室命名指南：墨与针意象、风格流派标签、纹身师个人 IP 等 5 种思路。", en: "Tattoo studio naming guide: ink and needle imagery, style-school signaling." } },
  { slug: "climbing", label: { zh: "攀岩馆", en: "Climbing gyms" }, oneLiner: { zh: "攀岩馆与抱石馆命名指南：岩壁意象、向上隐喻、社群圈层感等 5 种思路。", en: "Climbing and bouldering gym naming guide: rock imagery, upward metaphors." } },
  { slug: "swimschool", label: { zh: "游泳培训", en: "Swim schools" }, oneLiner: { zh: "游泳培训与亲子游泳机构命名指南：水的意象、安全承诺、小鱼儿人设等 5 种思路。", en: "Swim school and baby-swimming naming guide: water-play imagery, safety anchors." } },
  { slug: "3dprint", label: { zh: "3D 打印", en: "3D printing" }, oneLiner: { zh: "3D 打印与增材制造服务命名指南：层积意象、从图到物承诺、材料词根等 5 种思路。", en: "3D printing and additive manufacturing naming guide: layer-built imagery." } },
  { slug: "vending", label: { zh: "无人零售", en: "Vending & unattended retail" }, oneLiner: { zh: "自动售货机与无人零售品牌命名指南：随时随地承诺、盒子意象、点位信任等 5 种思路。", en: "Vending machine and unattended retail naming guide: always-there promises." } },
  { slug: "kidsart", label: { zh: "少儿美术", en: "Kids' art schools" }, oneLiner: { zh: "少儿美术与创意教育机构命名指南：色彩意象、想象力叙事、大师致敬等 5 种思路。", en: "Children's art education naming guide: saturated-color imagery." } },
  { slug: "danceschool", label: { zh: "舞蹈工作室", en: "Dance studios" }, oneLiner: { zh: "舞蹈工作室与舞蹈培训命名指南：律动意象、舞种流派标签、身体叙事等 5 种思路。", en: "Dance studio naming guide: rhythm roots, style-scene signaling." } },
  { slug: "martialarts", label: { zh: "武术格斗馆", en: "Martial arts gyms" }, oneLiner: { zh: "武术馆与格斗健身房命名指南：武学词根、师承门派叙事、强者隐喻等 5 种思路。", en: "Martial arts and combat gym naming guide: warrior-path roots, lineage narratives." } },
  { slug: "bikeshop", label: { zh: "骑行单车", en: "Bike shops & cycling" }, oneLiner: { zh: "骑行品牌与自行车店命名指南：轮与风的意象、速度隐喻、社群圈层感等 5 种思路。", en: "Cycling brand and bike shop naming guide: wheel and wind imagery, speed metaphors." } },
  { slug: "fishing", label: { zh: "垂钓渔具", en: "Fishing & tackle" }, oneLiner: { zh: "垂钓渔具与钓鱼服务命名指南：水域意象、渔获叙事、耐心哲学等 5 种思路。", en: "Fishing tackle and angling brand naming guide: water imagery, catch narratives." } },
  { slug: "foodtruck", label: { zh: "餐车小吃", en: "Food trucks & street food" }, oneLiner: { zh: "餐车与街头小吃品牌命名指南：招牌单品直给、烟火气人设、车轮梗等 5 种思路。", en: "Food truck and street food naming guide: signature-dish naming, vendor personas." } },
  { slug: "repair", label: { zh: "维修服务", en: "Repair & handyman services" }, oneLiner: { zh: "家电维修与上门服务命名指南：靠谱承诺、师傅人设、速度叙事等 5 种思路。", en: "Appliance repair and handyman naming guide: trust anchors, craftsman personas." } },
  { slug: "pottery", label: { zh: "陶艺手作", en: "Pottery & ceramics" }, oneLiner: { zh: "陶艺工作室与手作品牌命名指南：泥土窑火词根、器物哲学、慢生活叙事等 5 种思路。", en: "Pottery studio and ceramics brand naming guide: clay-and-kiln roots." } },
  { slug: "billiards", label: { zh: "台球桌球馆", en: "Billiards & pool halls" }, oneLiner: { zh: "台球馆与桌球俱乐部命名指南：球杆词根、绅士运动叙事、传奇人物借势等 5 种思路。", en: "Billiards hall and pool club naming guide: cue-and-break roots." } },
  { slug: "drivingschool", label: { zh: "驾校驾培", en: "Driving schools" }, oneLiner: { zh: "驾校与驾培机构命名指南：通过率承诺、安全信任词根、陪伴叙事等 5 种思路。", en: "Driving school naming guide: pass-rate promise roots, safety-trust registers." } },
  { slug: "optician", label: { zh: "眼镜视光", en: "Opticians & eyewear" }, oneLiner: { zh: "眼镜店与视光中心命名指南：光学词根、医疗信任叙事、潮流配饰路线等 5 种思路。", en: "Optical shop and eyewear brand naming guide: optics roots, medical-trust narratives." } },
  { slug: "massage", label: { zh: "按摩推拿", en: "Massage & bodywork" }, oneLiner: { zh: "按摩推拿与养生 SPA 命名指南：手法词根、中医经络叙事、都市减压路线等 5 种思路。", en: "Massage and bodywork studio naming guide: touch-and-release roots." } },
  { slug: "mealprep", label: { zh: "轻食健康餐", en: "Meal prep & healthy eats" }, oneLiner: { zh: "轻食店与健康餐订阅命名指南：清爽词根、营养数字叙事、自律人设等 5 种思路。", en: "Salad bar and meal-prep subscription naming guide: fresh-and-light roots." } },
  { slug: "petphoto", label: { zh: "宠物摄影", en: "Pet photography" }, oneLiner: { zh: "宠物摄影工作室命名指南：拟人视角、瞬间词根、毛孩子昵称等 5 种思路。", en: "Pet photography naming guide: humanizing registers, moment roots, paw-pun coinages." } },
  { slug: "campgear", label: { zh: "露营装备", en: "Camping gear" }, oneLiner: { zh: "露营装备品牌命名指南：荒野词根、可靠感金属词、轻量化叙事等 5 种思路。", en: "Camping gear naming guide: wilderness imagery, reliability roots." } },
  { slug: "careercoach", label: { zh: "职业规划咨询", en: "Career coaching" }, oneLiner: { zh: "职业规划与生涯咨询命名指南：航向词根、跃迁叙事、教练人设等 5 种思路。", en: "Career coaching and counseling naming guide: navigation roots, upward narratives." } },
  { slug: "fragrance", label: { zh: "香氛蜡烛", en: "Home fragrance & candles" }, oneLiner: { zh: "香氛蜡烛与家居香品牌命名指南：通感词根、场景切片、故事产地等 5 种思路。", en: "Candle and home fragrance naming guide: synesthetic roots, moment slices." } },
  { slug: "diving", label: { zh: "潜水俱乐部", en: "Diving & scuba" }, oneLiner: { zh: "潜水俱乐部与潜店命名指南：深蓝词根、失重叙事、安全专业感等 5 种思路。", en: "Dive shop and scuba club naming guide: deep-blue imagery, weightlessness narratives." } },
  { slug: "carwash", label: { zh: "汽车美容洗车", en: "Car wash & detailing" }, oneLiner: { zh: "洗车与汽车美容命名指南：焕新词根、爱车人设、效率承诺等 5 种思路。", en: "Car wash and auto detailing naming guide: renewal roots, car-lover personas." } },
  { slug: "studytour", label: { zh: "研学营地", en: "Study camps & tours" }, oneLiner: { zh: "研学旅行与营地教育命名指南：成长隐喻、行走课堂、安全信号等 5 种思路。", en: "Study travel and camp education naming guide: growth metaphors." } },
  { slug: "petboarding", label: { zh: "宠物寄养", en: "Pet boarding" }, oneLiner: { zh: "宠物寄养与宠物酒店命名指南：第二个家、假期快乐、透明可见等 5 种思路。", en: "Pet boarding and pet hotel naming guide: second-home warmth, vacation framing." } },
  { slug: "upcycling", label: { zh: "旧物改造", en: "Upcycling & rework" }, oneLiner: { zh: "旧物改造与升级再造命名指南：重生叙事、独一无二、来历故事等 5 种思路。", en: "Upcycling and rework naming guide: rebirth narratives, one-of-a-kind scarcity." } },
  { slug: "zine", label: { zh: "独立杂志", en: "Indie magazines & zines" }, oneLiner: { zh: "独立杂志与 zine 命名指南：单词美学、态度宣言、生活方式提案等 5 种思路。", en: "Indie magazine and zine naming guide: single-word aesthetics, stance statements." } },
  { slug: "locksmith", label: { zh: "开锁换锁", en: "Locksmiths" }, oneLiner: { zh: "开锁换锁与锁匠服务命名指南：速度承诺、持证信任、钥匙意象等 5 种思路。", en: "Locksmith and lock service naming guide: speed promises, licensed-trust signals." } },
  { slug: "skateshop", label: { zh: "滑板店", en: "Skate shops" }, oneLiner: { zh: "滑板店与滑板品牌命名指南：反叛态度、圈内黑话、场景地标等 5 种思路。", en: "Skate shop and skate brand naming guide: rebel attitude, insider slang." } },
  { slug: "surf", label: { zh: "冲浪俱乐部", en: "Surf clubs" }, oneLiner: { zh: "冲浪俱乐部与冲浪学校命名指南：海浪意象、地点绑定、自由态度等 5 种思路。", en: "Surf club and surf school naming guide: ocean imagery, spot-binding." } },
  { slug: "golf", label: { zh: "高尔夫", en: "Golf" }, oneLiner: { zh: "高尔夫俱乐部与球具品牌命名指南：庄园气质、自然地貌、技术精准等 5 种思路。", en: "Golf club and golf brand naming guide: estate gravitas, landscape binding." } },
  { slug: "vr", label: { zh: "VR 体验馆", en: "VR arcades" }, oneLiner: { zh: "VR 体验馆与线下沉浸娱乐命名指南：异世界入口、科技奇观、场域命名等 5 种思路。", en: "VR arcade and immersive entertainment naming guide: portal imagery, tech spectacle." } },
  { slug: "bar", label: { zh: "酒吧清吧", en: "Bars & lounges" }, oneLiner: { zh: "酒吧与鸡尾酒吧命名指南：隐秘暗号、故事人设、微醺意象等 5 种思路。", en: "Bar and cocktail lounge naming guide: speakeasy secrecy, house personas." } },
  { slug: "musicschool", label: { zh: "音乐培训琴行", en: "Music schools" }, oneLiner: { zh: "音乐培训机构与琴行命名指南：乐理词根、大师致敬、成长叙事等 5 种思路。", en: "Music school and instrument store naming guide: music-theory roots, maestro homage." } },
  { slug: "chess", label: { zh: "棋类培训", en: "Chess & Go academies" }, oneLiner: { zh: "围棋、国际象棋与棋类培训命名指南：棋语词根、智慧意象、段位叙事等 5 种思路。", en: "Chess and Go academy naming guide: board-game roots, wisdom imagery." } },
  { slug: "hotpot", label: { zh: "火锅烧烤", en: "Hotpot & BBQ" }, oneLiner: { zh: "火锅店与烧烤品牌命名指南：烟火气直给、地域血统、社交记忆点等 5 种思路。", en: "Hotpot and BBQ naming guide: street-fire imagery, regional bloodline." } },
  { slug: "dessert", label: { zh: "甜品冰淇淋", en: "Dessert & ice cream" }, oneLiner: { zh: "甜品店与冰淇淋品牌命名指南：甜蜜意象、口感通感、情绪犒赏等 5 种思路。", en: "Dessert and ice cream naming guide: sweet imagery, texture synesthesia." } },
  { slug: "convenience", label: { zh: "社区便利店", en: "Convenience stores" }, oneLiner: { zh: "便利店与社区零售品牌命名指南：邻里亲切感、便利承诺、都市节奏等 5 种思路。", en: "Convenience store naming guide: neighborly warmth, the convenience promise." } },
  { slug: "stationery", label: { zh: "文创文具", en: "Stationery & paper goods" }, oneLiner: { zh: "文创品牌与文具店命名指南：纸墨意象、生活美学、文化 IP 等 5 种思路。", en: "Stationery brand naming guide: paper-and-ink imagery, lifestyle aesthetics." } },
  { slug: "cybercafe", label: { zh: "电竞网咖", en: "Esports cafés" }, oneLiner: { zh: "电竞馆与网咖命名指南：竞技热血、基地场域、玩家黑话等 5 种思路。", en: "Esports café naming guide: competitive fire, base-camp identity, player slang." } },
  { slug: "carrental", label: { zh: "租车出行", en: "Car rental & mobility" }, oneLiner: { zh: "租车公司与共享出行品牌命名指南：自由在路上、可靠承诺、速度效率等 5 种思路。", en: "Car rental naming guide: freedom on the road, reliability promise." } },
  { slug: "noodle", label: { zh: "粉面小吃", en: "Noodle shops" }, oneLiner: { zh: "面馆与粉面小吃品牌命名指南：一碗的画面感、地域正宗、市井烟火等 5 种思路。", en: "Noodle shop naming guide: bowl imagery, regional authenticity, street-life persona." } },
  { slug: "grocery", label: { zh: "社区生鲜", en: "Fresh groceries" }, oneLiner: { zh: "社区生鲜店命名指南：新鲜承诺、邻里亲切、产地直采等 5 种思路。", en: "Fresh grocery naming guide: the freshness promise, neighborly warmth." } },
  { slug: "tutoring", label: { zh: "课外辅导", en: "Tutoring & test prep" }, oneLiner: { zh: "课外辅导与家教品牌命名指南：提分承诺、师者人设、陪伴成长等 5 种思路。", en: "Tutoring brand naming guide: academic value, teacher persona, growth companionship." } },
  { slug: "printshop", label: { zh: "图文快印", en: "Print shops" }, oneLiner: { zh: "图文快印店命名指南：快与准的承诺、一站式服务、设计增值等 5 种思路。", en: "Print shop naming guide: speed-and-accuracy promise, one-stop capability." } },
  { slug: "errand", label: { zh: "同城跑腿", en: "Errand & courier services" }, oneLiner: { zh: "同城跑腿与代办服务命名指南：快的承诺、使命必达、人格化信任等 5 种思路。", en: "Errand and courier naming guide: speed in the sound, mission-complete reliability." } },
  { slug: "plumber", label: { zh: "管道疏通维修", en: "Plumbing & repair" }, oneLiner: { zh: "管道疏通与水电维修品牌命名指南：应急响应、师傅人设、透明报价等 5 种思路。", en: "Plumbing and home repair naming guide: emergency response, tradesman persona." } },
  { slug: "travelagency", label: { zh: "旅行社", en: "Travel agencies" }, oneLiner: { zh: "旅行社与定制游命名指南：目的地梦想、专业向导人设、行程确定性等 5 种思路。", en: "Travel agency naming guide: destination dreaming, guide personas." } },
  { slug: "teahouse", label: { zh: "茶馆茶室", en: "Tea houses & tea brands" }, oneLiner: { zh: "茶馆与茶品牌命名指南：山场产地、慢生活意境、新中式反差等 5 种思路。", en: "Tea house and tea brand naming guide: terroir words, slow-living moods." } },
  { slug: "petcafe", label: { zh: "宠物咖啡", en: "Pet cafés" }, oneLiner: { zh: "宠物咖啡馆与猫咖命名指南：治愈拟声、店宠 IP、空间意象等 5 种思路。", en: "Pet café and cat café naming guide: healing onomatopoeia, house-pet IP." } },
  { slug: "weddingphoto", label: { zh: "婚纱摄影", en: "Wedding photography" }, oneLiner: { zh: "婚纱摄影与婚礼跟拍命名指南：永恒意象、光影工艺、主理人签名等 5 种思路。", en: "Wedding photography naming guide: forever imagery, light-craft words." } },
  { slug: "footspa", label: { zh: "足疗采耳", en: "Foot spas & wellness lounges" }, oneLiner: { zh: "足疗采耳与养生馆命名指南：解乏意象、手艺传承、新中式体验等 5 种思路。", en: "Foot spa and wellness lounge naming guide: release imagery, craft lineage." } },
  { slug: "parcel", label: { zh: "快递驿站", en: "Parcel stations & pickup points" }, oneLiner: { zh: "快递驿站与社区代收命名指南：驿站意象、邻里人格、安心承诺等 5 种思路。", en: "Parcel station and pickup point naming guide: relay-station imagery." } },
];
