/**
 * hub 索引页轻量数据 —— 由 scripts/gen-hub-index.mjs 从
 * tlds.ts / guides.ts / compares.ts 全文内容生成，请勿手改。
 * 内容源变更（新增/修改 TLD、行业指南、对比页）后运行 node scripts/gen-hub-index.mjs 重新生成；
 * CI/审计可用 --check 校验一致性。
 * 存在意义：hub 页组件只需一句话定位/标签/标题，引用本模块而非全文 chunk（R271 移动性能优化）；
 * 按 hub 分立三个文件，每个 hub 页只加载自己那份索引（R282 移动性能优化）。
 */
import type { Tld } from "./tld-list";

type Localized = { zh: string; en: string };

/** tld → 一句话定位（metaDescription 首句），键集与 TLD_LIST 编译期强一致 */
export const TLD_ONE_LINERS = {
  "com": { zh: ".com 是认知度最高的通用顶级域名，适合几乎所有正式产品与企业官网。", en: ".com is the most recognized TLD on the internet — the default for serious products and businesses." },
  "net": { zh: ".net 源自网络基础设施，适合网络服务、开发工具与技术平台。", en: ".net has infrastructure roots and suits network services, developer tools and technical platforms." },
  "org": { zh: ".org 是非营利组织与开源项目的标志性域名，自带公益与公信力气质。", en: ".org signals non-profit credibility and is the natural home of open-source projects and communities." },
  "io": { zh: ".io 是开发者与科技创业公司的心头好，短、极客、辨识度高。", en: ".io is the developer favorite — short, geeky, instantly recognizable in tech circles." },
  "ai": { zh: ".ai 是 AI 产品的身份标签，贵但直接表达定位。", en: ".ai is the identity badge of AI products — expensive but instantly communicates positioning." },
  "co": { zh: ".co 短小精悍，是创业公司在 .com 之外的时髦替身。", en: ".co is the stylish one-letter-off alternative to .com favored by startups." },
  "app": { zh: ".app 由 Google 运营、强制 HTTPS，是移动与 Web 应用的天然后缀。", en: ".app is Google-operated with enforced HTTPS — the natural suffix for mobile and web apps." },
  "dev": { zh: ".dev 由 Google 运营、强制 HTTPS，是开发者产品与技术品牌的标配后缀。", en: ".dev is Google-operated, HTTPS-enforced, and the default suffix for developer products and personal tech brands." },
  "xyz": { zh: ".xyz 首年极便宜、气质年轻反叛，是 Web3 与实验项目的宠儿。", en: ".xyz is dirt-cheap in year one with a young, rebellious vibe — beloved by Web3 and experimental projects." },
  "cc": { zh: ".cc 短平快、无语义包袱，社区与创意项目常用。", en: ".cc is short, neutral and baggage-free — popular with communities and creative projects." },
  "tv": { zh: ".tv 天然指向视频与直播，是流媒体内容品牌的首选后缀。", en: ".tv points straight at video and streaming — the suffix of choice for content brands." },
  "cn": { zh: ".cn 是中国国家域名，价格亲民、面向国内业务合规友好。", en: ".cn is China's country domain — affordable and compliance-friendly for businesses serving Chinese users." },
  "me": { zh: ".me 天然适合个人品牌、简历主页与开发者作品集，还能拼出动词短语域名。", en: ".me is the natural home for personal brands, portfolios and verb-phrase domains like hire.me." },
  "tech": { zh: ".tech 把「科技」直接写进后缀，适合硬科技公司、开发者社区与科技媒体。", en: ".tech puts the industry right in the suffix — built for hard-tech companies, developer communities and tech media." },
  "online": { zh: ".online 读起来就是一句话（品牌 + 上线了），适合线上服务、课程与活动页。", en: ".online reads as a full phrase — brand, online." },
  "store": { zh: ".store 直接告诉访客「这里能买东西」，适合电商、品牌商城与 DTC 独立站。", en: ".store tells visitors they can buy here — built for e-commerce, brand shops and DTC sites." },
  "site": { zh: ".site 是含义最中性的新后缀之一，什么类型的网站都装得下，价格亲民库存充裕。", en: ".site is the most neutral new TLD — it fits any kind of website, with friendly pricing and deep inventory." },
  "top": { zh: ".top 注册量位居新后缀前列、在国内接受度高、价格极低。", en: ".top ranks among the highest-volume new TLDs, is popular in China, and costs very little." },
  "shop": { zh: ".shop 语义直白，是电商与品牌商店的天然后缀。", en: ".shop says exactly what it means — the natural suffix for e-commerce and brand stores." },
  "cloud": { zh: ".cloud 是云服务与 SaaS 的品类后缀，语义清晰、库存充足。", en: ".cloud is the category suffix for cloud services and SaaS — clear semantics, good inventory." },
  "pro": { zh: ".pro 传达专业与资质感，适合专业服务、顾问与工具的 Pro 版。", en: ".pro signals professionalism — great for professional services, consultants, and Pro tiers of products." },
  "vip": { zh: ".vip 在国内认知度高、可 ICP 备案，适合会员制产品与粉丝社群。", en: ".vip is unusually strong in China, ICP-filable, and fits membership products and fan communities." },
  "club": { zh: ".club 是社群与俱乐部的天然后缀，语义友好、价格低。", en: ".club is the natural suffix for communities and clubs — friendly semantics, low prices." },
  "link": { zh: ".link 语义即「链接」，适合导航页、个人主页聚合与短链服务。", en: ".link literally means link — perfect for link-in-bio pages, directories and short-link services." },
  "live": { zh: ".live 语义即「直播/现场」，适合直播、活动与实时服务。", en: ".live means happening now — built for streaming, events and real-time services." },
  "space": { zh: ".space 语义开放百搭，适合创意空间、个人站与社区。", en: ".space is open-ended and versatile — great for creative spaces, personal sites and communities." },
  "fun": { zh: ".fun 语义即「好玩」，适合游戏、娱乐与活动品牌。", en: ".fun literally means fun — built for games, entertainment and event brands." },
  "art": { zh: ".art 是艺术领域的专属后缀，适合艺术家、画廊与创意机构。", en: ".art is the dedicated suffix for the art world — artists, galleries and creative institutions." },
  "design": { zh: ".design 是设计师与设计团队的身份后缀。", en: ".design puts the profession in the domain — for designers, studios and design teams." },
  "studio": { zh: ".studio 是创意工作室的天然后缀，适合设计、影像、游戏与内容团队。", en: ".studio is the natural suffix for creative studios — design, film, games and content teams." },
  "info": { zh: ".info 是最早的「信息类」通用后缀，适合资料站、文档、百科与项目信息页。", en: ".info is the original \"information\" TLD — great for resource sites, docs, wikis and info pages." },
  "sh": { zh: ".sh 是开发者最爱的极客后缀之一（shell 梗），适合 CLI 工具、开发者产品与技术博客。", en: ".sh is a developer favorite (the shell-script pun) — great for CLI tools, dev products and tech blogs." },
  "gg": { zh: ".gg 是游戏与电竞圈的标志性后缀（good game 梗），适合游戏、社区与直播相关产品。", en: ".gg is the signature TLD of gaming and esports (the \"good game\" pun) — for games, communities and streaming products." },
  "so": { zh: ".so 因 Notion.so 走红，适合效率工具与初创产品，也是共享库文件名的极客梗。", en: ".so was put on the map by Notion.so — a fit for productivity tools and startups, with a shared-library pun for developers." },
  "us": { zh: ".us 是美国国家后缀，便宜且可玩「与我们」的语义梗，适合面向美国市场的产品与社区。", en: ".us is America's country code — cheap, with a built-in \"us = we\" wordplay." },
  "in": { zh: ".in 是印度国家后缀，也是英语介词 in 的语义梗，适合面向印度市场的产品与「in」短语域名。", en: ".in is India's country code and the English preposition \"in\" — for India-market products and phrase domains." },
  "world": { zh: ".world 自带全球化与开放感，适合国际化产品、社区与元宇宙/虚拟世界项目。", en: ".world signals global reach and openness — great for international products, communities and virtual-world projects." },
  "life": { zh: ".life 语义温暖，适合健康、生活方式、家庭与个人成长类产品。", en: ".life has warm, human semantics — ideal for health, lifestyle, family and personal-growth brands." },
  "agency": { zh: ".agency 直接说明「我是一家代理/机构」，适合设计、营销、公关与创意服务公司。", en: ".agency says exactly what you are — built for design, marketing, PR and creative service firms." },
  "games": { zh: ".games 是游戏行业的语义后缀，适合游戏工作室、独立游戏、电竞与游戏媒体。", en: ".games puts the industry in the domain — for game studios, indie games, esports and gaming media." },
  "email": { zh: ".email 语义唯一指向邮件，适合邮件服务、营销工具与通讯类产品。", en: ".email means exactly one thing — perfect for email services, marketing tools and messaging products." },
  "network": { zh: ".network 适合网络基础设施、去中心化协议与社群网络类产品。", en: ".network fits infrastructure, decentralized protocols and community networks." },
  "digital": { zh: ".digital 适合数字化转型服务、数字营销机构与一切「数字化」叙事的产品。", en: ".digital fits digital-transformation services, marketing agencies and anything with a digital story." },
  "media": { zh: ".media 是内容与媒体行业的语义后缀，适合媒体公司、播客、视频团队与内容工作室。", en: ".media is the content industry's suffix — for media companies, podcasts, video teams and content studios." },
  "group": { zh: ".group 适合集团公司、控股企业与多品牌矩阵的母品牌官网。", en: ".group suits holding companies, multi-brand parents and community groups." },
  "center": { zh: ".center 适合帮助中心、资源中心、培训与服务中心类站点。", en: ".center fits help centers, resource hubs, training and service centers." },
  "works": { zh: ".works 语义双关「作品」与「能用」，适合工作室、作品集与实干型工具产品。", en: ".works puns on \"works of craft\" and \"it works\" — great for studios, portfolios and dependable tools." },
  "zone": { zh: ".zone 语义是「地带/专区」，适合游戏社区、主题站与开发者试验场。", en: ".zone means a dedicated space — great for gaming communities, topic hubs and developer playgrounds." },
  "news": { zh: ".news 语义直白「新闻/资讯」，适合媒体、行业资讯站与 newsletter。", en: ".news says exactly what it means — built for media sites, industry news hubs and newsletters." },
  "tools": { zh: ".tools 语义是「工具集」，适合在线工具站、开发者工具与实用软件。", en: ".tools is purpose-built for utility sites, developer toolchains and practical software." },
  "run": { zh: ".run 语义双关「运行」与「跑步」，适合开发者运行时/部署产品与运动健身品牌。", en: ".run puns on executing code and running sports — great for runtimes, deploy platforms and running brands." },
  "codes": { zh: ".codes 语义覆盖「代码」与「优惠码」，适合开发者个人站、代码产品与折扣码聚合站。", en: ".codes covers both source code and promo codes — great for developer portfolios, code products and coupon sites." },
  "company": { zh: ".company 语义是「公司」，适合中小企业官网、控股主体与品牌旗下公司页。", en: ".company literally says what you are — great for SMB websites, holding entities and \"The X Company\" brands." },
  "wiki": { zh: ".wiki 语义是「百科/知识库」，适合产品文档、粉丝百科与团队知识库。", en: ".wiki means knowledge base — built for product docs, fan wikis and team knowledge hubs." },
  "blog": { zh: ".blog 语义直白，是个人博客与内容创作者的身份后缀。", en: ".blog says exactly what it is — the identity suffix for writers and content creators." },
  "team": { zh: ".team 语义是「团队」，适合协作工具、招聘页、战队与俱乐部主页。", en: ".team means exactly that — built for collaboration tools, hiring pages, esports squads and clubs." },
  "chat": { zh: ".chat 是 AI 对话产品与社区聊天工具的天然后缀。", en: ".chat is the natural suffix for AI conversation products and community chat tools." },
  "finance": { zh: ".finance 语义严肃专业，适合金融科技、DeFi 与财务工具。", en: ".finance reads serious and professional — built for fintech, DeFi and money tools." },
  "global": { zh: ".global 一词表达全球化定位，适合跨国业务、国际组织与出海品牌。", en: ".global declares worldwide positioning in one word — for multinationals, international orgs and expanding brands." },
  "host": { zh: ".host 是主机托管与基础设施服务的行业后缀。", en: ".host is the industry suffix for hosting and infrastructure services." },
  "social": { zh: ".social 是社区、社交产品与创作者阵地的行业后缀。", en: ".social is the industry suffix for communities, social products and creator hubs." },
  "video": { zh: ".video 语义直指视频内容与视频工具，适合创作者、视频平台与视频类 SaaS。", en: ".video points straight at video content and video tools — for creators, platforms and video SaaS." },
  "fund": { zh: ".fund 语义直指基金与募资，适合投资基金、众筹项目与公益筹款。", en: ".fund points straight at funds and fundraising — for investment funds, crowdfunding and grant programs." },
  "land": { zh: ".land 语义指向土地、地产与虚拟世界，适合房产地产、农业与元宇宙项目。", en: ".land evokes real estate, farmland and virtual worlds — for property, agriculture and metaverse projects." },
  "click": { zh: ".click 便宜且动作感强，适合短链跳转、落地页与营销活动页。", en: ".click is cheap and action-charged — for short links, landing pages and marketing campaigns." },
  "icu": { zh: ".icu 读作 I see you，超低价且有梗，适合个人主页、实验项目与创意短域。", en: ".icu reads \"I see you\" — ultra-cheap with a built-in pun, for personal pages, experiments and creative short domains." },
  "page": { zh: ".page 是 Google 运营的「页面」后缀，全站强制 HTTPS，适合个人主页、产品落地页与文档站。", en: ".page is Google's HTTPS-only \"page\" suffix — for personal pages, landing pages and docs sites." },
  "bio": { zh: ".bio 一词双关「个人简介」与「生物/有机」，适合创作者主页、link-in-bio 与生物科技。", en: ".bio puns on \"personal bio\" and \"biology/organic\" — for creator pages, link-in-bio hubs and biotech." },
  "ink": { zh: ".ink 语义是「墨水」，适合纹身工作室、作家、插画师与出版内容站。", en: ".ink means ink — for tattoo studios, writers, illustrators and publishing sites." },
  "moe": { zh: ".moe 源自日语「萌え」，是 ACG 圈的文化后缀，适合动漫站、同人项目与二次元社区。", en: ".moe comes from Japanese \"moe\" — the anime-culture suffix for fan sites, doujin projects and otaku communities." },
  "lol": { zh: ".lol 就是「laughing out loud」，自带幽默基因，适合梗图站、搞笑内容与游戏社区。", en: ".lol is literally \"laughing out loud\" — built-in humor for meme sites, comedy content and gaming communities." },
  "uk": { zh: ".uk 是英国国家域名，本地信任度极高，适合面向英国市场的品牌与业务。", en: ".uk is the United Kingdom's country domain with unmatched local trust — for brands and businesses targeting the UK." },
  "fm": { zh: ".fm 自带电台与音频基因，是播客、音乐与音频产品的标志性后缀。", en: ".fm carries built-in radio and audio DNA — the signature suffix for podcasts, music and voice products." },
  "one": { zh: ".one 寓意「第一、唯一、合而为一」，短而好记，适合个人品牌与一体化产品。", en: ".one means first, only, all-in-one — short and memorable for personal brands and unified products." },
  "cool": { zh: ".cool 自带态度与年轻感，适合潮流品牌、创意工作室与个性化项目。", en: ".cool wears its attitude in the domain — for streetwear brands, creative studios and personality-first projects." },
  "red": { zh: ".red 以颜色入名，红色寓意热情、喜庆与醒目，适合品牌色为红的产品与中文场景。", en: ".red puts a color in the address — passion, celebration and visibility, with extra meaning for Chinese audiences." },
  "today": { zh: ".today 自带时效感与行动力，适合资讯站、日更内容与「今天就开始」的产品。", en: ".today carries urgency and freshness — for news sites, daily content and start-now products." },
  "best": { zh: ".best 把「最佳」写进域名，适合评测榜单、精选推荐与主打品质的品牌。", en: ".best puts a superlative in the address — for review sites, curated picks and quality-first brands." },
  "wtf": { zh: ".wtf 自带惊叹与吐槽气质，适合梗文化项目、猎奇内容与敢玩的品牌营销。", en: ".wtf carries built-in shock value — for meme projects, curiosity content and brands bold enough to play." },
  "pizza": { zh: ".pizza 是披萨店与美食品牌的行业专属后缀，域名即菜单。", en: ".pizza is the industry TLD where the domain is the menu — for pizzerias, food brands and delivery." },
  "bar": { zh: ".bar 适合酒吧、餐饮夜生活品牌，也被开发者玩出工具站气质。", en: ".bar suits bars and nightlife brands, with a developer-tool double meaning on the side." },
  "cafe": { zh: ".cafe 是咖啡馆与休闲空间的行业后缀，也适合社区型线上聚集地。", en: ".cafe is the industry TLD for coffee shops and cozy spaces — and for warm online gathering spots." },
  "money": { zh: ".money 直白宣示金钱主题，适合理财内容、个人财务工具与加密金融项目。", en: ".money says the topic out loud — for personal finance content, budgeting tools and crypto projects." },
  "gold": { zh: ".gold 自带贵金属与「金牌品质」双重语义，适合珠宝、贵金属交易与高端品牌。", en: ".gold carries both the precious metal and the gold-standard meaning — for jewelry, bullion and premium brands." },
  "band": { zh: ".band 是乐队与音乐团体的专属后缀，适合乐队官网、巡演信息与粉丝社群。", en: ".band is the purpose-built TLD for bands and music groups — sites, tours, merch and fan communities." },
  "cash": { zh: ".cash 直白传达「钱」的语义，适合支付工具、返现优惠与加密货币产品。", en: ".cash says money out loud — for payment tools, cashback platforms and crypto products." },
  "city": { zh: ".city 适合城市指南、本地生活服务与「××之城」式主题社区。", en: ".city fits city guides, local services and themed \"city of X\" communities." },
  "estate": { zh: ".estate 面向房地产经纪、豪宅项目与资产管理，real.estate 的组合自带行业招牌。", en: ".estate is built for real-estate agents, luxury properties and asset management — real.estate is the registry's own showcase." },
  "expert": { zh: ".expert 把专业身份写进域名，适合顾问、咨询师与垂直领域权威站。", en: ".expert puts professional authority in the domain — for consultants, advisors and vertical authority sites." },
  "farm": { zh: ".farm 适合农场直销、农业科技与「农场直达餐桌」品牌，也被开发者用作服务器集群昵称。", en: ".farm suits farm-to-table brands, agtech and direct-selling growers — plus developer culture's server farms." },
  "blue": { zh: ".blue 把品牌色写进域名，适合以蓝色为主视觉的品牌、海洋与航空主题项目。", en: ".blue writes your brand color into the domain — for blue-first brands, ocean and aviation projects." },
  "pink": { zh: ".pink 适合美妆时尚、甜品烘焙与少女感品牌，也是公益粉红丝带项目的天然后缀。", en: ".pink suits beauty, fashion, bakeries and sweet-toned brands — and pink-ribbon causes." },
  "black": { zh: ".black 自带高级感与神秘感，适合奢侈品牌、黑金会员体系与暗黑美学项目。", en: ".black carries built-in luxury and mystique — for premium brands, black-tier memberships and dark-aesthetic projects." },
  "ninja": { zh: ".ninja 是「某领域高手」的梗后缀，适合开发者工具、个人技术品牌与游戏电竞项目。", en: ".ninja is the \"master of X\" meme suffix — for developer tools, personal tech brands and gaming projects." },
  "rocks": { zh: ".rocks 把「X 真棒」写进域名，适合粉丝站、乐队与社区项目，注册价极低。", en: ".rocks puts \"X rocks!\" in the domain — for fan sites, bands and communities, at rock-bottom prices." },
  "pet": { zh: ".pet 是宠物行业的专属后缀，适合宠物店、宠物医疗与宠物科技品牌。", en: ".pet is the pet industry's own suffix — for pet shops, vet services and pet-tech brands." },
  "academy": { zh: ".academy 把「学院」写进域名，适合在线课程、培训机构与技能学习社区。", en: ".academy puts structured learning in the domain — for online courses, bootcamps and training programs." },
  "school": { zh: ".school 是教育行业的直白后缀，适合学校官网、课外班与在线学习项目，注册价很低。", en: ".school is education's most literal suffix — for schools, classes and online learning projects, at a low entry price." },
  "coach": { zh: ".coach 是教练经济的专属后缀，适合私教、人生教练与体育教练的个人品牌。", en: ".coach is the coaching economy's own suffix — for personal trainers, life coaches and sports coaches." },
  "care": { zh: ".care 把「关怀」写进域名，适合医疗健康、养老护理与客户服务品牌。", en: ".care puts compassion in the domain — for healthcare, senior care and customer-care brands." },
  "doctor": { zh: ".doctor 把医生身份写进域名，适合诊所、医生个人品牌与在线问诊服务。", en: ".doctor puts the white coat in the domain — for clinics, physician brands and telehealth, plus \"X doctor\" repair brands." },
  "restaurant": { zh: ".restaurant 把餐厅身份写进域名，适合实体餐厅、连锁品牌与餐饮预订平台。", en: ".restaurant spells the business out in full — for restaurants, chains and dining platforms." },
  "boutique": { zh: ".boutique 自带精品小店气质，适合独立设计品牌、买手店与手作工作室，首年注册极便宜。", en: ".boutique carries small-and-beautiful curation in the name — for indie labels, concept stores and artisan studios, with a very cheap first year." },
  "clinic": { zh: ".clinic 把诊所身份写进域名，适合口腔、医美、宠物等各类诊所与门诊品牌。", en: ".clinic spells the practice out in full — for dental, medspa, physio and veterinary clinics, plus \"X clinic\" consulting brands." },
  "dental": { zh: ".dental 是口腔行业的专属后缀，适合牙科诊所、正畸种植品牌与口腔护理产品。", en: ".dental is dentistry's own suffix — for dental practices, ortho and implant brands, and oral-care products." },
  "fitness": { zh: ".fitness 把健身身份写进域名，适合健身房、私教工作室与线上健身课程，首年注册很便宜。", en: ".fitness spells the business out in full — for gyms, training studios and online fitness programs, at a cheap entry price." },
  "photos": { zh: ".photos 把照片写进域名，适合摄影师作品集、婚礼摄影与图片交付站点，价格温和。", en: ".photos puts the pictures in the address — for photographer portfolios, wedding studios and client-delivery sites, at a mild price." },
  "gallery": { zh: ".gallery 自带展览气质，适合画廊、艺术家作品集与 NFT/数字艺术展厅。", en: ".gallery brings the white-wall space into the domain — for art galleries, artist portfolios and digital-art showrooms." },
  "salon": { zh: ".salon 把美业身份写进域名，适合美发、美甲、美容、造型工作室与连锁品牌。", en: ".salon spells the beauty business into the address — for hair, nail, skin and styling studios, plus creative salons." },
  "yoga": { zh: ".yoga 把瑜伽写进域名，适合瑜伽馆、教培与线上课程品牌，注册续费同价无涨价陷阱。", en: ".yoga puts the practice in the address — for studios, teachers, trainings and online course brands, with flat renewal pricing." },
  "coffee": { zh: ".coffee 把咖啡香写进域名，适合咖啡馆、烘焙工作室、咖啡豆电商与咖啡内容品牌。", en: ".coffee brews the aroma into the address — for cafés, roasters, bean e-commerce and coffee content brands." },
  "wine": { zh: ".wine 把酒香写进域名，适合酒庄、葡萄酒电商、侍酒师与酒评内容品牌。", en: ".wine pours the terroir into the address — for wineries, wine e-commerce, sommeliers and tasting content brands." },
  "kitchen": { zh: ".kitchen 把厨房搬进域名，适合私厨、云厨房、烹饪课程、食谱内容与厨房用品品牌。", en: ".kitchen moves the cooking into the address — for private chefs, cloud kitchens, cooking classes, recipe content and kitchenware brands." },
  "garden": { zh: ".garden 把花园写进域名，适合园艺电商、景观设计、植物内容社区与数字花园，首年注册极便宜。", en: ".garden grows greenery into the address — for garden e-commerce, landscaping, plant content and digital gardens, with a very cheap first year." },
  "photography": { zh: ".photography 把快门声写进域名，适合摄影师作品集、摄影工作室、婚礼与商业摄影品牌。", en: ".photography writes the craft into the address — for photographer portfolios, wedding and commercial studios, and photo education brands." },
  "events": { zh: ".events 把活动排期写进域名，适合活动策划、会展公司、演出售票与社群聚会品牌。", en: ".events puts the calendar into the address — for event planners, conference organizers, ticketing and community meetup brands." },
  "solutions": { zh: ".solutions 把「解决方案」写进域名，适合 IT 服务商、咨询公司、B2B 方案商与系统集成商，首年注册很便宜。", en: ".solutions says what you sell right in the address — for IT services, consultancies, B2B vendors and systems integrators, with a cheap first year." },
  "services": { zh: ".services 把服务清单写进域名，适合专业服务公司、家政维修、企业外包与本地服务商。", en: ".services puts the offering into the address — for professional firms, home services, outsourcing and local providers." },
  "consulting": { zh: ".consulting 把咨询身份写进域名，适合独立顾问、精品咨询公司、战略与管理咨询品牌。", en: ".consulting writes the profession into the address — for independent consultants, boutique firms, and strategy or management advisory brands." },
  "software": { zh: ".software 把产品形态写进域名，适合软件公司、开发工具、桌面应用与软件外包团队。", en: ".software says the product category in the address — for software companies, dev tools, desktop apps and custom development teams." },
  "marketing": { zh: ".marketing 把营销专业写进域名，适合营销代理机构、增长团队、营销 SaaS 与自媒体营销人。", en: ".marketing writes the profession into the address — for agencies, growth teams, martech SaaS and marketing creators." },
  "systems": { zh: ".systems 把工程气质写进域名，适合基础设施与运维团队、企业系统集成商、IoT 与嵌入式公司。", en: ".systems hums like an engineering room — for infrastructure and DevOps teams, integrators, IoT companies and security platforms." },
  "ventures": { zh: ".ventures 把创业野心写进域名，适合风投基金、创业工作室、孵化器与连续创业者。", en: ".ventures writes the bet on the future into the address — for VC funds, venture studios, accelerators and serial founders." },
  "capital": { zh: ".capital 把资本身份写进域名，适合私募与风投基金、资产管理公司、家族办公室与投资机构。", en: ".capital is the suit-and-tie suffix — for PE and VC funds, asset managers, family offices and investment firms." },
  "guru": { zh: ".guru 把专家人设写进域名，适合独立专家、教程与攻略站、咨询顾问与兴趣领域达人。", en: ".guru wears expertise with a wink — for independent experts, how-to sites, consultants and hobby authorities." },
  "tips": { zh: ".tips 把实用建议写进域名，适合攻略与技巧站、垂类内容博客、工具型 newsletter 与生活妙招品牌。", en: ".tips promises useful advice right in the address — for how-to sites, niche blogs, utility newsletters and life-hack brands." },
  "directory": { zh: ".directory 把「名录」写进域名，适合行业名录站、本地商家黄页、资源导航与工具聚合站。", en: ".directory writes the listing right into the address — for industry directories, local business listings, resource collections and tool roundups." },
  "exchange": { zh: ".exchange 把交易与流通写进域名，适合交易平台与撮合市场、二手与置换社区、汇率与积分兑换工具。", en: ".exchange writes the trade into the address — for marketplaces and matching platforms, swap communities, currency and points converters." },
  "institute": { zh: ".institute 把研究机构的庄重写进域名，适合研究院与智库、培训与认证机构、行业研究组织与非营利项目。", en: ".institute carries research-grade gravitas — for think tanks, training and certification bodies, industry research groups and nonprofits." },
  "international": { zh: ".international 把全球化身份写进域名，适合跨国业务与出海品牌、国际组织与 NGO、留学与跨境服务机构。", en: ".international writes the global footprint into the address — for cross-border brands, NGOs and international organizations, study-abroad and trade services." },
  "partners": { zh: ".partners 把合伙人身份写进域名，适合律所与咨询公司、基金与投资合伙、联盟与渠道合作计划。", en: ".partners is the professional-partnership nameplate — for law and consulting firms, investment partnerships, and channel or alliance programs." },
  "support": { zh: ".support 把「来这里求助」写进域名，适合产品帮助中心、客服与售后团队、技术支持服务商与公益互助组织。", en: ".support writes the help desk into the address — for product help centers, customer service teams, IT support providers and community helplines." },
  "plus": { zh: ".plus 把「增强版」写进域名，适合产品 Pro/会员版、增值服务、社区加强版与升级套餐页。", en: ".plus writes the upgrade into the address — for Pro/member tiers, value-added services, enhanced community editions and upgrade pages." },
  "house": { zh: ".house 把「家宅」写进域名，适合房产经纪与租售平台、家居装修品牌、民宿与设计工作室（House 命名传统）。", en: ".house writes home into the address — for real-estate agents and rental platforms, home & interior brands, guesthouses, and \"house\"-named studios." },
  "market": { zh: ".market 把「市集」写进域名，适合垂类电商市场、二手与本地市集、数字资产商店与农夫市集。", en: ".market writes the marketplace into the address — for vertical marketplaces, secondhand and local markets, digital-asset stores and farmers markets." },
  "watch": { zh: ".watch 一词双关「观看」与「腕表」，适合视频与直播站、监测与预警工具、腕表电商与钟表社区。", en: ".watch puns on viewing and wristwatches — for video and streaming sites, monitoring and alert tools, watch retailers and horology communities." },
  "style": { zh: ".style 把「风格」写进域名，适合时尚穿搭博主、造型师与形象顾问、美妆美发品牌与生活方式媒体。", en: ".style writes the aesthetic into the address — for fashion bloggers, stylists and image consultants, beauty brands and lifestyle media." },
  "show": { zh: ".show 把「节目」写进域名，适合播客与视频节目、演出与展览、直播秀与作品展示页。", en: ".show writes the program into the address — for podcasts and video shows, performances and exhibitions, live shows and showcase pages." },
  "website": { zh: ".website 把「网站」两个字直接写进域名，适合个人主页与作品集、小微企业官网、落地页与临时活动站。", en: ".website spells out exactly what it is — for personal pages and portfolios, small-business sites, landing pages and one-off event sites." },
  "technology": { zh: ".technology 把「技术」完整拼出来，适合科技公司官网、技术团队博客、深科技与硬科技品牌。", en: ".technology spells the word out in full — for tech company sites, engineering blogs, deep-tech and hard-tech brands." },
  "community": { zh: ".community 把「社区」写进域名，适合兴趣社群与论坛、开源项目社区、本地社区组织与会员制社群。", en: ".community writes belonging into the address — for interest groups and forums, open-source project communities, local organizations and membership clubs." },
  "education": { zh: ".education 把「教育」写进域名，适合培训机构与在线课程、教育科技产品、学校项目与教育内容站。", en: ".education writes learning into the address — for training providers and online courses, EdTech products, school programs and education media." },
  "training": { zh: ".training 把「培训」写进域名，适合职业技能培训、企业内训服务、健身与体能训练、认证课程站。", en: ".training writes practice into the address — for vocational skills training, corporate training services, fitness coaching and certification prep." },
  "love": { zh: ".love 把「爱」写进域名，适合婚礼与求婚站、情侣纪念页、公益与粉丝应援、宠物与兴趣「热爱」品牌。", en: ".love writes the feeling into the address — for wedding and proposal sites, couple pages, charities and fan projects, and passion brands." },
  "beauty": { zh: ".beauty 把「美」写进域名，适合美妆品牌与电商、美容院与皮肤管理、美妆博主与教程站、造型工作室。", en: ".beauty writes the industry into the address — for beauty brands and e-commerce, salons and skincare studios, beauty creators and styling studios." },
  "fashion": { zh: ".fashion 把「时尚」写进域名，适合服装品牌与买手店、独立设计师、时尚电商与穿搭博主。", en: ".fashion writes the runway into the address — for clothing brands and boutiques, independent designers, fashion e-commerce and style creators." },
  "work": { zh: ".work 把「工作」写进域名，适合招聘与求职站、自由职业者作品集、远程办公工具、职业服务与劳务平台。", en: ".work writes the job into the address — for hiring and job boards, freelancer portfolios, remote-work tools and professional services." },
  "sale": { zh: ".sale 把「促销」写进域名，适合促销活动站、折扣电商与清仓频道、二手转卖平台、房产车辆出售页。", en: ".sale writes the discount into the address — for promo campaign sites, outlet e-commerce, resale platforms and for-sale listing pages." },
  "help": { zh: ".help 把「帮助」写进域名，适合产品帮助中心与文档站、客服与支持入口、公益求助与互助平台、工具教程站。", en: ".help writes the answer into the address — for product help centers and docs, support entry points, mutual-aid platforms and tutorial sites." },
  "wedding": { zh: ".wedding 把「婚礼」写进域名，适合婚礼请柬与纪念站、婚庆策划与场地、婚纱摄影与礼服、婚礼跟拍团队。", en: ".wedding writes the big day into the address — for invitation and keepsake sites, planners and venues, bridal photography and wedding crews." },
  "law": { zh: ".law 把「法律」写进域名，适合律师事务所、独立执业律师、法律科技产品、法律咨询与普法内容站。", en: ".law writes the profession into the address — for law firms, solo attorneys, legal-tech products and legal-content sites." },
  "tax": { zh: ".tax 把「税」写进域名，适合税务师与会计事务所、报税软件、税务咨询与筹划、税法内容站。", en: ".tax writes the business into the address — for tax and accounting firms, filing software, tax advisory services and tax-law content sites." },
  "menu": { zh: ".menu 把「菜单」写进域名，适合餐厅在线菜单、扫码点餐系统、外卖与订餐平台、餐饮品牌官网。", en: ".menu writes the card into the address — for restaurant online menus, QR ordering systems, delivery platforms and restaurant brand sites." },
  "bike": { zh: ".bike 把「自行车」写进域名，适合自行车品牌与车店、骑行俱乐部与赛事、租车与修车服务、骑行装备电商。", en: ".bike writes the ride into the address — for bike brands and shops, cycling clubs and races, rental and repair services, gear e-commerce." },
  "toys": { zh: ".toys 把「玩具」写进域名，适合玩具品牌与电商、潮玩与手办店、桌游与积木社区、儿童教育玩具。", en: ".toys writes the shelf into the address — for toy brands and e-commerce, designer-toy and figure shops, board-game communities and educational toys." },
  "shoes": { zh: ".shoes 把「鞋」写进域名，适合鞋履品牌与电商、球鞋店与鞋圈社区、手工鞋定制、洗鞋修鞋服务。", en: ".shoes writes the category into the address — for footwear brands and e-commerce, sneaker shops and communities, custom shoemakers and shoe-care services." },
  "travel": { zh: ".travel 是旅游行业的专属老牌后缀，适合旅行社与定制游、旅游攻略与目的地站、酒店民宿预订、签证与出行服务。", en: ".travel is the tourism industry's veteran dedicated TLD — for travel agencies and tour operators, destination guides, hotel booking and visa services." },
  "tours": { zh: ".tours 把「跟团/路线」写进域名，适合一日游与包车路线、徒步登山向导、城市导览与美食团、景区体验项目。", en: ".tours writes the product into the address — for day trips and chartered routes, hiking guides, city walks and food tours, and attraction experiences." },
  "vacations": { zh: ".vacations 把「度假」写进域名，适合度假套餐与海岛游、度假村与民宿集群、亲子与蜜月主题游、度假攻略内容站。", en: ".vacations writes the getaway into the address — for vacation packages and island trips, resorts and lodging clusters, family and honeymoon themes, and vacation-planning content." },
  "holiday": { zh: ".holiday 把「假日」写进域名，适合节日礼品与假日营销、假期出行产品、节庆活动策划、假日主题内容站。", en: ".holiday writes the festive break into the address — for seasonal gifts and holiday marketing, getaway products, festive event planning and holiday-themed content." },
  "flights": { zh: ".flights 把「机票/航班」写进域名，适合机票比价与订票、航线攻略与里程玩法、包机与商务航空、低价机票订阅提醒。", en: ".flights writes air travel into the address — for fare comparison and booking, route guides and miles hacking, charter and business aviation, and cheap-fare alert services." },
  "taxi": { zh: ".taxi 把「打车/接送」写进域名，适合本地出租车与网约车队、机场接送与包车、景区与酒店接驳、代驾与货运小车队。", en: ".taxi writes the ride into the address — for local cab and ride-hail fleets, airport transfers and charters, resort and hotel shuttles, and designated-driver services." },
  "properties": { zh: ".properties 把「物业/房产」写进域名，适合房产中介与经纪团队、物业管理公司、房源展示与楼盘官网、房产投资组合。", en: ".properties writes real estate into the address — for agencies and broker teams, property management firms, listing showcases and development sites, and investment portfolios." },
  "rentals": { zh: ".rentals 把「出租」写进域名，适合民宿与短租运营、长租公寓与租房平台、汽车与设备租赁、婚礼与活动物品出租。", en: ".rentals writes the business model into the address — for vacation and short-term rentals, apartment and housing platforms, car and equipment hire, and event gear rental." },
  "apartments": { zh: ".apartments 把「公寓」写进域名，适合长租公寓品牌、服务式公寓与公寓式酒店、公寓楼盘招租官网、学生公寓运营。", en: ".apartments writes the property type into the address — for long-term apartment brands, serviced apartments and aparthotels, leasing sites for developments, and student housing operators." },
  "builders": { zh: ".builders 把「建造者」写进域名，适合建筑与施工承包商、自建房与装修团队、房屋定制与模块化建造、开发者社区与创客团队。", en: ".builders writes the identity into the address — for construction contractors, custom-home and renovation crews, modular builders, and maker/developer communities." },
  "construction": { zh: ".construction 把「建筑工程」写进域名，适合建筑工程公司、总包与分包商、基建与市政工程、建材与工程设备供应商。", en: ".construction writes the industry into the address — for construction firms, general and sub-contractors, infrastructure and civil works, and building material suppliers." },
  "repair": { zh: ".repair 把「维修」写进域名，适合手机与电脑维修店、家电与家庭维修服务、汽车维修与保养、维修教程与配件商城。", en: ".repair writes the service into the address — for phone and computer repair shops, appliance and home repair services, auto repair and maintenance, and repair guides and parts stores." },
  "energy": { zh: ".energy 把「能源」写进域名，适合能源公司与电力服务商、光伏与储能企业、充电桩与新能源汽车配套、能源科技与碳管理 SaaS。", en: ".energy writes the industry into the address — for power companies and utilities, solar and storage firms, EV charging providers, and energy-tech and carbon SaaS." },
  "solar": { zh: ".solar 把「光伏」写进域名，适合光伏安装商与经销商、户用与工商业光伏方案、太阳能组件与逆变器品牌、光伏电站运维监控。", en: ".solar writes the product into the address — for solar installers and dealers, residential and commercial PV providers, panel and inverter brands, and plant monitoring platforms." },
  "green": { zh: ".green 把「绿色环保」写进域名，适合可持续品牌与环保产品、绿色金融与 ESG 服务、环保组织与公益项目、有机食品与低碳生活方式。", en: ".green writes the values into the address — for sustainable brands and eco products, green finance and ESG services, environmental nonprofits, and organic and low-carbon lifestyle sites." },
  "eco": { zh: ".eco 把「生态环保」写进域名，适合环保组织与气候行动项目、可持续品牌官网、碳中和与循环经济服务、生态旅游与自然保护。", en: ".eco writes the commitment into the address — for environmental nonprofits and climate projects, sustainable brand sites, carbon-neutral and circular-economy services, and ecotourism." },
  "earth": { zh: ".earth 把「地球」写进域名，适合环境与气候内容站、地理与地图数据服务、户外与自然探索品牌、全球公益与可持续倡议。", en: ".earth writes the planet into the address — for environment and climate content sites, geo and mapping services, outdoor and nature brands, and global sustainability initiatives." },
  "engineering": { zh: ".engineering 把「工程」写进域名，适合工程设计与咨询公司、机械与电气工程服务、软件工程团队博客、工程教育与认证机构。", en: ".engineering writes the profession into the address — for engineering design and consulting firms, mechanical and electrical services, software engineering blogs, and engineering education." },
} satisfies Record<Tld, Localized>;
